// Code generated by ent, DO NOT EDIT.

package signalrootcauselink

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the signalrootcauselink type in the database.
	Label = "signal_root_cause_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSignalID holds the string denoting the signal_id field in the database.
	FieldSignalID = "signal_id"
	// FieldRootCauseID holds the string denoting the root_cause_id field in the database.
	FieldRootCauseID = "root_cause_id"
	// FieldLinkedAt holds the string denoting the linked_at field in the database.
	FieldLinkedAt = "linked_at"
	// Table holds the table name of the signalrootcauselink in the database.
	Table = "signal_root_cause_links"
)

// Columns holds all SQL columns for signalrootcauselink fields.
var Columns = []string{
	FieldID,
	FieldSignalID,
	FieldRootCauseID,
	FieldLinkedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLinkedAt holds the default value on creation for the "linked_at" field.
	DefaultLinkedAt func() time.Time
)

// OrderOption defines the ordering options for the SignalRootCauseLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySignalID orders the results by the signal_id field.
func BySignalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignalID, opts...).ToFunc()
}

// ByRootCauseID orders the results by the root_cause_id field.
func ByRootCauseID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootCauseID, opts...).ToFunc()
}

// ByLinkedAt orders the results by the linked_at field.
func ByLinkedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkedAt, opts...).ToFunc()
}
