// Code generated by ent, DO NOT EDIT.

package signalrootcauselink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnisignal/store/sqlite/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLTE(FieldID, id))
}

// SignalID applies equality check predicate on the "signal_id" field. It's identical to SignalIDEQ.
func SignalID(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldSignalID, v))
}

// RootCauseID applies equality check predicate on the "root_cause_id" field. It's identical to RootCauseIDEQ.
func RootCauseID(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldRootCauseID, v))
}

// LinkedAt applies equality check predicate on the "linked_at" field. It's identical to LinkedAtEQ.
func LinkedAt(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldLinkedAt, v))
}

// SignalIDEQ applies the EQ predicate on the "signal_id" field.
func SignalIDEQ(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldSignalID, v))
}

// SignalIDNEQ applies the NEQ predicate on the "signal_id" field.
func SignalIDNEQ(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNEQ(FieldSignalID, v))
}

// SignalIDIn applies the In predicate on the "signal_id" field.
func SignalIDIn(vs ...string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldIn(FieldSignalID, vs...))
}

// SignalIDNotIn applies the NotIn predicate on the "signal_id" field.
func SignalIDNotIn(vs ...string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNotIn(FieldSignalID, vs...))
}

// SignalIDGT applies the GT predicate on the "signal_id" field.
func SignalIDGT(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGT(FieldSignalID, v))
}

// SignalIDGTE applies the GTE predicate on the "signal_id" field.
func SignalIDGTE(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGTE(FieldSignalID, v))
}

// SignalIDLT applies the LT predicate on the "signal_id" field.
func SignalIDLT(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLT(FieldSignalID, v))
}

// SignalIDLTE applies the LTE predicate on the "signal_id" field.
func SignalIDLTE(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLTE(FieldSignalID, v))
}

// SignalIDContains applies the Contains predicate on the "signal_id" field.
func SignalIDContains(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldContains(FieldSignalID, v))
}

// SignalIDHasPrefix applies the HasPrefix predicate on the "signal_id" field.
func SignalIDHasPrefix(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldHasPrefix(FieldSignalID, v))
}

// SignalIDHasSuffix applies the HasSuffix predicate on the "signal_id" field.
func SignalIDHasSuffix(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldHasSuffix(FieldSignalID, v))
}

// SignalIDEqualFold applies the EqualFold predicate on the "signal_id" field.
func SignalIDEqualFold(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEqualFold(FieldSignalID, v))
}

// SignalIDContainsFold applies the ContainsFold predicate on the "signal_id" field.
func SignalIDContainsFold(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldContainsFold(FieldSignalID, v))
}

// RootCauseIDEQ applies the EQ predicate on the "root_cause_id" field.
func RootCauseIDEQ(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldRootCauseID, v))
}

// RootCauseIDNEQ applies the NEQ predicate on the "root_cause_id" field.
func RootCauseIDNEQ(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNEQ(FieldRootCauseID, v))
}

// RootCauseIDIn applies the In predicate on the "root_cause_id" field.
func RootCauseIDIn(vs ...string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldIn(FieldRootCauseID, vs...))
}

// RootCauseIDNotIn applies the NotIn predicate on the "root_cause_id" field.
func RootCauseIDNotIn(vs ...string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNotIn(FieldRootCauseID, vs...))
}

// RootCauseIDGT applies the GT predicate on the "root_cause_id" field.
func RootCauseIDGT(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGT(FieldRootCauseID, v))
}

// RootCauseIDGTE applies the GTE predicate on the "root_cause_id" field.
func RootCauseIDGTE(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGTE(FieldRootCauseID, v))
}

// RootCauseIDLT applies the LT predicate on the "root_cause_id" field.
func RootCauseIDLT(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLT(FieldRootCauseID, v))
}

// RootCauseIDLTE applies the LTE predicate on the "root_cause_id" field.
func RootCauseIDLTE(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLTE(FieldRootCauseID, v))
}

// RootCauseIDContains applies the Contains predicate on the "root_cause_id" field.
func RootCauseIDContains(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldContains(FieldRootCauseID, v))
}

// RootCauseIDHasPrefix applies the HasPrefix predicate on the "root_cause_id" field.
func RootCauseIDHasPrefix(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldHasPrefix(FieldRootCauseID, v))
}

// RootCauseIDHasSuffix applies the HasSuffix predicate on the "root_cause_id" field.
func RootCauseIDHasSuffix(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldHasSuffix(FieldRootCauseID, v))
}

// RootCauseIDEqualFold applies the EqualFold predicate on the "root_cause_id" field.
func RootCauseIDEqualFold(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEqualFold(FieldRootCauseID, v))
}

// RootCauseIDContainsFold applies the ContainsFold predicate on the "root_cause_id" field.
func RootCauseIDContainsFold(v string) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldContainsFold(FieldRootCauseID, v))
}

// LinkedAtEQ applies the EQ predicate on the "linked_at" field.
func LinkedAtEQ(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldEQ(FieldLinkedAt, v))
}

// LinkedAtNEQ applies the NEQ predicate on the "linked_at" field.
func LinkedAtNEQ(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNEQ(FieldLinkedAt, v))
}

// LinkedAtIn applies the In predicate on the "linked_at" field.
func LinkedAtIn(vs ...time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldIn(FieldLinkedAt, vs...))
}

// LinkedAtNotIn applies the NotIn predicate on the "linked_at" field.
func LinkedAtNotIn(vs ...time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldNotIn(FieldLinkedAt, vs...))
}

// LinkedAtGT applies the GT predicate on the "linked_at" field.
func LinkedAtGT(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGT(FieldLinkedAt, v))
}

// LinkedAtGTE applies the GTE predicate on the "linked_at" field.
func LinkedAtGTE(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldGTE(FieldLinkedAt, v))
}

// LinkedAtLT applies the LT predicate on the "linked_at" field.
func LinkedAtLT(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLT(FieldLinkedAt, v))
}

// LinkedAtLTE applies the LTE predicate on the "linked_at" field.
func LinkedAtLTE(v time.Time) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.FieldLTE(FieldLinkedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SignalRootCauseLink) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SignalRootCauseLink) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SignalRootCauseLink) predicate.SignalRootCauseLink {
	return predicate.SignalRootCauseLink(sql.NotPredicates(p))
}
