// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/plexusone/omnisignal/store/sqlite/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnisignal/store/sqlite/ent/rootcause"
	entsignal "github.com/plexusone/omnisignal/store/sqlite/ent/signal"
	"github.com/plexusone/omnisignal/store/sqlite/ent/signalrootcauselink"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// RootCause is the client for interacting with the RootCause builders.
	RootCause *RootCauseClient
	// Signal is the client for interacting with the Signal builders.
	Signal *SignalClient
	// SignalRootCauseLink is the client for interacting with the SignalRootCauseLink builders.
	SignalRootCauseLink *SignalRootCauseLinkClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.RootCause = NewRootCauseClient(c.config)
	c.Signal = NewSignalClient(c.config)
	c.SignalRootCauseLink = NewSignalRootCauseLinkClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		RootCause:           NewRootCauseClient(cfg),
		Signal:              NewSignalClient(cfg),
		SignalRootCauseLink: NewSignalRootCauseLinkClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                 ctx,
		config:              cfg,
		RootCause:           NewRootCauseClient(cfg),
		Signal:              NewSignalClient(cfg),
		SignalRootCauseLink: NewSignalRootCauseLinkClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		RootCause.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.RootCause.Use(hooks...)
	c.Signal.Use(hooks...)
	c.SignalRootCauseLink.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.RootCause.Intercept(interceptors...)
	c.Signal.Intercept(interceptors...)
	c.SignalRootCauseLink.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *RootCauseMutation:
		return c.RootCause.mutate(ctx, m)
	case *SignalMutation:
		return c.Signal.mutate(ctx, m)
	case *SignalRootCauseLinkMutation:
		return c.SignalRootCauseLink.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// RootCauseClient is a client for the RootCause schema.
type RootCauseClient struct {
	config
}

// NewRootCauseClient returns a client for the RootCause from the given config.
func NewRootCauseClient(c config) *RootCauseClient {
	return &RootCauseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `rootcause.Hooks(f(g(h())))`.
func (c *RootCauseClient) Use(hooks ...Hook) {
	c.hooks.RootCause = append(c.hooks.RootCause, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `rootcause.Intercept(f(g(h())))`.
func (c *RootCauseClient) Intercept(interceptors ...Interceptor) {
	c.inters.RootCause = append(c.inters.RootCause, interceptors...)
}

// Create returns a builder for creating a RootCause entity.
func (c *RootCauseClient) Create() *RootCauseCreate {
	mutation := newRootCauseMutation(c.config, OpCreate)
	return &RootCauseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RootCause entities.
func (c *RootCauseClient) CreateBulk(builders ...*RootCauseCreate) *RootCauseCreateBulk {
	return &RootCauseCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RootCauseClient) MapCreateBulk(slice any, setFunc func(*RootCauseCreate, int)) *RootCauseCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RootCauseCreateBulk{err: fmt.Errorf("calling to RootCauseClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RootCauseCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RootCauseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RootCause.
func (c *RootCauseClient) Update() *RootCauseUpdate {
	mutation := newRootCauseMutation(c.config, OpUpdate)
	return &RootCauseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RootCauseClient) UpdateOne(_m *RootCause) *RootCauseUpdateOne {
	mutation := newRootCauseMutation(c.config, OpUpdateOne, withRootCause(_m))
	return &RootCauseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RootCauseClient) UpdateOneID(id string) *RootCauseUpdateOne {
	mutation := newRootCauseMutation(c.config, OpUpdateOne, withRootCauseID(id))
	return &RootCauseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RootCause.
func (c *RootCauseClient) Delete() *RootCauseDelete {
	mutation := newRootCauseMutation(c.config, OpDelete)
	return &RootCauseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RootCauseClient) DeleteOne(_m *RootCause) *RootCauseDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RootCauseClient) DeleteOneID(id string) *RootCauseDeleteOne {
	builder := c.Delete().Where(rootcause.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RootCauseDeleteOne{builder}
}

// Query returns a query builder for RootCause.
func (c *RootCauseClient) Query() *RootCauseQuery {
	return &RootCauseQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRootCause},
		inters: c.Interceptors(),
	}
}

// Get returns a RootCause entity by its id.
func (c *RootCauseClient) Get(ctx context.Context, id string) (*RootCause, error) {
	return c.Query().Where(rootcause.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RootCauseClient) GetX(ctx context.Context, id string) *RootCause {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RootCauseClient) Hooks() []Hook {
	return c.hooks.RootCause
}

// Interceptors returns the client interceptors.
func (c *RootCauseClient) Interceptors() []Interceptor {
	return c.inters.RootCause
}

func (c *RootCauseClient) mutate(ctx context.Context, m *RootCauseMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RootCauseCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RootCauseUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RootCauseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RootCauseDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RootCause mutation op: %q", m.Op())
	}
}

// SignalClient is a client for the Signal schema.
type SignalClient struct {
	config
}

// NewSignalClient returns a client for the Signal from the given config.
func NewSignalClient(c config) *SignalClient {
	return &SignalClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `entsignal.Hooks(f(g(h())))`.
func (c *SignalClient) Use(hooks ...Hook) {
	c.hooks.Signal = append(c.hooks.Signal, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `entsignal.Intercept(f(g(h())))`.
func (c *SignalClient) Intercept(interceptors ...Interceptor) {
	c.inters.Signal = append(c.inters.Signal, interceptors...)
}

// Create returns a builder for creating a Signal entity.
func (c *SignalClient) Create() *SignalCreate {
	mutation := newSignalMutation(c.config, OpCreate)
	return &SignalCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Signal entities.
func (c *SignalClient) CreateBulk(builders ...*SignalCreate) *SignalCreateBulk {
	return &SignalCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SignalClient) MapCreateBulk(slice any, setFunc func(*SignalCreate, int)) *SignalCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SignalCreateBulk{err: fmt.Errorf("calling to SignalClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SignalCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SignalCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Signal.
func (c *SignalClient) Update() *SignalUpdate {
	mutation := newSignalMutation(c.config, OpUpdate)
	return &SignalUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SignalClient) UpdateOne(_m *Signal) *SignalUpdateOne {
	mutation := newSignalMutation(c.config, OpUpdateOne, withSignal(_m))
	return &SignalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SignalClient) UpdateOneID(id string) *SignalUpdateOne {
	mutation := newSignalMutation(c.config, OpUpdateOne, withSignalID(id))
	return &SignalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Signal.
func (c *SignalClient) Delete() *SignalDelete {
	mutation := newSignalMutation(c.config, OpDelete)
	return &SignalDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SignalClient) DeleteOne(_m *Signal) *SignalDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SignalClient) DeleteOneID(id string) *SignalDeleteOne {
	builder := c.Delete().Where(entsignal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SignalDeleteOne{builder}
}

// Query returns a query builder for Signal.
func (c *SignalClient) Query() *SignalQuery {
	return &SignalQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSignal},
		inters: c.Interceptors(),
	}
}

// Get returns a Signal entity by its id.
func (c *SignalClient) Get(ctx context.Context, id string) (*Signal, error) {
	return c.Query().Where(entsignal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SignalClient) GetX(ctx context.Context, id string) *Signal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SignalClient) Hooks() []Hook {
	return c.hooks.Signal
}

// Interceptors returns the client interceptors.
func (c *SignalClient) Interceptors() []Interceptor {
	return c.inters.Signal
}

func (c *SignalClient) mutate(ctx context.Context, m *SignalMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SignalCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SignalUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SignalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SignalDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Signal mutation op: %q", m.Op())
	}
}

// SignalRootCauseLinkClient is a client for the SignalRootCauseLink schema.
type SignalRootCauseLinkClient struct {
	config
}

// NewSignalRootCauseLinkClient returns a client for the SignalRootCauseLink from the given config.
func NewSignalRootCauseLinkClient(c config) *SignalRootCauseLinkClient {
	return &SignalRootCauseLinkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `signalrootcauselink.Hooks(f(g(h())))`.
func (c *SignalRootCauseLinkClient) Use(hooks ...Hook) {
	c.hooks.SignalRootCauseLink = append(c.hooks.SignalRootCauseLink, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `signalrootcauselink.Intercept(f(g(h())))`.
func (c *SignalRootCauseLinkClient) Intercept(interceptors ...Interceptor) {
	c.inters.SignalRootCauseLink = append(c.inters.SignalRootCauseLink, interceptors...)
}

// Create returns a builder for creating a SignalRootCauseLink entity.
func (c *SignalRootCauseLinkClient) Create() *SignalRootCauseLinkCreate {
	mutation := newSignalRootCauseLinkMutation(c.config, OpCreate)
	return &SignalRootCauseLinkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SignalRootCauseLink entities.
func (c *SignalRootCauseLinkClient) CreateBulk(builders ...*SignalRootCauseLinkCreate) *SignalRootCauseLinkCreateBulk {
	return &SignalRootCauseLinkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SignalRootCauseLinkClient) MapCreateBulk(slice any, setFunc func(*SignalRootCauseLinkCreate, int)) *SignalRootCauseLinkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SignalRootCauseLinkCreateBulk{err: fmt.Errorf("calling to SignalRootCauseLinkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SignalRootCauseLinkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SignalRootCauseLinkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SignalRootCauseLink.
func (c *SignalRootCauseLinkClient) Update() *SignalRootCauseLinkUpdate {
	mutation := newSignalRootCauseLinkMutation(c.config, OpUpdate)
	return &SignalRootCauseLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SignalRootCauseLinkClient) UpdateOne(_m *SignalRootCauseLink) *SignalRootCauseLinkUpdateOne {
	mutation := newSignalRootCauseLinkMutation(c.config, OpUpdateOne, withSignalRootCauseLink(_m))
	return &SignalRootCauseLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SignalRootCauseLinkClient) UpdateOneID(id int) *SignalRootCauseLinkUpdateOne {
	mutation := newSignalRootCauseLinkMutation(c.config, OpUpdateOne, withSignalRootCauseLinkID(id))
	return &SignalRootCauseLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SignalRootCauseLink.
func (c *SignalRootCauseLinkClient) Delete() *SignalRootCauseLinkDelete {
	mutation := newSignalRootCauseLinkMutation(c.config, OpDelete)
	return &SignalRootCauseLinkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SignalRootCauseLinkClient) DeleteOne(_m *SignalRootCauseLink) *SignalRootCauseLinkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SignalRootCauseLinkClient) DeleteOneID(id int) *SignalRootCauseLinkDeleteOne {
	builder := c.Delete().Where(signalrootcauselink.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SignalRootCauseLinkDeleteOne{builder}
}

// Query returns a query builder for SignalRootCauseLink.
func (c *SignalRootCauseLinkClient) Query() *SignalRootCauseLinkQuery {
	return &SignalRootCauseLinkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSignalRootCauseLink},
		inters: c.Interceptors(),
	}
}

// Get returns a SignalRootCauseLink entity by its id.
func (c *SignalRootCauseLinkClient) Get(ctx context.Context, id int) (*SignalRootCauseLink, error) {
	return c.Query().Where(signalrootcauselink.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SignalRootCauseLinkClient) GetX(ctx context.Context, id int) *SignalRootCauseLink {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SignalRootCauseLinkClient) Hooks() []Hook {
	return c.hooks.SignalRootCauseLink
}

// Interceptors returns the client interceptors.
func (c *SignalRootCauseLinkClient) Interceptors() []Interceptor {
	return c.inters.SignalRootCauseLink
}

func (c *SignalRootCauseLinkClient) mutate(ctx context.Context, m *SignalRootCauseLinkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SignalRootCauseLinkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SignalRootCauseLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SignalRootCauseLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SignalRootCauseLinkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SignalRootCauseLink mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		RootCause, Signal, SignalRootCauseLink []ent.Hook
	}
	inters struct {
		RootCause, Signal, SignalRootCauseLink []ent.Interceptor
	}
)
