// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnisignal/store/sqlite/ent/rootcause"
	"github.com/plexusone/signal-spec/pkg/common"
)

// RootCauseCreate is the builder for creating a RootCause entity.
type RootCauseCreate struct {
	config
	mutation *RootCauseMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *RootCauseCreate) SetTitle(v string) *RootCauseCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RootCauseCreate) SetDescription(v string) *RootCauseCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableDescription(v *string) *RootCauseCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RootCauseCreate) SetStatus(v string) *RootCauseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetDomainName sets the "domain_name" field.
func (_c *RootCauseCreate) SetDomainName(v string) *RootCauseCreate {
	_c.mutation.SetDomainName(v)
	return _c
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (_c *RootCauseCreate) SetDomainSubdomain(v string) *RootCauseCreate {
	_c.mutation.SetDomainSubdomain(v)
	return _c
}

// SetNillableDomainSubdomain sets the "domain_subdomain" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableDomainSubdomain(v *string) *RootCauseCreate {
	if v != nil {
		_c.SetDomainSubdomain(*v)
	}
	return _c
}

// SetDomainTeam sets the "domain_team" field.
func (_c *RootCauseCreate) SetDomainTeam(v string) *RootCauseCreate {
	_c.mutation.SetDomainTeam(v)
	return _c
}

// SetNillableDomainTeam sets the "domain_team" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableDomainTeam(v *string) *RootCauseCreate {
	if v != nil {
		_c.SetDomainTeam(*v)
	}
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *RootCauseCreate) SetSeverity(v string) *RootCauseCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetSymptomPatterns sets the "symptom_patterns" field.
func (_c *RootCauseCreate) SetSymptomPatterns(v []string) *RootCauseCreate {
	_c.mutation.SetSymptomPatterns(v)
	return _c
}

// SetImpactSignalCount sets the "impact_signal_count" field.
func (_c *RootCauseCreate) SetImpactSignalCount(v int) *RootCauseCreate {
	_c.mutation.SetImpactSignalCount(v)
	return _c
}

// SetNillableImpactSignalCount sets the "impact_signal_count" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableImpactSignalCount(v *int) *RootCauseCreate {
	if v != nil {
		_c.SetImpactSignalCount(*v)
	}
	return _c
}

// SetImpactAffectedCustomers sets the "impact_affected_customers" field.
func (_c *RootCauseCreate) SetImpactAffectedCustomers(v int) *RootCauseCreate {
	_c.mutation.SetImpactAffectedCustomers(v)
	return _c
}

// SetNillableImpactAffectedCustomers sets the "impact_affected_customers" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableImpactAffectedCustomers(v *int) *RootCauseCreate {
	if v != nil {
		_c.SetImpactAffectedCustomers(*v)
	}
	return _c
}

// SetImpactAffectedEntities sets the "impact_affected_entities" field.
func (_c *RootCauseCreate) SetImpactAffectedEntities(v []common.Entity) *RootCauseCreate {
	_c.mutation.SetImpactAffectedEntities(v)
	return _c
}

// SetImpactEscalationRate sets the "impact_escalation_rate" field.
func (_c *RootCauseCreate) SetImpactEscalationRate(v float64) *RootCauseCreate {
	_c.mutation.SetImpactEscalationRate(v)
	return _c
}

// SetNillableImpactEscalationRate sets the "impact_escalation_rate" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableImpactEscalationRate(v *float64) *RootCauseCreate {
	if v != nil {
		_c.SetImpactEscalationRate(*v)
	}
	return _c
}

// SetImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field.
func (_c *RootCauseCreate) SetImpactEstimatedRevenueLoss(v float64) *RootCauseCreate {
	_c.mutation.SetImpactEstimatedRevenueLoss(v)
	return _c
}

// SetNillableImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableImpactEstimatedRevenueLoss(v *float64) *RootCauseCreate {
	if v != nil {
		_c.SetImpactEstimatedRevenueLoss(*v)
	}
	return _c
}

// SetTrendDirection sets the "trend_direction" field.
func (_c *RootCauseCreate) SetTrendDirection(v string) *RootCauseCreate {
	_c.mutation.SetTrendDirection(v)
	return _c
}

// SetNillableTrendDirection sets the "trend_direction" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableTrendDirection(v *string) *RootCauseCreate {
	if v != nil {
		_c.SetTrendDirection(*v)
	}
	return _c
}

// SetTrendVelocity sets the "trend_velocity" field.
func (_c *RootCauseCreate) SetTrendVelocity(v float64) *RootCauseCreate {
	_c.mutation.SetTrendVelocity(v)
	return _c
}

// SetNillableTrendVelocity sets the "trend_velocity" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableTrendVelocity(v *float64) *RootCauseCreate {
	if v != nil {
		_c.SetTrendVelocity(*v)
	}
	return _c
}

// SetTrendPeriodStart sets the "trend_period_start" field.
func (_c *RootCauseCreate) SetTrendPeriodStart(v time.Time) *RootCauseCreate {
	_c.mutation.SetTrendPeriodStart(v)
	return _c
}

// SetNillableTrendPeriodStart sets the "trend_period_start" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableTrendPeriodStart(v *time.Time) *RootCauseCreate {
	if v != nil {
		_c.SetTrendPeriodStart(*v)
	}
	return _c
}

// SetTrendPeriodEnd sets the "trend_period_end" field.
func (_c *RootCauseCreate) SetTrendPeriodEnd(v time.Time) *RootCauseCreate {
	_c.mutation.SetTrendPeriodEnd(v)
	return _c
}

// SetNillableTrendPeriodEnd sets the "trend_period_end" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableTrendPeriodEnd(v *time.Time) *RootCauseCreate {
	if v != nil {
		_c.SetTrendPeriodEnd(*v)
	}
	return _c
}

// SetPriorityScore sets the "priority_score" field.
func (_c *RootCauseCreate) SetPriorityScore(v int) *RootCauseCreate {
	_c.mutation.SetPriorityScore(v)
	return _c
}

// SetNillablePriorityScore sets the "priority_score" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillablePriorityScore(v *int) *RootCauseCreate {
	if v != nil {
		_c.SetPriorityScore(*v)
	}
	return _c
}

// SetFirstSeen sets the "first_seen" field.
func (_c *RootCauseCreate) SetFirstSeen(v time.Time) *RootCauseCreate {
	_c.mutation.SetFirstSeen(v)
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *RootCauseCreate) SetLastSeen(v time.Time) *RootCauseCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetOwnerTeam sets the "owner_team" field.
func (_c *RootCauseCreate) SetOwnerTeam(v string) *RootCauseCreate {
	_c.mutation.SetOwnerTeam(v)
	return _c
}

// SetNillableOwnerTeam sets the "owner_team" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableOwnerTeam(v *string) *RootCauseCreate {
	if v != nil {
		_c.SetOwnerTeam(*v)
	}
	return _c
}

// SetRemediationID sets the "remediation_id" field.
func (_c *RootCauseCreate) SetRemediationID(v string) *RootCauseCreate {
	_c.mutation.SetRemediationID(v)
	return _c
}

// SetNillableRemediationID sets the "remediation_id" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableRemediationID(v *string) *RootCauseCreate {
	if v != nil {
		_c.SetRemediationID(*v)
	}
	return _c
}

// SetRecurrenceCount sets the "recurrence_count" field.
func (_c *RootCauseCreate) SetRecurrenceCount(v int) *RootCauseCreate {
	_c.mutation.SetRecurrenceCount(v)
	return _c
}

// SetNillableRecurrenceCount sets the "recurrence_count" field if the given value is not nil.
func (_c *RootCauseCreate) SetNillableRecurrenceCount(v *int) *RootCauseCreate {
	if v != nil {
		_c.SetRecurrenceCount(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RootCauseCreate) SetMetadata(v map[string]interface{}) *RootCauseCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *RootCauseCreate) SetTags(v []common.Tag) *RootCauseCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RootCauseCreate) SetID(v string) *RootCauseCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RootCauseMutation object of the builder.
func (_c *RootCauseCreate) Mutation() *RootCauseMutation {
	return _c.mutation
}

// Save creates the RootCause in the database.
func (_c *RootCauseCreate) Save(ctx context.Context) (*RootCause, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RootCauseCreate) SaveX(ctx context.Context) *RootCause {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RootCauseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RootCauseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RootCauseCreate) defaults() {
	if _, ok := _c.mutation.ImpactSignalCount(); !ok {
		v := rootcause.DefaultImpactSignalCount
		_c.mutation.SetImpactSignalCount(v)
	}
	if _, ok := _c.mutation.ImpactAffectedCustomers(); !ok {
		v := rootcause.DefaultImpactAffectedCustomers
		_c.mutation.SetImpactAffectedCustomers(v)
	}
	if _, ok := _c.mutation.ImpactEscalationRate(); !ok {
		v := rootcause.DefaultImpactEscalationRate
		_c.mutation.SetImpactEscalationRate(v)
	}
	if _, ok := _c.mutation.ImpactEstimatedRevenueLoss(); !ok {
		v := rootcause.DefaultImpactEstimatedRevenueLoss
		_c.mutation.SetImpactEstimatedRevenueLoss(v)
	}
	if _, ok := _c.mutation.TrendVelocity(); !ok {
		v := rootcause.DefaultTrendVelocity
		_c.mutation.SetTrendVelocity(v)
	}
	if _, ok := _c.mutation.PriorityScore(); !ok {
		v := rootcause.DefaultPriorityScore
		_c.mutation.SetPriorityScore(v)
	}
	if _, ok := _c.mutation.RecurrenceCount(); !ok {
		v := rootcause.DefaultRecurrenceCount
		_c.mutation.SetRecurrenceCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RootCauseCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "RootCause.title"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RootCause.status"`)}
	}
	if _, ok := _c.mutation.DomainName(); !ok {
		return &ValidationError{Name: "domain_name", err: errors.New(`ent: missing required field "RootCause.domain_name"`)}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "RootCause.severity"`)}
	}
	if _, ok := _c.mutation.ImpactSignalCount(); !ok {
		return &ValidationError{Name: "impact_signal_count", err: errors.New(`ent: missing required field "RootCause.impact_signal_count"`)}
	}
	if _, ok := _c.mutation.ImpactAffectedCustomers(); !ok {
		return &ValidationError{Name: "impact_affected_customers", err: errors.New(`ent: missing required field "RootCause.impact_affected_customers"`)}
	}
	if _, ok := _c.mutation.ImpactEscalationRate(); !ok {
		return &ValidationError{Name: "impact_escalation_rate", err: errors.New(`ent: missing required field "RootCause.impact_escalation_rate"`)}
	}
	if _, ok := _c.mutation.ImpactEstimatedRevenueLoss(); !ok {
		return &ValidationError{Name: "impact_estimated_revenue_loss", err: errors.New(`ent: missing required field "RootCause.impact_estimated_revenue_loss"`)}
	}
	if _, ok := _c.mutation.TrendVelocity(); !ok {
		return &ValidationError{Name: "trend_velocity", err: errors.New(`ent: missing required field "RootCause.trend_velocity"`)}
	}
	if _, ok := _c.mutation.PriorityScore(); !ok {
		return &ValidationError{Name: "priority_score", err: errors.New(`ent: missing required field "RootCause.priority_score"`)}
	}
	if _, ok := _c.mutation.FirstSeen(); !ok {
		return &ValidationError{Name: "first_seen", err: errors.New(`ent: missing required field "RootCause.first_seen"`)}
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		return &ValidationError{Name: "last_seen", err: errors.New(`ent: missing required field "RootCause.last_seen"`)}
	}
	if _, ok := _c.mutation.RecurrenceCount(); !ok {
		return &ValidationError{Name: "recurrence_count", err: errors.New(`ent: missing required field "RootCause.recurrence_count"`)}
	}
	return nil
}

func (_c *RootCauseCreate) sqlSave(ctx context.Context) (*RootCause, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RootCause.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RootCauseCreate) createSpec() (*RootCause, *sqlgraph.CreateSpec) {
	var (
		_node = &RootCause{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rootcause.Table, sqlgraph.NewFieldSpec(rootcause.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(rootcause.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(rootcause.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rootcause.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DomainName(); ok {
		_spec.SetField(rootcause.FieldDomainName, field.TypeString, value)
		_node.DomainName = value
	}
	if value, ok := _c.mutation.DomainSubdomain(); ok {
		_spec.SetField(rootcause.FieldDomainSubdomain, field.TypeString, value)
		_node.DomainSubdomain = value
	}
	if value, ok := _c.mutation.DomainTeam(); ok {
		_spec.SetField(rootcause.FieldDomainTeam, field.TypeString, value)
		_node.DomainTeam = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(rootcause.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.SymptomPatterns(); ok {
		_spec.SetField(rootcause.FieldSymptomPatterns, field.TypeJSON, value)
		_node.SymptomPatterns = value
	}
	if value, ok := _c.mutation.ImpactSignalCount(); ok {
		_spec.SetField(rootcause.FieldImpactSignalCount, field.TypeInt, value)
		_node.ImpactSignalCount = value
	}
	if value, ok := _c.mutation.ImpactAffectedCustomers(); ok {
		_spec.SetField(rootcause.FieldImpactAffectedCustomers, field.TypeInt, value)
		_node.ImpactAffectedCustomers = value
	}
	if value, ok := _c.mutation.ImpactAffectedEntities(); ok {
		_spec.SetField(rootcause.FieldImpactAffectedEntities, field.TypeJSON, value)
		_node.ImpactAffectedEntities = value
	}
	if value, ok := _c.mutation.ImpactEscalationRate(); ok {
		_spec.SetField(rootcause.FieldImpactEscalationRate, field.TypeFloat64, value)
		_node.ImpactEscalationRate = value
	}
	if value, ok := _c.mutation.ImpactEstimatedRevenueLoss(); ok {
		_spec.SetField(rootcause.FieldImpactEstimatedRevenueLoss, field.TypeFloat64, value)
		_node.ImpactEstimatedRevenueLoss = value
	}
	if value, ok := _c.mutation.TrendDirection(); ok {
		_spec.SetField(rootcause.FieldTrendDirection, field.TypeString, value)
		_node.TrendDirection = value
	}
	if value, ok := _c.mutation.TrendVelocity(); ok {
		_spec.SetField(rootcause.FieldTrendVelocity, field.TypeFloat64, value)
		_node.TrendVelocity = value
	}
	if value, ok := _c.mutation.TrendPeriodStart(); ok {
		_spec.SetField(rootcause.FieldTrendPeriodStart, field.TypeTime, value)
		_node.TrendPeriodStart = &value
	}
	if value, ok := _c.mutation.TrendPeriodEnd(); ok {
		_spec.SetField(rootcause.FieldTrendPeriodEnd, field.TypeTime, value)
		_node.TrendPeriodEnd = &value
	}
	if value, ok := _c.mutation.PriorityScore(); ok {
		_spec.SetField(rootcause.FieldPriorityScore, field.TypeInt, value)
		_node.PriorityScore = value
	}
	if value, ok := _c.mutation.FirstSeen(); ok {
		_spec.SetField(rootcause.FieldFirstSeen, field.TypeTime, value)
		_node.FirstSeen = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(rootcause.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if value, ok := _c.mutation.OwnerTeam(); ok {
		_spec.SetField(rootcause.FieldOwnerTeam, field.TypeString, value)
		_node.OwnerTeam = value
	}
	if value, ok := _c.mutation.RemediationID(); ok {
		_spec.SetField(rootcause.FieldRemediationID, field.TypeString, value)
		_node.RemediationID = value
	}
	if value, ok := _c.mutation.RecurrenceCount(); ok {
		_spec.SetField(rootcause.FieldRecurrenceCount, field.TypeInt, value)
		_node.RecurrenceCount = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(rootcause.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(rootcause.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RootCause.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RootCauseUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *RootCauseCreate) OnConflict(opts ...sql.ConflictOption) *RootCauseUpsertOne {
	_c.conflict = opts
	return &RootCauseUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RootCause.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RootCauseCreate) OnConflictColumns(columns ...string) *RootCauseUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RootCauseUpsertOne{
		create: _c,
	}
}

type (
	// RootCauseUpsertOne is the builder for "upsert"-ing
	//  one RootCause node.
	RootCauseUpsertOne struct {
		create *RootCauseCreate
	}

	// RootCauseUpsert is the "OnConflict" setter.
	RootCauseUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *RootCauseUpsert) SetTitle(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateTitle() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *RootCauseUpsert) SetDescription(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateDescription() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *RootCauseUpsert) ClearDescription() *RootCauseUpsert {
	u.SetNull(rootcause.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *RootCauseUpsert) SetStatus(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateStatus() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldStatus)
	return u
}

// SetDomainName sets the "domain_name" field.
func (u *RootCauseUpsert) SetDomainName(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldDomainName, v)
	return u
}

// UpdateDomainName sets the "domain_name" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateDomainName() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldDomainName)
	return u
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (u *RootCauseUpsert) SetDomainSubdomain(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldDomainSubdomain, v)
	return u
}

// UpdateDomainSubdomain sets the "domain_subdomain" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateDomainSubdomain() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldDomainSubdomain)
	return u
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (u *RootCauseUpsert) ClearDomainSubdomain() *RootCauseUpsert {
	u.SetNull(rootcause.FieldDomainSubdomain)
	return u
}

// SetDomainTeam sets the "domain_team" field.
func (u *RootCauseUpsert) SetDomainTeam(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldDomainTeam, v)
	return u
}

// UpdateDomainTeam sets the "domain_team" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateDomainTeam() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldDomainTeam)
	return u
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (u *RootCauseUpsert) ClearDomainTeam() *RootCauseUpsert {
	u.SetNull(rootcause.FieldDomainTeam)
	return u
}

// SetSeverity sets the "severity" field.
func (u *RootCauseUpsert) SetSeverity(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateSeverity() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldSeverity)
	return u
}

// SetSymptomPatterns sets the "symptom_patterns" field.
func (u *RootCauseUpsert) SetSymptomPatterns(v []string) *RootCauseUpsert {
	u.Set(rootcause.FieldSymptomPatterns, v)
	return u
}

// UpdateSymptomPatterns sets the "symptom_patterns" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateSymptomPatterns() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldSymptomPatterns)
	return u
}

// ClearSymptomPatterns clears the value of the "symptom_patterns" field.
func (u *RootCauseUpsert) ClearSymptomPatterns() *RootCauseUpsert {
	u.SetNull(rootcause.FieldSymptomPatterns)
	return u
}

// SetImpactSignalCount sets the "impact_signal_count" field.
func (u *RootCauseUpsert) SetImpactSignalCount(v int) *RootCauseUpsert {
	u.Set(rootcause.FieldImpactSignalCount, v)
	return u
}

// UpdateImpactSignalCount sets the "impact_signal_count" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateImpactSignalCount() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldImpactSignalCount)
	return u
}

// AddImpactSignalCount adds v to the "impact_signal_count" field.
func (u *RootCauseUpsert) AddImpactSignalCount(v int) *RootCauseUpsert {
	u.Add(rootcause.FieldImpactSignalCount, v)
	return u
}

// SetImpactAffectedCustomers sets the "impact_affected_customers" field.
func (u *RootCauseUpsert) SetImpactAffectedCustomers(v int) *RootCauseUpsert {
	u.Set(rootcause.FieldImpactAffectedCustomers, v)
	return u
}

// UpdateImpactAffectedCustomers sets the "impact_affected_customers" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateImpactAffectedCustomers() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldImpactAffectedCustomers)
	return u
}

// AddImpactAffectedCustomers adds v to the "impact_affected_customers" field.
func (u *RootCauseUpsert) AddImpactAffectedCustomers(v int) *RootCauseUpsert {
	u.Add(rootcause.FieldImpactAffectedCustomers, v)
	return u
}

// SetImpactAffectedEntities sets the "impact_affected_entities" field.
func (u *RootCauseUpsert) SetImpactAffectedEntities(v []common.Entity) *RootCauseUpsert {
	u.Set(rootcause.FieldImpactAffectedEntities, v)
	return u
}

// UpdateImpactAffectedEntities sets the "impact_affected_entities" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateImpactAffectedEntities() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldImpactAffectedEntities)
	return u
}

// ClearImpactAffectedEntities clears the value of the "impact_affected_entities" field.
func (u *RootCauseUpsert) ClearImpactAffectedEntities() *RootCauseUpsert {
	u.SetNull(rootcause.FieldImpactAffectedEntities)
	return u
}

// SetImpactEscalationRate sets the "impact_escalation_rate" field.
func (u *RootCauseUpsert) SetImpactEscalationRate(v float64) *RootCauseUpsert {
	u.Set(rootcause.FieldImpactEscalationRate, v)
	return u
}

// UpdateImpactEscalationRate sets the "impact_escalation_rate" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateImpactEscalationRate() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldImpactEscalationRate)
	return u
}

// AddImpactEscalationRate adds v to the "impact_escalation_rate" field.
func (u *RootCauseUpsert) AddImpactEscalationRate(v float64) *RootCauseUpsert {
	u.Add(rootcause.FieldImpactEscalationRate, v)
	return u
}

// SetImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field.
func (u *RootCauseUpsert) SetImpactEstimatedRevenueLoss(v float64) *RootCauseUpsert {
	u.Set(rootcause.FieldImpactEstimatedRevenueLoss, v)
	return u
}

// UpdateImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateImpactEstimatedRevenueLoss() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldImpactEstimatedRevenueLoss)
	return u
}

// AddImpactEstimatedRevenueLoss adds v to the "impact_estimated_revenue_loss" field.
func (u *RootCauseUpsert) AddImpactEstimatedRevenueLoss(v float64) *RootCauseUpsert {
	u.Add(rootcause.FieldImpactEstimatedRevenueLoss, v)
	return u
}

// SetTrendDirection sets the "trend_direction" field.
func (u *RootCauseUpsert) SetTrendDirection(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldTrendDirection, v)
	return u
}

// UpdateTrendDirection sets the "trend_direction" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateTrendDirection() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldTrendDirection)
	return u
}

// ClearTrendDirection clears the value of the "trend_direction" field.
func (u *RootCauseUpsert) ClearTrendDirection() *RootCauseUpsert {
	u.SetNull(rootcause.FieldTrendDirection)
	return u
}

// SetTrendVelocity sets the "trend_velocity" field.
func (u *RootCauseUpsert) SetTrendVelocity(v float64) *RootCauseUpsert {
	u.Set(rootcause.FieldTrendVelocity, v)
	return u
}

// UpdateTrendVelocity sets the "trend_velocity" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateTrendVelocity() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldTrendVelocity)
	return u
}

// AddTrendVelocity adds v to the "trend_velocity" field.
func (u *RootCauseUpsert) AddTrendVelocity(v float64) *RootCauseUpsert {
	u.Add(rootcause.FieldTrendVelocity, v)
	return u
}

// SetTrendPeriodStart sets the "trend_period_start" field.
func (u *RootCauseUpsert) SetTrendPeriodStart(v time.Time) *RootCauseUpsert {
	u.Set(rootcause.FieldTrendPeriodStart, v)
	return u
}

// UpdateTrendPeriodStart sets the "trend_period_start" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateTrendPeriodStart() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldTrendPeriodStart)
	return u
}

// ClearTrendPeriodStart clears the value of the "trend_period_start" field.
func (u *RootCauseUpsert) ClearTrendPeriodStart() *RootCauseUpsert {
	u.SetNull(rootcause.FieldTrendPeriodStart)
	return u
}

// SetTrendPeriodEnd sets the "trend_period_end" field.
func (u *RootCauseUpsert) SetTrendPeriodEnd(v time.Time) *RootCauseUpsert {
	u.Set(rootcause.FieldTrendPeriodEnd, v)
	return u
}

// UpdateTrendPeriodEnd sets the "trend_period_end" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateTrendPeriodEnd() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldTrendPeriodEnd)
	return u
}

// ClearTrendPeriodEnd clears the value of the "trend_period_end" field.
func (u *RootCauseUpsert) ClearTrendPeriodEnd() *RootCauseUpsert {
	u.SetNull(rootcause.FieldTrendPeriodEnd)
	return u
}

// SetPriorityScore sets the "priority_score" field.
func (u *RootCauseUpsert) SetPriorityScore(v int) *RootCauseUpsert {
	u.Set(rootcause.FieldPriorityScore, v)
	return u
}

// UpdatePriorityScore sets the "priority_score" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdatePriorityScore() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldPriorityScore)
	return u
}

// AddPriorityScore adds v to the "priority_score" field.
func (u *RootCauseUpsert) AddPriorityScore(v int) *RootCauseUpsert {
	u.Add(rootcause.FieldPriorityScore, v)
	return u
}

// SetFirstSeen sets the "first_seen" field.
func (u *RootCauseUpsert) SetFirstSeen(v time.Time) *RootCauseUpsert {
	u.Set(rootcause.FieldFirstSeen, v)
	return u
}

// UpdateFirstSeen sets the "first_seen" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateFirstSeen() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldFirstSeen)
	return u
}

// SetLastSeen sets the "last_seen" field.
func (u *RootCauseUpsert) SetLastSeen(v time.Time) *RootCauseUpsert {
	u.Set(rootcause.FieldLastSeen, v)
	return u
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateLastSeen() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldLastSeen)
	return u
}

// SetOwnerTeam sets the "owner_team" field.
func (u *RootCauseUpsert) SetOwnerTeam(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldOwnerTeam, v)
	return u
}

// UpdateOwnerTeam sets the "owner_team" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateOwnerTeam() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldOwnerTeam)
	return u
}

// ClearOwnerTeam clears the value of the "owner_team" field.
func (u *RootCauseUpsert) ClearOwnerTeam() *RootCauseUpsert {
	u.SetNull(rootcause.FieldOwnerTeam)
	return u
}

// SetRemediationID sets the "remediation_id" field.
func (u *RootCauseUpsert) SetRemediationID(v string) *RootCauseUpsert {
	u.Set(rootcause.FieldRemediationID, v)
	return u
}

// UpdateRemediationID sets the "remediation_id" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateRemediationID() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldRemediationID)
	return u
}

// ClearRemediationID clears the value of the "remediation_id" field.
func (u *RootCauseUpsert) ClearRemediationID() *RootCauseUpsert {
	u.SetNull(rootcause.FieldRemediationID)
	return u
}

// SetRecurrenceCount sets the "recurrence_count" field.
func (u *RootCauseUpsert) SetRecurrenceCount(v int) *RootCauseUpsert {
	u.Set(rootcause.FieldRecurrenceCount, v)
	return u
}

// UpdateRecurrenceCount sets the "recurrence_count" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateRecurrenceCount() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldRecurrenceCount)
	return u
}

// AddRecurrenceCount adds v to the "recurrence_count" field.
func (u *RootCauseUpsert) AddRecurrenceCount(v int) *RootCauseUpsert {
	u.Add(rootcause.FieldRecurrenceCount, v)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *RootCauseUpsert) SetMetadata(v map[string]interface{}) *RootCauseUpsert {
	u.Set(rootcause.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateMetadata() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RootCauseUpsert) ClearMetadata() *RootCauseUpsert {
	u.SetNull(rootcause.FieldMetadata)
	return u
}

// SetTags sets the "tags" field.
func (u *RootCauseUpsert) SetTags(v []common.Tag) *RootCauseUpsert {
	u.Set(rootcause.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *RootCauseUpsert) UpdateTags() *RootCauseUpsert {
	u.SetExcluded(rootcause.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *RootCauseUpsert) ClearTags() *RootCauseUpsert {
	u.SetNull(rootcause.FieldTags)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RootCause.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rootcause.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RootCauseUpsertOne) UpdateNewValues() *RootCauseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rootcause.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RootCause.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RootCauseUpsertOne) Ignore() *RootCauseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RootCauseUpsertOne) DoNothing() *RootCauseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RootCauseCreate.OnConflict
// documentation for more info.
func (u *RootCauseUpsertOne) Update(set func(*RootCauseUpsert)) *RootCauseUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RootCauseUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *RootCauseUpsertOne) SetTitle(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateTitle() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *RootCauseUpsertOne) SetDescription(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateDescription() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RootCauseUpsertOne) ClearDescription() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *RootCauseUpsertOne) SetStatus(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateStatus() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateStatus()
	})
}

// SetDomainName sets the "domain_name" field.
func (u *RootCauseUpsertOne) SetDomainName(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDomainName(v)
	})
}

// UpdateDomainName sets the "domain_name" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateDomainName() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDomainName()
	})
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (u *RootCauseUpsertOne) SetDomainSubdomain(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDomainSubdomain(v)
	})
}

// UpdateDomainSubdomain sets the "domain_subdomain" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateDomainSubdomain() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDomainSubdomain()
	})
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (u *RootCauseUpsertOne) ClearDomainSubdomain() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearDomainSubdomain()
	})
}

// SetDomainTeam sets the "domain_team" field.
func (u *RootCauseUpsertOne) SetDomainTeam(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDomainTeam(v)
	})
}

// UpdateDomainTeam sets the "domain_team" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateDomainTeam() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDomainTeam()
	})
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (u *RootCauseUpsertOne) ClearDomainTeam() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearDomainTeam()
	})
}

// SetSeverity sets the "severity" field.
func (u *RootCauseUpsertOne) SetSeverity(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateSeverity() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateSeverity()
	})
}

// SetSymptomPatterns sets the "symptom_patterns" field.
func (u *RootCauseUpsertOne) SetSymptomPatterns(v []string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetSymptomPatterns(v)
	})
}

// UpdateSymptomPatterns sets the "symptom_patterns" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateSymptomPatterns() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateSymptomPatterns()
	})
}

// ClearSymptomPatterns clears the value of the "symptom_patterns" field.
func (u *RootCauseUpsertOne) ClearSymptomPatterns() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearSymptomPatterns()
	})
}

// SetImpactSignalCount sets the "impact_signal_count" field.
func (u *RootCauseUpsertOne) SetImpactSignalCount(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactSignalCount(v)
	})
}

// AddImpactSignalCount adds v to the "impact_signal_count" field.
func (u *RootCauseUpsertOne) AddImpactSignalCount(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactSignalCount(v)
	})
}

// UpdateImpactSignalCount sets the "impact_signal_count" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateImpactSignalCount() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactSignalCount()
	})
}

// SetImpactAffectedCustomers sets the "impact_affected_customers" field.
func (u *RootCauseUpsertOne) SetImpactAffectedCustomers(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactAffectedCustomers(v)
	})
}

// AddImpactAffectedCustomers adds v to the "impact_affected_customers" field.
func (u *RootCauseUpsertOne) AddImpactAffectedCustomers(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactAffectedCustomers(v)
	})
}

// UpdateImpactAffectedCustomers sets the "impact_affected_customers" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateImpactAffectedCustomers() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactAffectedCustomers()
	})
}

// SetImpactAffectedEntities sets the "impact_affected_entities" field.
func (u *RootCauseUpsertOne) SetImpactAffectedEntities(v []common.Entity) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactAffectedEntities(v)
	})
}

// UpdateImpactAffectedEntities sets the "impact_affected_entities" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateImpactAffectedEntities() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactAffectedEntities()
	})
}

// ClearImpactAffectedEntities clears the value of the "impact_affected_entities" field.
func (u *RootCauseUpsertOne) ClearImpactAffectedEntities() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearImpactAffectedEntities()
	})
}

// SetImpactEscalationRate sets the "impact_escalation_rate" field.
func (u *RootCauseUpsertOne) SetImpactEscalationRate(v float64) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactEscalationRate(v)
	})
}

// AddImpactEscalationRate adds v to the "impact_escalation_rate" field.
func (u *RootCauseUpsertOne) AddImpactEscalationRate(v float64) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactEscalationRate(v)
	})
}

// UpdateImpactEscalationRate sets the "impact_escalation_rate" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateImpactEscalationRate() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactEscalationRate()
	})
}

// SetImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field.
func (u *RootCauseUpsertOne) SetImpactEstimatedRevenueLoss(v float64) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactEstimatedRevenueLoss(v)
	})
}

// AddImpactEstimatedRevenueLoss adds v to the "impact_estimated_revenue_loss" field.
func (u *RootCauseUpsertOne) AddImpactEstimatedRevenueLoss(v float64) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactEstimatedRevenueLoss(v)
	})
}

// UpdateImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateImpactEstimatedRevenueLoss() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactEstimatedRevenueLoss()
	})
}

// SetTrendDirection sets the "trend_direction" field.
func (u *RootCauseUpsertOne) SetTrendDirection(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendDirection(v)
	})
}

// UpdateTrendDirection sets the "trend_direction" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateTrendDirection() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendDirection()
	})
}

// ClearTrendDirection clears the value of the "trend_direction" field.
func (u *RootCauseUpsertOne) ClearTrendDirection() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTrendDirection()
	})
}

// SetTrendVelocity sets the "trend_velocity" field.
func (u *RootCauseUpsertOne) SetTrendVelocity(v float64) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendVelocity(v)
	})
}

// AddTrendVelocity adds v to the "trend_velocity" field.
func (u *RootCauseUpsertOne) AddTrendVelocity(v float64) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddTrendVelocity(v)
	})
}

// UpdateTrendVelocity sets the "trend_velocity" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateTrendVelocity() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendVelocity()
	})
}

// SetTrendPeriodStart sets the "trend_period_start" field.
func (u *RootCauseUpsertOne) SetTrendPeriodStart(v time.Time) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendPeriodStart(v)
	})
}

// UpdateTrendPeriodStart sets the "trend_period_start" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateTrendPeriodStart() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendPeriodStart()
	})
}

// ClearTrendPeriodStart clears the value of the "trend_period_start" field.
func (u *RootCauseUpsertOne) ClearTrendPeriodStart() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTrendPeriodStart()
	})
}

// SetTrendPeriodEnd sets the "trend_period_end" field.
func (u *RootCauseUpsertOne) SetTrendPeriodEnd(v time.Time) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendPeriodEnd(v)
	})
}

// UpdateTrendPeriodEnd sets the "trend_period_end" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateTrendPeriodEnd() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendPeriodEnd()
	})
}

// ClearTrendPeriodEnd clears the value of the "trend_period_end" field.
func (u *RootCauseUpsertOne) ClearTrendPeriodEnd() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTrendPeriodEnd()
	})
}

// SetPriorityScore sets the "priority_score" field.
func (u *RootCauseUpsertOne) SetPriorityScore(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetPriorityScore(v)
	})
}

// AddPriorityScore adds v to the "priority_score" field.
func (u *RootCauseUpsertOne) AddPriorityScore(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddPriorityScore(v)
	})
}

// UpdatePriorityScore sets the "priority_score" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdatePriorityScore() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdatePriorityScore()
	})
}

// SetFirstSeen sets the "first_seen" field.
func (u *RootCauseUpsertOne) SetFirstSeen(v time.Time) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetFirstSeen(v)
	})
}

// UpdateFirstSeen sets the "first_seen" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateFirstSeen() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateFirstSeen()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *RootCauseUpsertOne) SetLastSeen(v time.Time) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateLastSeen() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateLastSeen()
	})
}

// SetOwnerTeam sets the "owner_team" field.
func (u *RootCauseUpsertOne) SetOwnerTeam(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetOwnerTeam(v)
	})
}

// UpdateOwnerTeam sets the "owner_team" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateOwnerTeam() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateOwnerTeam()
	})
}

// ClearOwnerTeam clears the value of the "owner_team" field.
func (u *RootCauseUpsertOne) ClearOwnerTeam() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearOwnerTeam()
	})
}

// SetRemediationID sets the "remediation_id" field.
func (u *RootCauseUpsertOne) SetRemediationID(v string) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetRemediationID(v)
	})
}

// UpdateRemediationID sets the "remediation_id" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateRemediationID() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateRemediationID()
	})
}

// ClearRemediationID clears the value of the "remediation_id" field.
func (u *RootCauseUpsertOne) ClearRemediationID() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearRemediationID()
	})
}

// SetRecurrenceCount sets the "recurrence_count" field.
func (u *RootCauseUpsertOne) SetRecurrenceCount(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetRecurrenceCount(v)
	})
}

// AddRecurrenceCount adds v to the "recurrence_count" field.
func (u *RootCauseUpsertOne) AddRecurrenceCount(v int) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddRecurrenceCount(v)
	})
}

// UpdateRecurrenceCount sets the "recurrence_count" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateRecurrenceCount() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateRecurrenceCount()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RootCauseUpsertOne) SetMetadata(v map[string]interface{}) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateMetadata() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RootCauseUpsertOne) ClearMetadata() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearMetadata()
	})
}

// SetTags sets the "tags" field.
func (u *RootCauseUpsertOne) SetTags(v []common.Tag) *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *RootCauseUpsertOne) UpdateTags() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *RootCauseUpsertOne) ClearTags() *RootCauseUpsertOne {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTags()
	})
}

// Exec executes the query.
func (u *RootCauseUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RootCauseCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RootCauseUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RootCauseUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RootCauseUpsertOne.ID is not supported by MySQL driver. Use RootCauseUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RootCauseUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RootCauseCreateBulk is the builder for creating many RootCause entities in bulk.
type RootCauseCreateBulk struct {
	config
	err      error
	builders []*RootCauseCreate
	conflict []sql.ConflictOption
}

// Save creates the RootCause entities in the database.
func (_c *RootCauseCreateBulk) Save(ctx context.Context) ([]*RootCause, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RootCause, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RootCauseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RootCauseCreateBulk) SaveX(ctx context.Context) []*RootCause {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RootCauseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RootCauseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RootCause.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RootCauseUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *RootCauseCreateBulk) OnConflict(opts ...sql.ConflictOption) *RootCauseUpsertBulk {
	_c.conflict = opts
	return &RootCauseUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RootCause.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RootCauseCreateBulk) OnConflictColumns(columns ...string) *RootCauseUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RootCauseUpsertBulk{
		create: _c,
	}
}

// RootCauseUpsertBulk is the builder for "upsert"-ing
// a bulk of RootCause nodes.
type RootCauseUpsertBulk struct {
	create *RootCauseCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RootCause.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rootcause.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RootCauseUpsertBulk) UpdateNewValues() *RootCauseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rootcause.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RootCause.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RootCauseUpsertBulk) Ignore() *RootCauseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RootCauseUpsertBulk) DoNothing() *RootCauseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RootCauseCreateBulk.OnConflict
// documentation for more info.
func (u *RootCauseUpsertBulk) Update(set func(*RootCauseUpsert)) *RootCauseUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RootCauseUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *RootCauseUpsertBulk) SetTitle(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateTitle() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *RootCauseUpsertBulk) SetDescription(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateDescription() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *RootCauseUpsertBulk) ClearDescription() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *RootCauseUpsertBulk) SetStatus(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateStatus() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateStatus()
	})
}

// SetDomainName sets the "domain_name" field.
func (u *RootCauseUpsertBulk) SetDomainName(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDomainName(v)
	})
}

// UpdateDomainName sets the "domain_name" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateDomainName() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDomainName()
	})
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (u *RootCauseUpsertBulk) SetDomainSubdomain(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDomainSubdomain(v)
	})
}

// UpdateDomainSubdomain sets the "domain_subdomain" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateDomainSubdomain() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDomainSubdomain()
	})
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (u *RootCauseUpsertBulk) ClearDomainSubdomain() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearDomainSubdomain()
	})
}

// SetDomainTeam sets the "domain_team" field.
func (u *RootCauseUpsertBulk) SetDomainTeam(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetDomainTeam(v)
	})
}

// UpdateDomainTeam sets the "domain_team" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateDomainTeam() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateDomainTeam()
	})
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (u *RootCauseUpsertBulk) ClearDomainTeam() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearDomainTeam()
	})
}

// SetSeverity sets the "severity" field.
func (u *RootCauseUpsertBulk) SetSeverity(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateSeverity() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateSeverity()
	})
}

// SetSymptomPatterns sets the "symptom_patterns" field.
func (u *RootCauseUpsertBulk) SetSymptomPatterns(v []string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetSymptomPatterns(v)
	})
}

// UpdateSymptomPatterns sets the "symptom_patterns" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateSymptomPatterns() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateSymptomPatterns()
	})
}

// ClearSymptomPatterns clears the value of the "symptom_patterns" field.
func (u *RootCauseUpsertBulk) ClearSymptomPatterns() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearSymptomPatterns()
	})
}

// SetImpactSignalCount sets the "impact_signal_count" field.
func (u *RootCauseUpsertBulk) SetImpactSignalCount(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactSignalCount(v)
	})
}

// AddImpactSignalCount adds v to the "impact_signal_count" field.
func (u *RootCauseUpsertBulk) AddImpactSignalCount(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactSignalCount(v)
	})
}

// UpdateImpactSignalCount sets the "impact_signal_count" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateImpactSignalCount() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactSignalCount()
	})
}

// SetImpactAffectedCustomers sets the "impact_affected_customers" field.
func (u *RootCauseUpsertBulk) SetImpactAffectedCustomers(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactAffectedCustomers(v)
	})
}

// AddImpactAffectedCustomers adds v to the "impact_affected_customers" field.
func (u *RootCauseUpsertBulk) AddImpactAffectedCustomers(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactAffectedCustomers(v)
	})
}

// UpdateImpactAffectedCustomers sets the "impact_affected_customers" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateImpactAffectedCustomers() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactAffectedCustomers()
	})
}

// SetImpactAffectedEntities sets the "impact_affected_entities" field.
func (u *RootCauseUpsertBulk) SetImpactAffectedEntities(v []common.Entity) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactAffectedEntities(v)
	})
}

// UpdateImpactAffectedEntities sets the "impact_affected_entities" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateImpactAffectedEntities() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactAffectedEntities()
	})
}

// ClearImpactAffectedEntities clears the value of the "impact_affected_entities" field.
func (u *RootCauseUpsertBulk) ClearImpactAffectedEntities() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearImpactAffectedEntities()
	})
}

// SetImpactEscalationRate sets the "impact_escalation_rate" field.
func (u *RootCauseUpsertBulk) SetImpactEscalationRate(v float64) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactEscalationRate(v)
	})
}

// AddImpactEscalationRate adds v to the "impact_escalation_rate" field.
func (u *RootCauseUpsertBulk) AddImpactEscalationRate(v float64) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactEscalationRate(v)
	})
}

// UpdateImpactEscalationRate sets the "impact_escalation_rate" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateImpactEscalationRate() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactEscalationRate()
	})
}

// SetImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field.
func (u *RootCauseUpsertBulk) SetImpactEstimatedRevenueLoss(v float64) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetImpactEstimatedRevenueLoss(v)
	})
}

// AddImpactEstimatedRevenueLoss adds v to the "impact_estimated_revenue_loss" field.
func (u *RootCauseUpsertBulk) AddImpactEstimatedRevenueLoss(v float64) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddImpactEstimatedRevenueLoss(v)
	})
}

// UpdateImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateImpactEstimatedRevenueLoss() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateImpactEstimatedRevenueLoss()
	})
}

// SetTrendDirection sets the "trend_direction" field.
func (u *RootCauseUpsertBulk) SetTrendDirection(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendDirection(v)
	})
}

// UpdateTrendDirection sets the "trend_direction" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateTrendDirection() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendDirection()
	})
}

// ClearTrendDirection clears the value of the "trend_direction" field.
func (u *RootCauseUpsertBulk) ClearTrendDirection() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTrendDirection()
	})
}

// SetTrendVelocity sets the "trend_velocity" field.
func (u *RootCauseUpsertBulk) SetTrendVelocity(v float64) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendVelocity(v)
	})
}

// AddTrendVelocity adds v to the "trend_velocity" field.
func (u *RootCauseUpsertBulk) AddTrendVelocity(v float64) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddTrendVelocity(v)
	})
}

// UpdateTrendVelocity sets the "trend_velocity" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateTrendVelocity() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendVelocity()
	})
}

// SetTrendPeriodStart sets the "trend_period_start" field.
func (u *RootCauseUpsertBulk) SetTrendPeriodStart(v time.Time) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendPeriodStart(v)
	})
}

// UpdateTrendPeriodStart sets the "trend_period_start" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateTrendPeriodStart() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendPeriodStart()
	})
}

// ClearTrendPeriodStart clears the value of the "trend_period_start" field.
func (u *RootCauseUpsertBulk) ClearTrendPeriodStart() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTrendPeriodStart()
	})
}

// SetTrendPeriodEnd sets the "trend_period_end" field.
func (u *RootCauseUpsertBulk) SetTrendPeriodEnd(v time.Time) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTrendPeriodEnd(v)
	})
}

// UpdateTrendPeriodEnd sets the "trend_period_end" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateTrendPeriodEnd() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTrendPeriodEnd()
	})
}

// ClearTrendPeriodEnd clears the value of the "trend_period_end" field.
func (u *RootCauseUpsertBulk) ClearTrendPeriodEnd() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTrendPeriodEnd()
	})
}

// SetPriorityScore sets the "priority_score" field.
func (u *RootCauseUpsertBulk) SetPriorityScore(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetPriorityScore(v)
	})
}

// AddPriorityScore adds v to the "priority_score" field.
func (u *RootCauseUpsertBulk) AddPriorityScore(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddPriorityScore(v)
	})
}

// UpdatePriorityScore sets the "priority_score" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdatePriorityScore() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdatePriorityScore()
	})
}

// SetFirstSeen sets the "first_seen" field.
func (u *RootCauseUpsertBulk) SetFirstSeen(v time.Time) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetFirstSeen(v)
	})
}

// UpdateFirstSeen sets the "first_seen" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateFirstSeen() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateFirstSeen()
	})
}

// SetLastSeen sets the "last_seen" field.
func (u *RootCauseUpsertBulk) SetLastSeen(v time.Time) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetLastSeen(v)
	})
}

// UpdateLastSeen sets the "last_seen" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateLastSeen() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateLastSeen()
	})
}

// SetOwnerTeam sets the "owner_team" field.
func (u *RootCauseUpsertBulk) SetOwnerTeam(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetOwnerTeam(v)
	})
}

// UpdateOwnerTeam sets the "owner_team" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateOwnerTeam() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateOwnerTeam()
	})
}

// ClearOwnerTeam clears the value of the "owner_team" field.
func (u *RootCauseUpsertBulk) ClearOwnerTeam() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearOwnerTeam()
	})
}

// SetRemediationID sets the "remediation_id" field.
func (u *RootCauseUpsertBulk) SetRemediationID(v string) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetRemediationID(v)
	})
}

// UpdateRemediationID sets the "remediation_id" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateRemediationID() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateRemediationID()
	})
}

// ClearRemediationID clears the value of the "remediation_id" field.
func (u *RootCauseUpsertBulk) ClearRemediationID() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearRemediationID()
	})
}

// SetRecurrenceCount sets the "recurrence_count" field.
func (u *RootCauseUpsertBulk) SetRecurrenceCount(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetRecurrenceCount(v)
	})
}

// AddRecurrenceCount adds v to the "recurrence_count" field.
func (u *RootCauseUpsertBulk) AddRecurrenceCount(v int) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.AddRecurrenceCount(v)
	})
}

// UpdateRecurrenceCount sets the "recurrence_count" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateRecurrenceCount() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateRecurrenceCount()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RootCauseUpsertBulk) SetMetadata(v map[string]interface{}) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateMetadata() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *RootCauseUpsertBulk) ClearMetadata() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearMetadata()
	})
}

// SetTags sets the "tags" field.
func (u *RootCauseUpsertBulk) SetTags(v []common.Tag) *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *RootCauseUpsertBulk) UpdateTags() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *RootCauseUpsertBulk) ClearTags() *RootCauseUpsertBulk {
	return u.Update(func(s *RootCauseUpsert) {
		s.ClearTags()
	})
}

// Exec executes the query.
func (u *RootCauseUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RootCauseCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RootCauseCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RootCauseUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
