// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnisignal/store/sqlite/ent/rootcause"
	"github.com/plexusone/signal-spec/pkg/common"
)

// RootCause is the model entity for the RootCause schema.
type RootCause struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// DomainName holds the value of the "domain_name" field.
	DomainName string `json:"domain_name,omitempty"`
	// DomainSubdomain holds the value of the "domain_subdomain" field.
	DomainSubdomain string `json:"domain_subdomain,omitempty"`
	// DomainTeam holds the value of the "domain_team" field.
	DomainTeam string `json:"domain_team,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity string `json:"severity,omitempty"`
	// SymptomPatterns holds the value of the "symptom_patterns" field.
	SymptomPatterns []string `json:"symptom_patterns,omitempty"`
	// ImpactSignalCount holds the value of the "impact_signal_count" field.
	ImpactSignalCount int `json:"impact_signal_count,omitempty"`
	// ImpactAffectedCustomers holds the value of the "impact_affected_customers" field.
	ImpactAffectedCustomers int `json:"impact_affected_customers,omitempty"`
	// ImpactAffectedEntities holds the value of the "impact_affected_entities" field.
	ImpactAffectedEntities []common.Entity `json:"impact_affected_entities,omitempty"`
	// ImpactEscalationRate holds the value of the "impact_escalation_rate" field.
	ImpactEscalationRate float64 `json:"impact_escalation_rate,omitempty"`
	// ImpactEstimatedRevenueLoss holds the value of the "impact_estimated_revenue_loss" field.
	ImpactEstimatedRevenueLoss float64 `json:"impact_estimated_revenue_loss,omitempty"`
	// TrendDirection holds the value of the "trend_direction" field.
	TrendDirection string `json:"trend_direction,omitempty"`
	// TrendVelocity holds the value of the "trend_velocity" field.
	TrendVelocity float64 `json:"trend_velocity,omitempty"`
	// TrendPeriodStart holds the value of the "trend_period_start" field.
	TrendPeriodStart *time.Time `json:"trend_period_start,omitempty"`
	// TrendPeriodEnd holds the value of the "trend_period_end" field.
	TrendPeriodEnd *time.Time `json:"trend_period_end,omitempty"`
	// PriorityScore holds the value of the "priority_score" field.
	PriorityScore int `json:"priority_score,omitempty"`
	// FirstSeen holds the value of the "first_seen" field.
	FirstSeen time.Time `json:"first_seen,omitempty"`
	// LastSeen holds the value of the "last_seen" field.
	LastSeen time.Time `json:"last_seen,omitempty"`
	// OwnerTeam holds the value of the "owner_team" field.
	OwnerTeam string `json:"owner_team,omitempty"`
	// RemediationID holds the value of the "remediation_id" field.
	RemediationID string `json:"remediation_id,omitempty"`
	// RecurrenceCount holds the value of the "recurrence_count" field.
	RecurrenceCount int `json:"recurrence_count,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags         []common.Tag `json:"tags,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RootCause) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rootcause.FieldSymptomPatterns, rootcause.FieldImpactAffectedEntities, rootcause.FieldMetadata, rootcause.FieldTags:
			values[i] = new([]byte)
		case rootcause.FieldImpactEscalationRate, rootcause.FieldImpactEstimatedRevenueLoss, rootcause.FieldTrendVelocity:
			values[i] = new(sql.NullFloat64)
		case rootcause.FieldImpactSignalCount, rootcause.FieldImpactAffectedCustomers, rootcause.FieldPriorityScore, rootcause.FieldRecurrenceCount:
			values[i] = new(sql.NullInt64)
		case rootcause.FieldID, rootcause.FieldTitle, rootcause.FieldDescription, rootcause.FieldStatus, rootcause.FieldDomainName, rootcause.FieldDomainSubdomain, rootcause.FieldDomainTeam, rootcause.FieldSeverity, rootcause.FieldTrendDirection, rootcause.FieldOwnerTeam, rootcause.FieldRemediationID:
			values[i] = new(sql.NullString)
		case rootcause.FieldTrendPeriodStart, rootcause.FieldTrendPeriodEnd, rootcause.FieldFirstSeen, rootcause.FieldLastSeen:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RootCause fields.
func (_m *RootCause) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rootcause.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case rootcause.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case rootcause.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case rootcause.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case rootcause.FieldDomainName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_name", values[i])
			} else if value.Valid {
				_m.DomainName = value.String
			}
		case rootcause.FieldDomainSubdomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_subdomain", values[i])
			} else if value.Valid {
				_m.DomainSubdomain = value.String
			}
		case rootcause.FieldDomainTeam:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_team", values[i])
			} else if value.Valid {
				_m.DomainTeam = value.String
			}
		case rootcause.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case rootcause.FieldSymptomPatterns:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field symptom_patterns", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SymptomPatterns); err != nil {
					return fmt.Errorf("unmarshal field symptom_patterns: %w", err)
				}
			}
		case rootcause.FieldImpactSignalCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field impact_signal_count", values[i])
			} else if value.Valid {
				_m.ImpactSignalCount = int(value.Int64)
			}
		case rootcause.FieldImpactAffectedCustomers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field impact_affected_customers", values[i])
			} else if value.Valid {
				_m.ImpactAffectedCustomers = int(value.Int64)
			}
		case rootcause.FieldImpactAffectedEntities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field impact_affected_entities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ImpactAffectedEntities); err != nil {
					return fmt.Errorf("unmarshal field impact_affected_entities: %w", err)
				}
			}
		case rootcause.FieldImpactEscalationRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field impact_escalation_rate", values[i])
			} else if value.Valid {
				_m.ImpactEscalationRate = value.Float64
			}
		case rootcause.FieldImpactEstimatedRevenueLoss:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field impact_estimated_revenue_loss", values[i])
			} else if value.Valid {
				_m.ImpactEstimatedRevenueLoss = value.Float64
			}
		case rootcause.FieldTrendDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trend_direction", values[i])
			} else if value.Valid {
				_m.TrendDirection = value.String
			}
		case rootcause.FieldTrendVelocity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trend_velocity", values[i])
			} else if value.Valid {
				_m.TrendVelocity = value.Float64
			}
		case rootcause.FieldTrendPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field trend_period_start", values[i])
			} else if value.Valid {
				_m.TrendPeriodStart = new(time.Time)
				*_m.TrendPeriodStart = value.Time
			}
		case rootcause.FieldTrendPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field trend_period_end", values[i])
			} else if value.Valid {
				_m.TrendPeriodEnd = new(time.Time)
				*_m.TrendPeriodEnd = value.Time
			}
		case rootcause.FieldPriorityScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority_score", values[i])
			} else if value.Valid {
				_m.PriorityScore = int(value.Int64)
			}
		case rootcause.FieldFirstSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen", values[i])
			} else if value.Valid {
				_m.FirstSeen = value.Time
			}
		case rootcause.FieldLastSeen:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen", values[i])
			} else if value.Valid {
				_m.LastSeen = value.Time
			}
		case rootcause.FieldOwnerTeam:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_team", values[i])
			} else if value.Valid {
				_m.OwnerTeam = value.String
			}
		case rootcause.FieldRemediationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remediation_id", values[i])
			} else if value.Valid {
				_m.RemediationID = value.String
			}
		case rootcause.FieldRecurrenceCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recurrence_count", values[i])
			} else if value.Valid {
				_m.RecurrenceCount = int(value.Int64)
			}
		case rootcause.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case rootcause.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RootCause.
// This includes values selected through modifiers, order, etc.
func (_m *RootCause) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RootCause.
// Note that you need to call RootCause.Unwrap() before calling this method if this RootCause
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RootCause) Update() *RootCauseUpdateOne {
	return NewRootCauseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RootCause entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RootCause) Unwrap() *RootCause {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RootCause is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RootCause) String() string {
	var builder strings.Builder
	builder.WriteString("RootCause(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("domain_name=")
	builder.WriteString(_m.DomainName)
	builder.WriteString(", ")
	builder.WriteString("domain_subdomain=")
	builder.WriteString(_m.DomainSubdomain)
	builder.WriteString(", ")
	builder.WriteString("domain_team=")
	builder.WriteString(_m.DomainTeam)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("symptom_patterns=")
	builder.WriteString(fmt.Sprintf("%v", _m.SymptomPatterns))
	builder.WriteString(", ")
	builder.WriteString("impact_signal_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImpactSignalCount))
	builder.WriteString(", ")
	builder.WriteString("impact_affected_customers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImpactAffectedCustomers))
	builder.WriteString(", ")
	builder.WriteString("impact_affected_entities=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImpactAffectedEntities))
	builder.WriteString(", ")
	builder.WriteString("impact_escalation_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImpactEscalationRate))
	builder.WriteString(", ")
	builder.WriteString("impact_estimated_revenue_loss=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImpactEstimatedRevenueLoss))
	builder.WriteString(", ")
	builder.WriteString("trend_direction=")
	builder.WriteString(_m.TrendDirection)
	builder.WriteString(", ")
	builder.WriteString("trend_velocity=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrendVelocity))
	builder.WriteString(", ")
	if v := _m.TrendPeriodStart; v != nil {
		builder.WriteString("trend_period_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TrendPeriodEnd; v != nil {
		builder.WriteString("trend_period_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("priority_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriorityScore))
	builder.WriteString(", ")
	builder.WriteString("first_seen=")
	builder.WriteString(_m.FirstSeen.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_seen=")
	builder.WriteString(_m.LastSeen.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_team=")
	builder.WriteString(_m.OwnerTeam)
	builder.WriteString(", ")
	builder.WriteString("remediation_id=")
	builder.WriteString(_m.RemediationID)
	builder.WriteString(", ")
	builder.WriteString("recurrence_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecurrenceCount))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteByte(')')
	return builder.String()
}

// RootCauses is a parsable slice of RootCause.
type RootCauses []*RootCause
