// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnisignal/store/sqlite/ent/predicate"
	"github.com/plexusone/omnisignal/store/sqlite/ent/rootcause"
	"github.com/plexusone/signal-spec/pkg/common"
)

// RootCauseUpdate is the builder for updating RootCause entities.
type RootCauseUpdate struct {
	config
	hooks    []Hook
	mutation *RootCauseMutation
}

// Where appends a list predicates to the RootCauseUpdate builder.
func (_u *RootCauseUpdate) Where(ps ...predicate.RootCause) *RootCauseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *RootCauseUpdate) SetTitle(v string) *RootCauseUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableTitle(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RootCauseUpdate) SetDescription(v string) *RootCauseUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableDescription(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RootCauseUpdate) ClearDescription() *RootCauseUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RootCauseUpdate) SetStatus(v string) *RootCauseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableStatus(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDomainName sets the "domain_name" field.
func (_u *RootCauseUpdate) SetDomainName(v string) *RootCauseUpdate {
	_u.mutation.SetDomainName(v)
	return _u
}

// SetNillableDomainName sets the "domain_name" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableDomainName(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetDomainName(*v)
	}
	return _u
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (_u *RootCauseUpdate) SetDomainSubdomain(v string) *RootCauseUpdate {
	_u.mutation.SetDomainSubdomain(v)
	return _u
}

// SetNillableDomainSubdomain sets the "domain_subdomain" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableDomainSubdomain(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetDomainSubdomain(*v)
	}
	return _u
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (_u *RootCauseUpdate) ClearDomainSubdomain() *RootCauseUpdate {
	_u.mutation.ClearDomainSubdomain()
	return _u
}

// SetDomainTeam sets the "domain_team" field.
func (_u *RootCauseUpdate) SetDomainTeam(v string) *RootCauseUpdate {
	_u.mutation.SetDomainTeam(v)
	return _u
}

// SetNillableDomainTeam sets the "domain_team" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableDomainTeam(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetDomainTeam(*v)
	}
	return _u
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (_u *RootCauseUpdate) ClearDomainTeam() *RootCauseUpdate {
	_u.mutation.ClearDomainTeam()
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *RootCauseUpdate) SetSeverity(v string) *RootCauseUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableSeverity(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetSymptomPatterns sets the "symptom_patterns" field.
func (_u *RootCauseUpdate) SetSymptomPatterns(v []string) *RootCauseUpdate {
	_u.mutation.SetSymptomPatterns(v)
	return _u
}

// AppendSymptomPatterns appends value to the "symptom_patterns" field.
func (_u *RootCauseUpdate) AppendSymptomPatterns(v []string) *RootCauseUpdate {
	_u.mutation.AppendSymptomPatterns(v)
	return _u
}

// ClearSymptomPatterns clears the value of the "symptom_patterns" field.
func (_u *RootCauseUpdate) ClearSymptomPatterns() *RootCauseUpdate {
	_u.mutation.ClearSymptomPatterns()
	return _u
}

// SetImpactSignalCount sets the "impact_signal_count" field.
func (_u *RootCauseUpdate) SetImpactSignalCount(v int) *RootCauseUpdate {
	_u.mutation.ResetImpactSignalCount()
	_u.mutation.SetImpactSignalCount(v)
	return _u
}

// SetNillableImpactSignalCount sets the "impact_signal_count" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableImpactSignalCount(v *int) *RootCauseUpdate {
	if v != nil {
		_u.SetImpactSignalCount(*v)
	}
	return _u
}

// AddImpactSignalCount adds value to the "impact_signal_count" field.
func (_u *RootCauseUpdate) AddImpactSignalCount(v int) *RootCauseUpdate {
	_u.mutation.AddImpactSignalCount(v)
	return _u
}

// SetImpactAffectedCustomers sets the "impact_affected_customers" field.
func (_u *RootCauseUpdate) SetImpactAffectedCustomers(v int) *RootCauseUpdate {
	_u.mutation.ResetImpactAffectedCustomers()
	_u.mutation.SetImpactAffectedCustomers(v)
	return _u
}

// SetNillableImpactAffectedCustomers sets the "impact_affected_customers" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableImpactAffectedCustomers(v *int) *RootCauseUpdate {
	if v != nil {
		_u.SetImpactAffectedCustomers(*v)
	}
	return _u
}

// AddImpactAffectedCustomers adds value to the "impact_affected_customers" field.
func (_u *RootCauseUpdate) AddImpactAffectedCustomers(v int) *RootCauseUpdate {
	_u.mutation.AddImpactAffectedCustomers(v)
	return _u
}

// SetImpactAffectedEntities sets the "impact_affected_entities" field.
func (_u *RootCauseUpdate) SetImpactAffectedEntities(v []common.Entity) *RootCauseUpdate {
	_u.mutation.SetImpactAffectedEntities(v)
	return _u
}

// AppendImpactAffectedEntities appends value to the "impact_affected_entities" field.
func (_u *RootCauseUpdate) AppendImpactAffectedEntities(v []common.Entity) *RootCauseUpdate {
	_u.mutation.AppendImpactAffectedEntities(v)
	return _u
}

// ClearImpactAffectedEntities clears the value of the "impact_affected_entities" field.
func (_u *RootCauseUpdate) ClearImpactAffectedEntities() *RootCauseUpdate {
	_u.mutation.ClearImpactAffectedEntities()
	return _u
}

// SetImpactEscalationRate sets the "impact_escalation_rate" field.
func (_u *RootCauseUpdate) SetImpactEscalationRate(v float64) *RootCauseUpdate {
	_u.mutation.ResetImpactEscalationRate()
	_u.mutation.SetImpactEscalationRate(v)
	return _u
}

// SetNillableImpactEscalationRate sets the "impact_escalation_rate" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableImpactEscalationRate(v *float64) *RootCauseUpdate {
	if v != nil {
		_u.SetImpactEscalationRate(*v)
	}
	return _u
}

// AddImpactEscalationRate adds value to the "impact_escalation_rate" field.
func (_u *RootCauseUpdate) AddImpactEscalationRate(v float64) *RootCauseUpdate {
	_u.mutation.AddImpactEscalationRate(v)
	return _u
}

// SetImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field.
func (_u *RootCauseUpdate) SetImpactEstimatedRevenueLoss(v float64) *RootCauseUpdate {
	_u.mutation.ResetImpactEstimatedRevenueLoss()
	_u.mutation.SetImpactEstimatedRevenueLoss(v)
	return _u
}

// SetNillableImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableImpactEstimatedRevenueLoss(v *float64) *RootCauseUpdate {
	if v != nil {
		_u.SetImpactEstimatedRevenueLoss(*v)
	}
	return _u
}

// AddImpactEstimatedRevenueLoss adds value to the "impact_estimated_revenue_loss" field.
func (_u *RootCauseUpdate) AddImpactEstimatedRevenueLoss(v float64) *RootCauseUpdate {
	_u.mutation.AddImpactEstimatedRevenueLoss(v)
	return _u
}

// SetTrendDirection sets the "trend_direction" field.
func (_u *RootCauseUpdate) SetTrendDirection(v string) *RootCauseUpdate {
	_u.mutation.SetTrendDirection(v)
	return _u
}

// SetNillableTrendDirection sets the "trend_direction" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableTrendDirection(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetTrendDirection(*v)
	}
	return _u
}

// ClearTrendDirection clears the value of the "trend_direction" field.
func (_u *RootCauseUpdate) ClearTrendDirection() *RootCauseUpdate {
	_u.mutation.ClearTrendDirection()
	return _u
}

// SetTrendVelocity sets the "trend_velocity" field.
func (_u *RootCauseUpdate) SetTrendVelocity(v float64) *RootCauseUpdate {
	_u.mutation.ResetTrendVelocity()
	_u.mutation.SetTrendVelocity(v)
	return _u
}

// SetNillableTrendVelocity sets the "trend_velocity" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableTrendVelocity(v *float64) *RootCauseUpdate {
	if v != nil {
		_u.SetTrendVelocity(*v)
	}
	return _u
}

// AddTrendVelocity adds value to the "trend_velocity" field.
func (_u *RootCauseUpdate) AddTrendVelocity(v float64) *RootCauseUpdate {
	_u.mutation.AddTrendVelocity(v)
	return _u
}

// SetTrendPeriodStart sets the "trend_period_start" field.
func (_u *RootCauseUpdate) SetTrendPeriodStart(v time.Time) *RootCauseUpdate {
	_u.mutation.SetTrendPeriodStart(v)
	return _u
}

// SetNillableTrendPeriodStart sets the "trend_period_start" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableTrendPeriodStart(v *time.Time) *RootCauseUpdate {
	if v != nil {
		_u.SetTrendPeriodStart(*v)
	}
	return _u
}

// ClearTrendPeriodStart clears the value of the "trend_period_start" field.
func (_u *RootCauseUpdate) ClearTrendPeriodStart() *RootCauseUpdate {
	_u.mutation.ClearTrendPeriodStart()
	return _u
}

// SetTrendPeriodEnd sets the "trend_period_end" field.
func (_u *RootCauseUpdate) SetTrendPeriodEnd(v time.Time) *RootCauseUpdate {
	_u.mutation.SetTrendPeriodEnd(v)
	return _u
}

// SetNillableTrendPeriodEnd sets the "trend_period_end" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableTrendPeriodEnd(v *time.Time) *RootCauseUpdate {
	if v != nil {
		_u.SetTrendPeriodEnd(*v)
	}
	return _u
}

// ClearTrendPeriodEnd clears the value of the "trend_period_end" field.
func (_u *RootCauseUpdate) ClearTrendPeriodEnd() *RootCauseUpdate {
	_u.mutation.ClearTrendPeriodEnd()
	return _u
}

// SetPriorityScore sets the "priority_score" field.
func (_u *RootCauseUpdate) SetPriorityScore(v int) *RootCauseUpdate {
	_u.mutation.ResetPriorityScore()
	_u.mutation.SetPriorityScore(v)
	return _u
}

// SetNillablePriorityScore sets the "priority_score" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillablePriorityScore(v *int) *RootCauseUpdate {
	if v != nil {
		_u.SetPriorityScore(*v)
	}
	return _u
}

// AddPriorityScore adds value to the "priority_score" field.
func (_u *RootCauseUpdate) AddPriorityScore(v int) *RootCauseUpdate {
	_u.mutation.AddPriorityScore(v)
	return _u
}

// SetFirstSeen sets the "first_seen" field.
func (_u *RootCauseUpdate) SetFirstSeen(v time.Time) *RootCauseUpdate {
	_u.mutation.SetFirstSeen(v)
	return _u
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableFirstSeen(v *time.Time) *RootCauseUpdate {
	if v != nil {
		_u.SetFirstSeen(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *RootCauseUpdate) SetLastSeen(v time.Time) *RootCauseUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableLastSeen(v *time.Time) *RootCauseUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetOwnerTeam sets the "owner_team" field.
func (_u *RootCauseUpdate) SetOwnerTeam(v string) *RootCauseUpdate {
	_u.mutation.SetOwnerTeam(v)
	return _u
}

// SetNillableOwnerTeam sets the "owner_team" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableOwnerTeam(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetOwnerTeam(*v)
	}
	return _u
}

// ClearOwnerTeam clears the value of the "owner_team" field.
func (_u *RootCauseUpdate) ClearOwnerTeam() *RootCauseUpdate {
	_u.mutation.ClearOwnerTeam()
	return _u
}

// SetRemediationID sets the "remediation_id" field.
func (_u *RootCauseUpdate) SetRemediationID(v string) *RootCauseUpdate {
	_u.mutation.SetRemediationID(v)
	return _u
}

// SetNillableRemediationID sets the "remediation_id" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableRemediationID(v *string) *RootCauseUpdate {
	if v != nil {
		_u.SetRemediationID(*v)
	}
	return _u
}

// ClearRemediationID clears the value of the "remediation_id" field.
func (_u *RootCauseUpdate) ClearRemediationID() *RootCauseUpdate {
	_u.mutation.ClearRemediationID()
	return _u
}

// SetRecurrenceCount sets the "recurrence_count" field.
func (_u *RootCauseUpdate) SetRecurrenceCount(v int) *RootCauseUpdate {
	_u.mutation.ResetRecurrenceCount()
	_u.mutation.SetRecurrenceCount(v)
	return _u
}

// SetNillableRecurrenceCount sets the "recurrence_count" field if the given value is not nil.
func (_u *RootCauseUpdate) SetNillableRecurrenceCount(v *int) *RootCauseUpdate {
	if v != nil {
		_u.SetRecurrenceCount(*v)
	}
	return _u
}

// AddRecurrenceCount adds value to the "recurrence_count" field.
func (_u *RootCauseUpdate) AddRecurrenceCount(v int) *RootCauseUpdate {
	_u.mutation.AddRecurrenceCount(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RootCauseUpdate) SetMetadata(v map[string]interface{}) *RootCauseUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RootCauseUpdate) ClearMetadata() *RootCauseUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetTags sets the "tags" field.
func (_u *RootCauseUpdate) SetTags(v []common.Tag) *RootCauseUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *RootCauseUpdate) AppendTags(v []common.Tag) *RootCauseUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *RootCauseUpdate) ClearTags() *RootCauseUpdate {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the RootCauseMutation object of the builder.
func (_u *RootCauseUpdate) Mutation() *RootCauseMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RootCauseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RootCauseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RootCauseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RootCauseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RootCauseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(rootcause.Table, rootcause.Columns, sqlgraph.NewFieldSpec(rootcause.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(rootcause.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rootcause.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rootcause.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rootcause.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DomainName(); ok {
		_spec.SetField(rootcause.FieldDomainName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DomainSubdomain(); ok {
		_spec.SetField(rootcause.FieldDomainSubdomain, field.TypeString, value)
	}
	if _u.mutation.DomainSubdomainCleared() {
		_spec.ClearField(rootcause.FieldDomainSubdomain, field.TypeString)
	}
	if value, ok := _u.mutation.DomainTeam(); ok {
		_spec.SetField(rootcause.FieldDomainTeam, field.TypeString, value)
	}
	if _u.mutation.DomainTeamCleared() {
		_spec.ClearField(rootcause.FieldDomainTeam, field.TypeString)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(rootcause.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.SymptomPatterns(); ok {
		_spec.SetField(rootcause.FieldSymptomPatterns, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSymptomPatterns(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rootcause.FieldSymptomPatterns, value)
		})
	}
	if _u.mutation.SymptomPatternsCleared() {
		_spec.ClearField(rootcause.FieldSymptomPatterns, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImpactSignalCount(); ok {
		_spec.SetField(rootcause.FieldImpactSignalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImpactSignalCount(); ok {
		_spec.AddField(rootcause.FieldImpactSignalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImpactAffectedCustomers(); ok {
		_spec.SetField(rootcause.FieldImpactAffectedCustomers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImpactAffectedCustomers(); ok {
		_spec.AddField(rootcause.FieldImpactAffectedCustomers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImpactAffectedEntities(); ok {
		_spec.SetField(rootcause.FieldImpactAffectedEntities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImpactAffectedEntities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rootcause.FieldImpactAffectedEntities, value)
		})
	}
	if _u.mutation.ImpactAffectedEntitiesCleared() {
		_spec.ClearField(rootcause.FieldImpactAffectedEntities, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImpactEscalationRate(); ok {
		_spec.SetField(rootcause.FieldImpactEscalationRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImpactEscalationRate(); ok {
		_spec.AddField(rootcause.FieldImpactEscalationRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImpactEstimatedRevenueLoss(); ok {
		_spec.SetField(rootcause.FieldImpactEstimatedRevenueLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImpactEstimatedRevenueLoss(); ok {
		_spec.AddField(rootcause.FieldImpactEstimatedRevenueLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrendDirection(); ok {
		_spec.SetField(rootcause.FieldTrendDirection, field.TypeString, value)
	}
	if _u.mutation.TrendDirectionCleared() {
		_spec.ClearField(rootcause.FieldTrendDirection, field.TypeString)
	}
	if value, ok := _u.mutation.TrendVelocity(); ok {
		_spec.SetField(rootcause.FieldTrendVelocity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrendVelocity(); ok {
		_spec.AddField(rootcause.FieldTrendVelocity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrendPeriodStart(); ok {
		_spec.SetField(rootcause.FieldTrendPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.TrendPeriodStartCleared() {
		_spec.ClearField(rootcause.FieldTrendPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.TrendPeriodEnd(); ok {
		_spec.SetField(rootcause.FieldTrendPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.TrendPeriodEndCleared() {
		_spec.ClearField(rootcause.FieldTrendPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.PriorityScore(); ok {
		_spec.SetField(rootcause.FieldPriorityScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriorityScore(); ok {
		_spec.AddField(rootcause.FieldPriorityScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstSeen(); ok {
		_spec.SetField(rootcause.FieldFirstSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(rootcause.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerTeam(); ok {
		_spec.SetField(rootcause.FieldOwnerTeam, field.TypeString, value)
	}
	if _u.mutation.OwnerTeamCleared() {
		_spec.ClearField(rootcause.FieldOwnerTeam, field.TypeString)
	}
	if value, ok := _u.mutation.RemediationID(); ok {
		_spec.SetField(rootcause.FieldRemediationID, field.TypeString, value)
	}
	if _u.mutation.RemediationIDCleared() {
		_spec.ClearField(rootcause.FieldRemediationID, field.TypeString)
	}
	if value, ok := _u.mutation.RecurrenceCount(); ok {
		_spec.SetField(rootcause.FieldRecurrenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecurrenceCount(); ok {
		_spec.AddField(rootcause.FieldRecurrenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rootcause.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rootcause.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(rootcause.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rootcause.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(rootcause.FieldTags, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rootcause.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RootCauseUpdateOne is the builder for updating a single RootCause entity.
type RootCauseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RootCauseMutation
}

// SetTitle sets the "title" field.
func (_u *RootCauseUpdateOne) SetTitle(v string) *RootCauseUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableTitle(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RootCauseUpdateOne) SetDescription(v string) *RootCauseUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableDescription(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *RootCauseUpdateOne) ClearDescription() *RootCauseUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *RootCauseUpdateOne) SetStatus(v string) *RootCauseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableStatus(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDomainName sets the "domain_name" field.
func (_u *RootCauseUpdateOne) SetDomainName(v string) *RootCauseUpdateOne {
	_u.mutation.SetDomainName(v)
	return _u
}

// SetNillableDomainName sets the "domain_name" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableDomainName(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetDomainName(*v)
	}
	return _u
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (_u *RootCauseUpdateOne) SetDomainSubdomain(v string) *RootCauseUpdateOne {
	_u.mutation.SetDomainSubdomain(v)
	return _u
}

// SetNillableDomainSubdomain sets the "domain_subdomain" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableDomainSubdomain(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetDomainSubdomain(*v)
	}
	return _u
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (_u *RootCauseUpdateOne) ClearDomainSubdomain() *RootCauseUpdateOne {
	_u.mutation.ClearDomainSubdomain()
	return _u
}

// SetDomainTeam sets the "domain_team" field.
func (_u *RootCauseUpdateOne) SetDomainTeam(v string) *RootCauseUpdateOne {
	_u.mutation.SetDomainTeam(v)
	return _u
}

// SetNillableDomainTeam sets the "domain_team" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableDomainTeam(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetDomainTeam(*v)
	}
	return _u
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (_u *RootCauseUpdateOne) ClearDomainTeam() *RootCauseUpdateOne {
	_u.mutation.ClearDomainTeam()
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *RootCauseUpdateOne) SetSeverity(v string) *RootCauseUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableSeverity(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetSymptomPatterns sets the "symptom_patterns" field.
func (_u *RootCauseUpdateOne) SetSymptomPatterns(v []string) *RootCauseUpdateOne {
	_u.mutation.SetSymptomPatterns(v)
	return _u
}

// AppendSymptomPatterns appends value to the "symptom_patterns" field.
func (_u *RootCauseUpdateOne) AppendSymptomPatterns(v []string) *RootCauseUpdateOne {
	_u.mutation.AppendSymptomPatterns(v)
	return _u
}

// ClearSymptomPatterns clears the value of the "symptom_patterns" field.
func (_u *RootCauseUpdateOne) ClearSymptomPatterns() *RootCauseUpdateOne {
	_u.mutation.ClearSymptomPatterns()
	return _u
}

// SetImpactSignalCount sets the "impact_signal_count" field.
func (_u *RootCauseUpdateOne) SetImpactSignalCount(v int) *RootCauseUpdateOne {
	_u.mutation.ResetImpactSignalCount()
	_u.mutation.SetImpactSignalCount(v)
	return _u
}

// SetNillableImpactSignalCount sets the "impact_signal_count" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableImpactSignalCount(v *int) *RootCauseUpdateOne {
	if v != nil {
		_u.SetImpactSignalCount(*v)
	}
	return _u
}

// AddImpactSignalCount adds value to the "impact_signal_count" field.
func (_u *RootCauseUpdateOne) AddImpactSignalCount(v int) *RootCauseUpdateOne {
	_u.mutation.AddImpactSignalCount(v)
	return _u
}

// SetImpactAffectedCustomers sets the "impact_affected_customers" field.
func (_u *RootCauseUpdateOne) SetImpactAffectedCustomers(v int) *RootCauseUpdateOne {
	_u.mutation.ResetImpactAffectedCustomers()
	_u.mutation.SetImpactAffectedCustomers(v)
	return _u
}

// SetNillableImpactAffectedCustomers sets the "impact_affected_customers" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableImpactAffectedCustomers(v *int) *RootCauseUpdateOne {
	if v != nil {
		_u.SetImpactAffectedCustomers(*v)
	}
	return _u
}

// AddImpactAffectedCustomers adds value to the "impact_affected_customers" field.
func (_u *RootCauseUpdateOne) AddImpactAffectedCustomers(v int) *RootCauseUpdateOne {
	_u.mutation.AddImpactAffectedCustomers(v)
	return _u
}

// SetImpactAffectedEntities sets the "impact_affected_entities" field.
func (_u *RootCauseUpdateOne) SetImpactAffectedEntities(v []common.Entity) *RootCauseUpdateOne {
	_u.mutation.SetImpactAffectedEntities(v)
	return _u
}

// AppendImpactAffectedEntities appends value to the "impact_affected_entities" field.
func (_u *RootCauseUpdateOne) AppendImpactAffectedEntities(v []common.Entity) *RootCauseUpdateOne {
	_u.mutation.AppendImpactAffectedEntities(v)
	return _u
}

// ClearImpactAffectedEntities clears the value of the "impact_affected_entities" field.
func (_u *RootCauseUpdateOne) ClearImpactAffectedEntities() *RootCauseUpdateOne {
	_u.mutation.ClearImpactAffectedEntities()
	return _u
}

// SetImpactEscalationRate sets the "impact_escalation_rate" field.
func (_u *RootCauseUpdateOne) SetImpactEscalationRate(v float64) *RootCauseUpdateOne {
	_u.mutation.ResetImpactEscalationRate()
	_u.mutation.SetImpactEscalationRate(v)
	return _u
}

// SetNillableImpactEscalationRate sets the "impact_escalation_rate" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableImpactEscalationRate(v *float64) *RootCauseUpdateOne {
	if v != nil {
		_u.SetImpactEscalationRate(*v)
	}
	return _u
}

// AddImpactEscalationRate adds value to the "impact_escalation_rate" field.
func (_u *RootCauseUpdateOne) AddImpactEscalationRate(v float64) *RootCauseUpdateOne {
	_u.mutation.AddImpactEscalationRate(v)
	return _u
}

// SetImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field.
func (_u *RootCauseUpdateOne) SetImpactEstimatedRevenueLoss(v float64) *RootCauseUpdateOne {
	_u.mutation.ResetImpactEstimatedRevenueLoss()
	_u.mutation.SetImpactEstimatedRevenueLoss(v)
	return _u
}

// SetNillableImpactEstimatedRevenueLoss sets the "impact_estimated_revenue_loss" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableImpactEstimatedRevenueLoss(v *float64) *RootCauseUpdateOne {
	if v != nil {
		_u.SetImpactEstimatedRevenueLoss(*v)
	}
	return _u
}

// AddImpactEstimatedRevenueLoss adds value to the "impact_estimated_revenue_loss" field.
func (_u *RootCauseUpdateOne) AddImpactEstimatedRevenueLoss(v float64) *RootCauseUpdateOne {
	_u.mutation.AddImpactEstimatedRevenueLoss(v)
	return _u
}

// SetTrendDirection sets the "trend_direction" field.
func (_u *RootCauseUpdateOne) SetTrendDirection(v string) *RootCauseUpdateOne {
	_u.mutation.SetTrendDirection(v)
	return _u
}

// SetNillableTrendDirection sets the "trend_direction" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableTrendDirection(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetTrendDirection(*v)
	}
	return _u
}

// ClearTrendDirection clears the value of the "trend_direction" field.
func (_u *RootCauseUpdateOne) ClearTrendDirection() *RootCauseUpdateOne {
	_u.mutation.ClearTrendDirection()
	return _u
}

// SetTrendVelocity sets the "trend_velocity" field.
func (_u *RootCauseUpdateOne) SetTrendVelocity(v float64) *RootCauseUpdateOne {
	_u.mutation.ResetTrendVelocity()
	_u.mutation.SetTrendVelocity(v)
	return _u
}

// SetNillableTrendVelocity sets the "trend_velocity" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableTrendVelocity(v *float64) *RootCauseUpdateOne {
	if v != nil {
		_u.SetTrendVelocity(*v)
	}
	return _u
}

// AddTrendVelocity adds value to the "trend_velocity" field.
func (_u *RootCauseUpdateOne) AddTrendVelocity(v float64) *RootCauseUpdateOne {
	_u.mutation.AddTrendVelocity(v)
	return _u
}

// SetTrendPeriodStart sets the "trend_period_start" field.
func (_u *RootCauseUpdateOne) SetTrendPeriodStart(v time.Time) *RootCauseUpdateOne {
	_u.mutation.SetTrendPeriodStart(v)
	return _u
}

// SetNillableTrendPeriodStart sets the "trend_period_start" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableTrendPeriodStart(v *time.Time) *RootCauseUpdateOne {
	if v != nil {
		_u.SetTrendPeriodStart(*v)
	}
	return _u
}

// ClearTrendPeriodStart clears the value of the "trend_period_start" field.
func (_u *RootCauseUpdateOne) ClearTrendPeriodStart() *RootCauseUpdateOne {
	_u.mutation.ClearTrendPeriodStart()
	return _u
}

// SetTrendPeriodEnd sets the "trend_period_end" field.
func (_u *RootCauseUpdateOne) SetTrendPeriodEnd(v time.Time) *RootCauseUpdateOne {
	_u.mutation.SetTrendPeriodEnd(v)
	return _u
}

// SetNillableTrendPeriodEnd sets the "trend_period_end" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableTrendPeriodEnd(v *time.Time) *RootCauseUpdateOne {
	if v != nil {
		_u.SetTrendPeriodEnd(*v)
	}
	return _u
}

// ClearTrendPeriodEnd clears the value of the "trend_period_end" field.
func (_u *RootCauseUpdateOne) ClearTrendPeriodEnd() *RootCauseUpdateOne {
	_u.mutation.ClearTrendPeriodEnd()
	return _u
}

// SetPriorityScore sets the "priority_score" field.
func (_u *RootCauseUpdateOne) SetPriorityScore(v int) *RootCauseUpdateOne {
	_u.mutation.ResetPriorityScore()
	_u.mutation.SetPriorityScore(v)
	return _u
}

// SetNillablePriorityScore sets the "priority_score" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillablePriorityScore(v *int) *RootCauseUpdateOne {
	if v != nil {
		_u.SetPriorityScore(*v)
	}
	return _u
}

// AddPriorityScore adds value to the "priority_score" field.
func (_u *RootCauseUpdateOne) AddPriorityScore(v int) *RootCauseUpdateOne {
	_u.mutation.AddPriorityScore(v)
	return _u
}

// SetFirstSeen sets the "first_seen" field.
func (_u *RootCauseUpdateOne) SetFirstSeen(v time.Time) *RootCauseUpdateOne {
	_u.mutation.SetFirstSeen(v)
	return _u
}

// SetNillableFirstSeen sets the "first_seen" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableFirstSeen(v *time.Time) *RootCauseUpdateOne {
	if v != nil {
		_u.SetFirstSeen(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *RootCauseUpdateOne) SetLastSeen(v time.Time) *RootCauseUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableLastSeen(v *time.Time) *RootCauseUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// SetOwnerTeam sets the "owner_team" field.
func (_u *RootCauseUpdateOne) SetOwnerTeam(v string) *RootCauseUpdateOne {
	_u.mutation.SetOwnerTeam(v)
	return _u
}

// SetNillableOwnerTeam sets the "owner_team" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableOwnerTeam(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetOwnerTeam(*v)
	}
	return _u
}

// ClearOwnerTeam clears the value of the "owner_team" field.
func (_u *RootCauseUpdateOne) ClearOwnerTeam() *RootCauseUpdateOne {
	_u.mutation.ClearOwnerTeam()
	return _u
}

// SetRemediationID sets the "remediation_id" field.
func (_u *RootCauseUpdateOne) SetRemediationID(v string) *RootCauseUpdateOne {
	_u.mutation.SetRemediationID(v)
	return _u
}

// SetNillableRemediationID sets the "remediation_id" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableRemediationID(v *string) *RootCauseUpdateOne {
	if v != nil {
		_u.SetRemediationID(*v)
	}
	return _u
}

// ClearRemediationID clears the value of the "remediation_id" field.
func (_u *RootCauseUpdateOne) ClearRemediationID() *RootCauseUpdateOne {
	_u.mutation.ClearRemediationID()
	return _u
}

// SetRecurrenceCount sets the "recurrence_count" field.
func (_u *RootCauseUpdateOne) SetRecurrenceCount(v int) *RootCauseUpdateOne {
	_u.mutation.ResetRecurrenceCount()
	_u.mutation.SetRecurrenceCount(v)
	return _u
}

// SetNillableRecurrenceCount sets the "recurrence_count" field if the given value is not nil.
func (_u *RootCauseUpdateOne) SetNillableRecurrenceCount(v *int) *RootCauseUpdateOne {
	if v != nil {
		_u.SetRecurrenceCount(*v)
	}
	return _u
}

// AddRecurrenceCount adds value to the "recurrence_count" field.
func (_u *RootCauseUpdateOne) AddRecurrenceCount(v int) *RootCauseUpdateOne {
	_u.mutation.AddRecurrenceCount(v)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RootCauseUpdateOne) SetMetadata(v map[string]interface{}) *RootCauseUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RootCauseUpdateOne) ClearMetadata() *RootCauseUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetTags sets the "tags" field.
func (_u *RootCauseUpdateOne) SetTags(v []common.Tag) *RootCauseUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *RootCauseUpdateOne) AppendTags(v []common.Tag) *RootCauseUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *RootCauseUpdateOne) ClearTags() *RootCauseUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the RootCauseMutation object of the builder.
func (_u *RootCauseUpdateOne) Mutation() *RootCauseMutation {
	return _u.mutation
}

// Where appends a list predicates to the RootCauseUpdate builder.
func (_u *RootCauseUpdateOne) Where(ps ...predicate.RootCause) *RootCauseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RootCauseUpdateOne) Select(field string, fields ...string) *RootCauseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RootCause entity.
func (_u *RootCauseUpdateOne) Save(ctx context.Context) (*RootCause, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RootCauseUpdateOne) SaveX(ctx context.Context) *RootCause {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RootCauseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RootCauseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RootCauseUpdateOne) sqlSave(ctx context.Context) (_node *RootCause, err error) {
	_spec := sqlgraph.NewUpdateSpec(rootcause.Table, rootcause.Columns, sqlgraph.NewFieldSpec(rootcause.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RootCause.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rootcause.FieldID)
		for _, f := range fields {
			if !rootcause.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rootcause.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(rootcause.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rootcause.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(rootcause.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rootcause.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DomainName(); ok {
		_spec.SetField(rootcause.FieldDomainName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DomainSubdomain(); ok {
		_spec.SetField(rootcause.FieldDomainSubdomain, field.TypeString, value)
	}
	if _u.mutation.DomainSubdomainCleared() {
		_spec.ClearField(rootcause.FieldDomainSubdomain, field.TypeString)
	}
	if value, ok := _u.mutation.DomainTeam(); ok {
		_spec.SetField(rootcause.FieldDomainTeam, field.TypeString, value)
	}
	if _u.mutation.DomainTeamCleared() {
		_spec.ClearField(rootcause.FieldDomainTeam, field.TypeString)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(rootcause.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.SymptomPatterns(); ok {
		_spec.SetField(rootcause.FieldSymptomPatterns, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSymptomPatterns(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rootcause.FieldSymptomPatterns, value)
		})
	}
	if _u.mutation.SymptomPatternsCleared() {
		_spec.ClearField(rootcause.FieldSymptomPatterns, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImpactSignalCount(); ok {
		_spec.SetField(rootcause.FieldImpactSignalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImpactSignalCount(); ok {
		_spec.AddField(rootcause.FieldImpactSignalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImpactAffectedCustomers(); ok {
		_spec.SetField(rootcause.FieldImpactAffectedCustomers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImpactAffectedCustomers(); ok {
		_spec.AddField(rootcause.FieldImpactAffectedCustomers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImpactAffectedEntities(); ok {
		_spec.SetField(rootcause.FieldImpactAffectedEntities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImpactAffectedEntities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rootcause.FieldImpactAffectedEntities, value)
		})
	}
	if _u.mutation.ImpactAffectedEntitiesCleared() {
		_spec.ClearField(rootcause.FieldImpactAffectedEntities, field.TypeJSON)
	}
	if value, ok := _u.mutation.ImpactEscalationRate(); ok {
		_spec.SetField(rootcause.FieldImpactEscalationRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImpactEscalationRate(); ok {
		_spec.AddField(rootcause.FieldImpactEscalationRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ImpactEstimatedRevenueLoss(); ok {
		_spec.SetField(rootcause.FieldImpactEstimatedRevenueLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImpactEstimatedRevenueLoss(); ok {
		_spec.AddField(rootcause.FieldImpactEstimatedRevenueLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrendDirection(); ok {
		_spec.SetField(rootcause.FieldTrendDirection, field.TypeString, value)
	}
	if _u.mutation.TrendDirectionCleared() {
		_spec.ClearField(rootcause.FieldTrendDirection, field.TypeString)
	}
	if value, ok := _u.mutation.TrendVelocity(); ok {
		_spec.SetField(rootcause.FieldTrendVelocity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrendVelocity(); ok {
		_spec.AddField(rootcause.FieldTrendVelocity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrendPeriodStart(); ok {
		_spec.SetField(rootcause.FieldTrendPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.TrendPeriodStartCleared() {
		_spec.ClearField(rootcause.FieldTrendPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.TrendPeriodEnd(); ok {
		_spec.SetField(rootcause.FieldTrendPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.TrendPeriodEndCleared() {
		_spec.ClearField(rootcause.FieldTrendPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.PriorityScore(); ok {
		_spec.SetField(rootcause.FieldPriorityScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriorityScore(); ok {
		_spec.AddField(rootcause.FieldPriorityScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstSeen(); ok {
		_spec.SetField(rootcause.FieldFirstSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(rootcause.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerTeam(); ok {
		_spec.SetField(rootcause.FieldOwnerTeam, field.TypeString, value)
	}
	if _u.mutation.OwnerTeamCleared() {
		_spec.ClearField(rootcause.FieldOwnerTeam, field.TypeString)
	}
	if value, ok := _u.mutation.RemediationID(); ok {
		_spec.SetField(rootcause.FieldRemediationID, field.TypeString, value)
	}
	if _u.mutation.RemediationIDCleared() {
		_spec.ClearField(rootcause.FieldRemediationID, field.TypeString)
	}
	if value, ok := _u.mutation.RecurrenceCount(); ok {
		_spec.SetField(rootcause.FieldRecurrenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRecurrenceCount(); ok {
		_spec.AddField(rootcause.FieldRecurrenceCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(rootcause.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(rootcause.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(rootcause.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, rootcause.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(rootcause.FieldTags, field.TypeJSON)
	}
	_node = &RootCause{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rootcause.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
