// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/plexusone/omnisignal/store/sqlite/ent/rootcause"
	"github.com/plexusone/omnisignal/store/sqlite/ent/schema"
	"github.com/plexusone/omnisignal/store/sqlite/ent/signalrootcauselink"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	rootcauseFields := schema.RootCause{}.Fields()
	_ = rootcauseFields
	// rootcauseDescImpactSignalCount is the schema descriptor for impact_signal_count field.
	rootcauseDescImpactSignalCount := rootcauseFields[9].Descriptor()
	// rootcause.DefaultImpactSignalCount holds the default value on creation for the impact_signal_count field.
	rootcause.DefaultImpactSignalCount = rootcauseDescImpactSignalCount.Default.(int)
	// rootcauseDescImpactAffectedCustomers is the schema descriptor for impact_affected_customers field.
	rootcauseDescImpactAffectedCustomers := rootcauseFields[10].Descriptor()
	// rootcause.DefaultImpactAffectedCustomers holds the default value on creation for the impact_affected_customers field.
	rootcause.DefaultImpactAffectedCustomers = rootcauseDescImpactAffectedCustomers.Default.(int)
	// rootcauseDescImpactEscalationRate is the schema descriptor for impact_escalation_rate field.
	rootcauseDescImpactEscalationRate := rootcauseFields[12].Descriptor()
	// rootcause.DefaultImpactEscalationRate holds the default value on creation for the impact_escalation_rate field.
	rootcause.DefaultImpactEscalationRate = rootcauseDescImpactEscalationRate.Default.(float64)
	// rootcauseDescImpactEstimatedRevenueLoss is the schema descriptor for impact_estimated_revenue_loss field.
	rootcauseDescImpactEstimatedRevenueLoss := rootcauseFields[13].Descriptor()
	// rootcause.DefaultImpactEstimatedRevenueLoss holds the default value on creation for the impact_estimated_revenue_loss field.
	rootcause.DefaultImpactEstimatedRevenueLoss = rootcauseDescImpactEstimatedRevenueLoss.Default.(float64)
	// rootcauseDescTrendVelocity is the schema descriptor for trend_velocity field.
	rootcauseDescTrendVelocity := rootcauseFields[15].Descriptor()
	// rootcause.DefaultTrendVelocity holds the default value on creation for the trend_velocity field.
	rootcause.DefaultTrendVelocity = rootcauseDescTrendVelocity.Default.(float64)
	// rootcauseDescPriorityScore is the schema descriptor for priority_score field.
	rootcauseDescPriorityScore := rootcauseFields[18].Descriptor()
	// rootcause.DefaultPriorityScore holds the default value on creation for the priority_score field.
	rootcause.DefaultPriorityScore = rootcauseDescPriorityScore.Default.(int)
	// rootcauseDescRecurrenceCount is the schema descriptor for recurrence_count field.
	rootcauseDescRecurrenceCount := rootcauseFields[23].Descriptor()
	// rootcause.DefaultRecurrenceCount holds the default value on creation for the recurrence_count field.
	rootcause.DefaultRecurrenceCount = rootcauseDescRecurrenceCount.Default.(int)
	signalrootcauselinkFields := schema.SignalRootCauseLink{}.Fields()
	_ = signalrootcauselinkFields
	// signalrootcauselinkDescLinkedAt is the schema descriptor for linked_at field.
	signalrootcauselinkDescLinkedAt := signalrootcauselinkFields[2].Descriptor()
	// signalrootcauselink.DefaultLinkedAt holds the default value on creation for the linked_at field.
	signalrootcauselink.DefaultLinkedAt = signalrootcauselinkDescLinkedAt.Default.(func() time.Time)
}
