// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnisignal/store/sqlite/ent/predicate"
	"github.com/plexusone/omnisignal/store/sqlite/ent/signalrootcauselink"
)

// SignalRootCauseLinkUpdate is the builder for updating SignalRootCauseLink entities.
type SignalRootCauseLinkUpdate struct {
	config
	hooks    []Hook
	mutation *SignalRootCauseLinkMutation
}

// Where appends a list predicates to the SignalRootCauseLinkUpdate builder.
func (_u *SignalRootCauseLinkUpdate) Where(ps ...predicate.SignalRootCauseLink) *SignalRootCauseLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSignalID sets the "signal_id" field.
func (_u *SignalRootCauseLinkUpdate) SetSignalID(v string) *SignalRootCauseLinkUpdate {
	_u.mutation.SetSignalID(v)
	return _u
}

// SetNillableSignalID sets the "signal_id" field if the given value is not nil.
func (_u *SignalRootCauseLinkUpdate) SetNillableSignalID(v *string) *SignalRootCauseLinkUpdate {
	if v != nil {
		_u.SetSignalID(*v)
	}
	return _u
}

// SetRootCauseID sets the "root_cause_id" field.
func (_u *SignalRootCauseLinkUpdate) SetRootCauseID(v string) *SignalRootCauseLinkUpdate {
	_u.mutation.SetRootCauseID(v)
	return _u
}

// SetNillableRootCauseID sets the "root_cause_id" field if the given value is not nil.
func (_u *SignalRootCauseLinkUpdate) SetNillableRootCauseID(v *string) *SignalRootCauseLinkUpdate {
	if v != nil {
		_u.SetRootCauseID(*v)
	}
	return _u
}

// SetLinkedAt sets the "linked_at" field.
func (_u *SignalRootCauseLinkUpdate) SetLinkedAt(v time.Time) *SignalRootCauseLinkUpdate {
	_u.mutation.SetLinkedAt(v)
	return _u
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_u *SignalRootCauseLinkUpdate) SetNillableLinkedAt(v *time.Time) *SignalRootCauseLinkUpdate {
	if v != nil {
		_u.SetLinkedAt(*v)
	}
	return _u
}

// Mutation returns the SignalRootCauseLinkMutation object of the builder.
func (_u *SignalRootCauseLinkUpdate) Mutation() *SignalRootCauseLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SignalRootCauseLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignalRootCauseLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SignalRootCauseLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignalRootCauseLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SignalRootCauseLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(signalrootcauselink.Table, signalrootcauselink.Columns, sqlgraph.NewFieldSpec(signalrootcauselink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SignalID(); ok {
		_spec.SetField(signalrootcauselink.FieldSignalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootCauseID(); ok {
		_spec.SetField(signalrootcauselink.FieldRootCauseID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkedAt(); ok {
		_spec.SetField(signalrootcauselink.FieldLinkedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signalrootcauselink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SignalRootCauseLinkUpdateOne is the builder for updating a single SignalRootCauseLink entity.
type SignalRootCauseLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignalRootCauseLinkMutation
}

// SetSignalID sets the "signal_id" field.
func (_u *SignalRootCauseLinkUpdateOne) SetSignalID(v string) *SignalRootCauseLinkUpdateOne {
	_u.mutation.SetSignalID(v)
	return _u
}

// SetNillableSignalID sets the "signal_id" field if the given value is not nil.
func (_u *SignalRootCauseLinkUpdateOne) SetNillableSignalID(v *string) *SignalRootCauseLinkUpdateOne {
	if v != nil {
		_u.SetSignalID(*v)
	}
	return _u
}

// SetRootCauseID sets the "root_cause_id" field.
func (_u *SignalRootCauseLinkUpdateOne) SetRootCauseID(v string) *SignalRootCauseLinkUpdateOne {
	_u.mutation.SetRootCauseID(v)
	return _u
}

// SetNillableRootCauseID sets the "root_cause_id" field if the given value is not nil.
func (_u *SignalRootCauseLinkUpdateOne) SetNillableRootCauseID(v *string) *SignalRootCauseLinkUpdateOne {
	if v != nil {
		_u.SetRootCauseID(*v)
	}
	return _u
}

// SetLinkedAt sets the "linked_at" field.
func (_u *SignalRootCauseLinkUpdateOne) SetLinkedAt(v time.Time) *SignalRootCauseLinkUpdateOne {
	_u.mutation.SetLinkedAt(v)
	return _u
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_u *SignalRootCauseLinkUpdateOne) SetNillableLinkedAt(v *time.Time) *SignalRootCauseLinkUpdateOne {
	if v != nil {
		_u.SetLinkedAt(*v)
	}
	return _u
}

// Mutation returns the SignalRootCauseLinkMutation object of the builder.
func (_u *SignalRootCauseLinkUpdateOne) Mutation() *SignalRootCauseLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the SignalRootCauseLinkUpdate builder.
func (_u *SignalRootCauseLinkUpdateOne) Where(ps ...predicate.SignalRootCauseLink) *SignalRootCauseLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SignalRootCauseLinkUpdateOne) Select(field string, fields ...string) *SignalRootCauseLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SignalRootCauseLink entity.
func (_u *SignalRootCauseLinkUpdateOne) Save(ctx context.Context) (*SignalRootCauseLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignalRootCauseLinkUpdateOne) SaveX(ctx context.Context) *SignalRootCauseLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SignalRootCauseLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignalRootCauseLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SignalRootCauseLinkUpdateOne) sqlSave(ctx context.Context) (_node *SignalRootCauseLink, err error) {
	_spec := sqlgraph.NewUpdateSpec(signalrootcauselink.Table, signalrootcauselink.Columns, sqlgraph.NewFieldSpec(signalrootcauselink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SignalRootCauseLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, signalrootcauselink.FieldID)
		for _, f := range fields {
			if !signalrootcauselink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != signalrootcauselink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SignalID(); ok {
		_spec.SetField(signalrootcauselink.FieldSignalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RootCauseID(); ok {
		_spec.SetField(signalrootcauselink.FieldRootCauseID, field.TypeString, value)
	}
	if value, ok := _u.mutation.LinkedAt(); ok {
		_spec.SetField(signalrootcauselink.FieldLinkedAt, field.TypeTime, value)
	}
	_node = &SignalRootCauseLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{signalrootcauselink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
