// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnisignal/store/sqlite/ent/signalrootcauselink"
)

// SignalRootCauseLinkCreate is the builder for creating a SignalRootCauseLink entity.
type SignalRootCauseLinkCreate struct {
	config
	mutation *SignalRootCauseLinkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSignalID sets the "signal_id" field.
func (_c *SignalRootCauseLinkCreate) SetSignalID(v string) *SignalRootCauseLinkCreate {
	_c.mutation.SetSignalID(v)
	return _c
}

// SetRootCauseID sets the "root_cause_id" field.
func (_c *SignalRootCauseLinkCreate) SetRootCauseID(v string) *SignalRootCauseLinkCreate {
	_c.mutation.SetRootCauseID(v)
	return _c
}

// SetLinkedAt sets the "linked_at" field.
func (_c *SignalRootCauseLinkCreate) SetLinkedAt(v time.Time) *SignalRootCauseLinkCreate {
	_c.mutation.SetLinkedAt(v)
	return _c
}

// SetNillableLinkedAt sets the "linked_at" field if the given value is not nil.
func (_c *SignalRootCauseLinkCreate) SetNillableLinkedAt(v *time.Time) *SignalRootCauseLinkCreate {
	if v != nil {
		_c.SetLinkedAt(*v)
	}
	return _c
}

// Mutation returns the SignalRootCauseLinkMutation object of the builder.
func (_c *SignalRootCauseLinkCreate) Mutation() *SignalRootCauseLinkMutation {
	return _c.mutation
}

// Save creates the SignalRootCauseLink in the database.
func (_c *SignalRootCauseLinkCreate) Save(ctx context.Context) (*SignalRootCauseLink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SignalRootCauseLinkCreate) SaveX(ctx context.Context) *SignalRootCauseLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignalRootCauseLinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignalRootCauseLinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SignalRootCauseLinkCreate) defaults() {
	if _, ok := _c.mutation.LinkedAt(); !ok {
		v := signalrootcauselink.DefaultLinkedAt()
		_c.mutation.SetLinkedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SignalRootCauseLinkCreate) check() error {
	if _, ok := _c.mutation.SignalID(); !ok {
		return &ValidationError{Name: "signal_id", err: errors.New(`ent: missing required field "SignalRootCauseLink.signal_id"`)}
	}
	if _, ok := _c.mutation.RootCauseID(); !ok {
		return &ValidationError{Name: "root_cause_id", err: errors.New(`ent: missing required field "SignalRootCauseLink.root_cause_id"`)}
	}
	if _, ok := _c.mutation.LinkedAt(); !ok {
		return &ValidationError{Name: "linked_at", err: errors.New(`ent: missing required field "SignalRootCauseLink.linked_at"`)}
	}
	return nil
}

func (_c *SignalRootCauseLinkCreate) sqlSave(ctx context.Context) (*SignalRootCauseLink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SignalRootCauseLinkCreate) createSpec() (*SignalRootCauseLink, *sqlgraph.CreateSpec) {
	var (
		_node = &SignalRootCauseLink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(signalrootcauselink.Table, sqlgraph.NewFieldSpec(signalrootcauselink.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SignalID(); ok {
		_spec.SetField(signalrootcauselink.FieldSignalID, field.TypeString, value)
		_node.SignalID = value
	}
	if value, ok := _c.mutation.RootCauseID(); ok {
		_spec.SetField(signalrootcauselink.FieldRootCauseID, field.TypeString, value)
		_node.RootCauseID = value
	}
	if value, ok := _c.mutation.LinkedAt(); ok {
		_spec.SetField(signalrootcauselink.FieldLinkedAt, field.TypeTime, value)
		_node.LinkedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SignalRootCauseLink.Create().
//		SetSignalID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignalRootCauseLinkUpsert) {
//			SetSignalID(v+v).
//		}).
//		Exec(ctx)
func (_c *SignalRootCauseLinkCreate) OnConflict(opts ...sql.ConflictOption) *SignalRootCauseLinkUpsertOne {
	_c.conflict = opts
	return &SignalRootCauseLinkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SignalRootCauseLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignalRootCauseLinkCreate) OnConflictColumns(columns ...string) *SignalRootCauseLinkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignalRootCauseLinkUpsertOne{
		create: _c,
	}
}

type (
	// SignalRootCauseLinkUpsertOne is the builder for "upsert"-ing
	//  one SignalRootCauseLink node.
	SignalRootCauseLinkUpsertOne struct {
		create *SignalRootCauseLinkCreate
	}

	// SignalRootCauseLinkUpsert is the "OnConflict" setter.
	SignalRootCauseLinkUpsert struct {
		*sql.UpdateSet
	}
)

// SetSignalID sets the "signal_id" field.
func (u *SignalRootCauseLinkUpsert) SetSignalID(v string) *SignalRootCauseLinkUpsert {
	u.Set(signalrootcauselink.FieldSignalID, v)
	return u
}

// UpdateSignalID sets the "signal_id" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsert) UpdateSignalID() *SignalRootCauseLinkUpsert {
	u.SetExcluded(signalrootcauselink.FieldSignalID)
	return u
}

// SetRootCauseID sets the "root_cause_id" field.
func (u *SignalRootCauseLinkUpsert) SetRootCauseID(v string) *SignalRootCauseLinkUpsert {
	u.Set(signalrootcauselink.FieldRootCauseID, v)
	return u
}

// UpdateRootCauseID sets the "root_cause_id" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsert) UpdateRootCauseID() *SignalRootCauseLinkUpsert {
	u.SetExcluded(signalrootcauselink.FieldRootCauseID)
	return u
}

// SetLinkedAt sets the "linked_at" field.
func (u *SignalRootCauseLinkUpsert) SetLinkedAt(v time.Time) *SignalRootCauseLinkUpsert {
	u.Set(signalrootcauselink.FieldLinkedAt, v)
	return u
}

// UpdateLinkedAt sets the "linked_at" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsert) UpdateLinkedAt() *SignalRootCauseLinkUpsert {
	u.SetExcluded(signalrootcauselink.FieldLinkedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SignalRootCauseLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SignalRootCauseLinkUpsertOne) UpdateNewValues() *SignalRootCauseLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SignalRootCauseLink.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SignalRootCauseLinkUpsertOne) Ignore() *SignalRootCauseLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignalRootCauseLinkUpsertOne) DoNothing() *SignalRootCauseLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignalRootCauseLinkCreate.OnConflict
// documentation for more info.
func (u *SignalRootCauseLinkUpsertOne) Update(set func(*SignalRootCauseLinkUpsert)) *SignalRootCauseLinkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignalRootCauseLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetSignalID sets the "signal_id" field.
func (u *SignalRootCauseLinkUpsertOne) SetSignalID(v string) *SignalRootCauseLinkUpsertOne {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.SetSignalID(v)
	})
}

// UpdateSignalID sets the "signal_id" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsertOne) UpdateSignalID() *SignalRootCauseLinkUpsertOne {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.UpdateSignalID()
	})
}

// SetRootCauseID sets the "root_cause_id" field.
func (u *SignalRootCauseLinkUpsertOne) SetRootCauseID(v string) *SignalRootCauseLinkUpsertOne {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.SetRootCauseID(v)
	})
}

// UpdateRootCauseID sets the "root_cause_id" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsertOne) UpdateRootCauseID() *SignalRootCauseLinkUpsertOne {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.UpdateRootCauseID()
	})
}

// SetLinkedAt sets the "linked_at" field.
func (u *SignalRootCauseLinkUpsertOne) SetLinkedAt(v time.Time) *SignalRootCauseLinkUpsertOne {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.SetLinkedAt(v)
	})
}

// UpdateLinkedAt sets the "linked_at" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsertOne) UpdateLinkedAt() *SignalRootCauseLinkUpsertOne {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.UpdateLinkedAt()
	})
}

// Exec executes the query.
func (u *SignalRootCauseLinkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SignalRootCauseLinkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignalRootCauseLinkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SignalRootCauseLinkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SignalRootCauseLinkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SignalRootCauseLinkCreateBulk is the builder for creating many SignalRootCauseLink entities in bulk.
type SignalRootCauseLinkCreateBulk struct {
	config
	err      error
	builders []*SignalRootCauseLinkCreate
	conflict []sql.ConflictOption
}

// Save creates the SignalRootCauseLink entities in the database.
func (_c *SignalRootCauseLinkCreateBulk) Save(ctx context.Context) ([]*SignalRootCauseLink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SignalRootCauseLink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignalRootCauseLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SignalRootCauseLinkCreateBulk) SaveX(ctx context.Context) []*SignalRootCauseLink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignalRootCauseLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignalRootCauseLinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SignalRootCauseLink.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignalRootCauseLinkUpsert) {
//			SetSignalID(v+v).
//		}).
//		Exec(ctx)
func (_c *SignalRootCauseLinkCreateBulk) OnConflict(opts ...sql.ConflictOption) *SignalRootCauseLinkUpsertBulk {
	_c.conflict = opts
	return &SignalRootCauseLinkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SignalRootCauseLink.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignalRootCauseLinkCreateBulk) OnConflictColumns(columns ...string) *SignalRootCauseLinkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignalRootCauseLinkUpsertBulk{
		create: _c,
	}
}

// SignalRootCauseLinkUpsertBulk is the builder for "upsert"-ing
// a bulk of SignalRootCauseLink nodes.
type SignalRootCauseLinkUpsertBulk struct {
	create *SignalRootCauseLinkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SignalRootCauseLink.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SignalRootCauseLinkUpsertBulk) UpdateNewValues() *SignalRootCauseLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SignalRootCauseLink.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SignalRootCauseLinkUpsertBulk) Ignore() *SignalRootCauseLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignalRootCauseLinkUpsertBulk) DoNothing() *SignalRootCauseLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignalRootCauseLinkCreateBulk.OnConflict
// documentation for more info.
func (u *SignalRootCauseLinkUpsertBulk) Update(set func(*SignalRootCauseLinkUpsert)) *SignalRootCauseLinkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignalRootCauseLinkUpsert{UpdateSet: update})
	}))
	return u
}

// SetSignalID sets the "signal_id" field.
func (u *SignalRootCauseLinkUpsertBulk) SetSignalID(v string) *SignalRootCauseLinkUpsertBulk {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.SetSignalID(v)
	})
}

// UpdateSignalID sets the "signal_id" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsertBulk) UpdateSignalID() *SignalRootCauseLinkUpsertBulk {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.UpdateSignalID()
	})
}

// SetRootCauseID sets the "root_cause_id" field.
func (u *SignalRootCauseLinkUpsertBulk) SetRootCauseID(v string) *SignalRootCauseLinkUpsertBulk {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.SetRootCauseID(v)
	})
}

// UpdateRootCauseID sets the "root_cause_id" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsertBulk) UpdateRootCauseID() *SignalRootCauseLinkUpsertBulk {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.UpdateRootCauseID()
	})
}

// SetLinkedAt sets the "linked_at" field.
func (u *SignalRootCauseLinkUpsertBulk) SetLinkedAt(v time.Time) *SignalRootCauseLinkUpsertBulk {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.SetLinkedAt(v)
	})
}

// UpdateLinkedAt sets the "linked_at" field to the value that was provided on create.
func (u *SignalRootCauseLinkUpsertBulk) UpdateLinkedAt() *SignalRootCauseLinkUpsertBulk {
	return u.Update(func(s *SignalRootCauseLinkUpsert) {
		s.UpdateLinkedAt()
	})
}

// Exec executes the query.
func (u *SignalRootCauseLinkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SignalRootCauseLinkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SignalRootCauseLinkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignalRootCauseLinkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
