// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/plexusone/omnisignal/store/sqlite/ent/predicate"
	entsignal "github.com/plexusone/omnisignal/store/sqlite/ent/signal"
	"github.com/plexusone/signal-spec/pkg/common"
	"github.com/plexusone/signal-spec/pkg/signal"
)

// SignalUpdate is the builder for updating Signal entities.
type SignalUpdate struct {
	config
	hooks    []Hook
	mutation *SignalMutation
}

// Where appends a list predicates to the SignalUpdate builder.
func (_u *SignalUpdate) Where(ps ...predicate.Signal) *SignalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *SignalUpdate) SetType(v string) *SignalUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableType(v *string) *SignalUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SignalUpdate) SetStatus(v string) *SignalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableStatus(v *string) *SignalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SignalUpdate) SetSourceType(v string) *SignalUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableSourceType(v *string) *SignalUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *SignalUpdate) SetSourceName(v string) *SignalUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableSourceName(v *string) *SignalUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// SetSourceExternalID sets the "source_external_id" field.
func (_u *SignalUpdate) SetSourceExternalID(v string) *SignalUpdate {
	_u.mutation.SetSourceExternalID(v)
	return _u
}

// SetNillableSourceExternalID sets the "source_external_id" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableSourceExternalID(v *string) *SignalUpdate {
	if v != nil {
		_u.SetSourceExternalID(*v)
	}
	return _u
}

// ClearSourceExternalID clears the value of the "source_external_id" field.
func (_u *SignalUpdate) ClearSourceExternalID() *SignalUpdate {
	_u.mutation.ClearSourceExternalID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SignalUpdate) SetSourceURL(v string) *SignalUpdate {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableSourceURL(v *string) *SignalUpdate {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *SignalUpdate) ClearSourceURL() *SignalUpdate {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetDomainName sets the "domain_name" field.
func (_u *SignalUpdate) SetDomainName(v string) *SignalUpdate {
	_u.mutation.SetDomainName(v)
	return _u
}

// SetNillableDomainName sets the "domain_name" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableDomainName(v *string) *SignalUpdate {
	if v != nil {
		_u.SetDomainName(*v)
	}
	return _u
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (_u *SignalUpdate) SetDomainSubdomain(v string) *SignalUpdate {
	_u.mutation.SetDomainSubdomain(v)
	return _u
}

// SetNillableDomainSubdomain sets the "domain_subdomain" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableDomainSubdomain(v *string) *SignalUpdate {
	if v != nil {
		_u.SetDomainSubdomain(*v)
	}
	return _u
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (_u *SignalUpdate) ClearDomainSubdomain() *SignalUpdate {
	_u.mutation.ClearDomainSubdomain()
	return _u
}

// SetDomainTeam sets the "domain_team" field.
func (_u *SignalUpdate) SetDomainTeam(v string) *SignalUpdate {
	_u.mutation.SetDomainTeam(v)
	return _u
}

// SetNillableDomainTeam sets the "domain_team" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableDomainTeam(v *string) *SignalUpdate {
	if v != nil {
		_u.SetDomainTeam(*v)
	}
	return _u
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (_u *SignalUpdate) ClearDomainTeam() *SignalUpdate {
	_u.mutation.ClearDomainTeam()
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *SignalUpdate) SetSeverity(v string) *SignalUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableSeverity(v *string) *SignalUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SignalUpdate) SetSummary(v string) *SignalUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableSummary(v *string) *SignalUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SignalUpdate) SetDescription(v string) *SignalUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableDescription(v *string) *SignalUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SignalUpdate) ClearDescription() *SignalUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntities sets the "entities" field.
func (_u *SignalUpdate) SetEntities(v []common.Entity) *SignalUpdate {
	_u.mutation.SetEntities(v)
	return _u
}

// AppendEntities appends value to the "entities" field.
func (_u *SignalUpdate) AppendEntities(v []common.Entity) *SignalUpdate {
	_u.mutation.AppendEntities(v)
	return _u
}

// ClearEntities clears the value of the "entities" field.
func (_u *SignalUpdate) ClearEntities() *SignalUpdate {
	_u.mutation.ClearEntities()
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *SignalUpdate) SetObservedAt(v time.Time) *SignalUpdate {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableObservedAt(v *time.Time) *SignalUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *SignalUpdate) SetReceivedAt(v time.Time) *SignalUpdate {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableReceivedAt(v *time.Time) *SignalUpdate {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *SignalUpdate) SetFingerprint(v string) *SignalUpdate {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *SignalUpdate) SetNillableFingerprint(v *string) *SignalUpdate {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (_u *SignalUpdate) ClearFingerprint() *SignalUpdate {
	_u.mutation.ClearFingerprint()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SignalUpdate) SetMetadata(v map[string]interface{}) *SignalUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SignalUpdate) ClearMetadata() *SignalUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDerived sets the "derived" field.
func (_u *SignalUpdate) SetDerived(v *signal.DerivedMetrics) *SignalUpdate {
	_u.mutation.SetDerived(v)
	return _u
}

// ClearDerived clears the value of the "derived" field.
func (_u *SignalUpdate) ClearDerived() *SignalUpdate {
	_u.mutation.ClearDerived()
	return _u
}

// SetTags sets the "tags" field.
func (_u *SignalUpdate) SetTags(v []common.Tag) *SignalUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *SignalUpdate) AppendTags(v []common.Tag) *SignalUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *SignalUpdate) ClearTags() *SignalUpdate {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the SignalMutation object of the builder.
func (_u *SignalUpdate) Mutation() *SignalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SignalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SignalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SignalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(entsignal.Table, entsignal.Columns, sqlgraph.NewFieldSpec(entsignal.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(entsignal.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(entsignal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(entsignal.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(entsignal.FieldSourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceExternalID(); ok {
		_spec.SetField(entsignal.FieldSourceExternalID, field.TypeString, value)
	}
	if _u.mutation.SourceExternalIDCleared() {
		_spec.ClearField(entsignal.FieldSourceExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(entsignal.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(entsignal.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.DomainName(); ok {
		_spec.SetField(entsignal.FieldDomainName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DomainSubdomain(); ok {
		_spec.SetField(entsignal.FieldDomainSubdomain, field.TypeString, value)
	}
	if _u.mutation.DomainSubdomainCleared() {
		_spec.ClearField(entsignal.FieldDomainSubdomain, field.TypeString)
	}
	if value, ok := _u.mutation.DomainTeam(); ok {
		_spec.SetField(entsignal.FieldDomainTeam, field.TypeString, value)
	}
	if _u.mutation.DomainTeamCleared() {
		_spec.ClearField(entsignal.FieldDomainTeam, field.TypeString)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(entsignal.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(entsignal.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(entsignal.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(entsignal.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Entities(); ok {
		_spec.SetField(entsignal.FieldEntities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEntities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entsignal.FieldEntities, value)
		})
	}
	if _u.mutation.EntitiesCleared() {
		_spec.ClearField(entsignal.FieldEntities, field.TypeJSON)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(entsignal.FieldObservedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(entsignal.FieldReceivedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(entsignal.FieldFingerprint, field.TypeString, value)
	}
	if _u.mutation.FingerprintCleared() {
		_spec.ClearField(entsignal.FieldFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(entsignal.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(entsignal.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Derived(); ok {
		_spec.SetField(entsignal.FieldDerived, field.TypeJSON, value)
	}
	if _u.mutation.DerivedCleared() {
		_spec.ClearField(entsignal.FieldDerived, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(entsignal.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entsignal.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(entsignal.FieldTags, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entsignal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SignalUpdateOne is the builder for updating a single Signal entity.
type SignalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SignalMutation
}

// SetType sets the "type" field.
func (_u *SignalUpdateOne) SetType(v string) *SignalUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableType(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SignalUpdateOne) SetStatus(v string) *SignalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableStatus(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *SignalUpdateOne) SetSourceType(v string) *SignalUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableSourceType(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *SignalUpdateOne) SetSourceName(v string) *SignalUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableSourceName(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// SetSourceExternalID sets the "source_external_id" field.
func (_u *SignalUpdateOne) SetSourceExternalID(v string) *SignalUpdateOne {
	_u.mutation.SetSourceExternalID(v)
	return _u
}

// SetNillableSourceExternalID sets the "source_external_id" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableSourceExternalID(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetSourceExternalID(*v)
	}
	return _u
}

// ClearSourceExternalID clears the value of the "source_external_id" field.
func (_u *SignalUpdateOne) ClearSourceExternalID() *SignalUpdateOne {
	_u.mutation.ClearSourceExternalID()
	return _u
}

// SetSourceURL sets the "source_url" field.
func (_u *SignalUpdateOne) SetSourceURL(v string) *SignalUpdateOne {
	_u.mutation.SetSourceURL(v)
	return _u
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableSourceURL(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetSourceURL(*v)
	}
	return _u
}

// ClearSourceURL clears the value of the "source_url" field.
func (_u *SignalUpdateOne) ClearSourceURL() *SignalUpdateOne {
	_u.mutation.ClearSourceURL()
	return _u
}

// SetDomainName sets the "domain_name" field.
func (_u *SignalUpdateOne) SetDomainName(v string) *SignalUpdateOne {
	_u.mutation.SetDomainName(v)
	return _u
}

// SetNillableDomainName sets the "domain_name" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableDomainName(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetDomainName(*v)
	}
	return _u
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (_u *SignalUpdateOne) SetDomainSubdomain(v string) *SignalUpdateOne {
	_u.mutation.SetDomainSubdomain(v)
	return _u
}

// SetNillableDomainSubdomain sets the "domain_subdomain" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableDomainSubdomain(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetDomainSubdomain(*v)
	}
	return _u
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (_u *SignalUpdateOne) ClearDomainSubdomain() *SignalUpdateOne {
	_u.mutation.ClearDomainSubdomain()
	return _u
}

// SetDomainTeam sets the "domain_team" field.
func (_u *SignalUpdateOne) SetDomainTeam(v string) *SignalUpdateOne {
	_u.mutation.SetDomainTeam(v)
	return _u
}

// SetNillableDomainTeam sets the "domain_team" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableDomainTeam(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetDomainTeam(*v)
	}
	return _u
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (_u *SignalUpdateOne) ClearDomainTeam() *SignalUpdateOne {
	_u.mutation.ClearDomainTeam()
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *SignalUpdateOne) SetSeverity(v string) *SignalUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableSeverity(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *SignalUpdateOne) SetSummary(v string) *SignalUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableSummary(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *SignalUpdateOne) SetDescription(v string) *SignalUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableDescription(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SignalUpdateOne) ClearDescription() *SignalUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEntities sets the "entities" field.
func (_u *SignalUpdateOne) SetEntities(v []common.Entity) *SignalUpdateOne {
	_u.mutation.SetEntities(v)
	return _u
}

// AppendEntities appends value to the "entities" field.
func (_u *SignalUpdateOne) AppendEntities(v []common.Entity) *SignalUpdateOne {
	_u.mutation.AppendEntities(v)
	return _u
}

// ClearEntities clears the value of the "entities" field.
func (_u *SignalUpdateOne) ClearEntities() *SignalUpdateOne {
	_u.mutation.ClearEntities()
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *SignalUpdateOne) SetObservedAt(v time.Time) *SignalUpdateOne {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableObservedAt(v *time.Time) *SignalUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetReceivedAt sets the "received_at" field.
func (_u *SignalUpdateOne) SetReceivedAt(v time.Time) *SignalUpdateOne {
	_u.mutation.SetReceivedAt(v)
	return _u
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableReceivedAt(v *time.Time) *SignalUpdateOne {
	if v != nil {
		_u.SetReceivedAt(*v)
	}
	return _u
}

// SetFingerprint sets the "fingerprint" field.
func (_u *SignalUpdateOne) SetFingerprint(v string) *SignalUpdateOne {
	_u.mutation.SetFingerprint(v)
	return _u
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_u *SignalUpdateOne) SetNillableFingerprint(v *string) *SignalUpdateOne {
	if v != nil {
		_u.SetFingerprint(*v)
	}
	return _u
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (_u *SignalUpdateOne) ClearFingerprint() *SignalUpdateOne {
	_u.mutation.ClearFingerprint()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SignalUpdateOne) SetMetadata(v map[string]interface{}) *SignalUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SignalUpdateOne) ClearMetadata() *SignalUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDerived sets the "derived" field.
func (_u *SignalUpdateOne) SetDerived(v *signal.DerivedMetrics) *SignalUpdateOne {
	_u.mutation.SetDerived(v)
	return _u
}

// ClearDerived clears the value of the "derived" field.
func (_u *SignalUpdateOne) ClearDerived() *SignalUpdateOne {
	_u.mutation.ClearDerived()
	return _u
}

// SetTags sets the "tags" field.
func (_u *SignalUpdateOne) SetTags(v []common.Tag) *SignalUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *SignalUpdateOne) AppendTags(v []common.Tag) *SignalUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *SignalUpdateOne) ClearTags() *SignalUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the SignalMutation object of the builder.
func (_u *SignalUpdateOne) Mutation() *SignalMutation {
	return _u.mutation
}

// Where appends a list predicates to the SignalUpdate builder.
func (_u *SignalUpdateOne) Where(ps ...predicate.Signal) *SignalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SignalUpdateOne) Select(field string, fields ...string) *SignalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Signal entity.
func (_u *SignalUpdateOne) Save(ctx context.Context) (*Signal, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SignalUpdateOne) SaveX(ctx context.Context) *Signal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SignalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SignalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SignalUpdateOne) sqlSave(ctx context.Context) (_node *Signal, err error) {
	_spec := sqlgraph.NewUpdateSpec(entsignal.Table, entsignal.Columns, sqlgraph.NewFieldSpec(entsignal.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Signal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entsignal.FieldID)
		for _, f := range fields {
			if !entsignal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entsignal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(entsignal.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(entsignal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(entsignal.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(entsignal.FieldSourceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceExternalID(); ok {
		_spec.SetField(entsignal.FieldSourceExternalID, field.TypeString, value)
	}
	if _u.mutation.SourceExternalIDCleared() {
		_spec.ClearField(entsignal.FieldSourceExternalID, field.TypeString)
	}
	if value, ok := _u.mutation.SourceURL(); ok {
		_spec.SetField(entsignal.FieldSourceURL, field.TypeString, value)
	}
	if _u.mutation.SourceURLCleared() {
		_spec.ClearField(entsignal.FieldSourceURL, field.TypeString)
	}
	if value, ok := _u.mutation.DomainName(); ok {
		_spec.SetField(entsignal.FieldDomainName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DomainSubdomain(); ok {
		_spec.SetField(entsignal.FieldDomainSubdomain, field.TypeString, value)
	}
	if _u.mutation.DomainSubdomainCleared() {
		_spec.ClearField(entsignal.FieldDomainSubdomain, field.TypeString)
	}
	if value, ok := _u.mutation.DomainTeam(); ok {
		_spec.SetField(entsignal.FieldDomainTeam, field.TypeString, value)
	}
	if _u.mutation.DomainTeamCleared() {
		_spec.ClearField(entsignal.FieldDomainTeam, field.TypeString)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(entsignal.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(entsignal.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(entsignal.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(entsignal.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Entities(); ok {
		_spec.SetField(entsignal.FieldEntities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEntities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entsignal.FieldEntities, value)
		})
	}
	if _u.mutation.EntitiesCleared() {
		_spec.ClearField(entsignal.FieldEntities, field.TypeJSON)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(entsignal.FieldObservedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReceivedAt(); ok {
		_spec.SetField(entsignal.FieldReceivedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Fingerprint(); ok {
		_spec.SetField(entsignal.FieldFingerprint, field.TypeString, value)
	}
	if _u.mutation.FingerprintCleared() {
		_spec.ClearField(entsignal.FieldFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(entsignal.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(entsignal.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Derived(); ok {
		_spec.SetField(entsignal.FieldDerived, field.TypeJSON, value)
	}
	if _u.mutation.DerivedCleared() {
		_spec.ClearField(entsignal.FieldDerived, field.TypeJSON)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(entsignal.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, entsignal.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(entsignal.FieldTags, field.TypeJSON)
	}
	_node = &Signal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entsignal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
