// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnisignal/store/sqlite/ent/signalrootcauselink"
)

// SignalRootCauseLink is the model entity for the SignalRootCauseLink schema.
type SignalRootCauseLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SignalID holds the value of the "signal_id" field.
	SignalID string `json:"signal_id,omitempty"`
	// RootCauseID holds the value of the "root_cause_id" field.
	RootCauseID string `json:"root_cause_id,omitempty"`
	// LinkedAt holds the value of the "linked_at" field.
	LinkedAt     time.Time `json:"linked_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SignalRootCauseLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case signalrootcauselink.FieldID:
			values[i] = new(sql.NullInt64)
		case signalrootcauselink.FieldSignalID, signalrootcauselink.FieldRootCauseID:
			values[i] = new(sql.NullString)
		case signalrootcauselink.FieldLinkedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SignalRootCauseLink fields.
func (_m *SignalRootCauseLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case signalrootcauselink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case signalrootcauselink.FieldSignalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field signal_id", values[i])
			} else if value.Valid {
				_m.SignalID = value.String
			}
		case signalrootcauselink.FieldRootCauseID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field root_cause_id", values[i])
			} else if value.Valid {
				_m.RootCauseID = value.String
			}
		case signalrootcauselink.FieldLinkedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field linked_at", values[i])
			} else if value.Valid {
				_m.LinkedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SignalRootCauseLink.
// This includes values selected through modifiers, order, etc.
func (_m *SignalRootCauseLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SignalRootCauseLink.
// Note that you need to call SignalRootCauseLink.Unwrap() before calling this method if this SignalRootCauseLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SignalRootCauseLink) Update() *SignalRootCauseLinkUpdateOne {
	return NewSignalRootCauseLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SignalRootCauseLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SignalRootCauseLink) Unwrap() *SignalRootCauseLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SignalRootCauseLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SignalRootCauseLink) String() string {
	var builder strings.Builder
	builder.WriteString("SignalRootCauseLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("signal_id=")
	builder.WriteString(_m.SignalID)
	builder.WriteString(", ")
	builder.WriteString("root_cause_id=")
	builder.WriteString(_m.RootCauseID)
	builder.WriteString(", ")
	builder.WriteString("linked_at=")
	builder.WriteString(_m.LinkedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SignalRootCauseLinks is a parsable slice of SignalRootCauseLink.
type SignalRootCauseLinks []*SignalRootCauseLink
