// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	entsignal "github.com/plexusone/omnisignal/store/sqlite/ent/signal"
	"github.com/plexusone/signal-spec/pkg/common"
	"github.com/plexusone/signal-spec/pkg/signal"
)

// SignalCreate is the builder for creating a Signal entity.
type SignalCreate struct {
	config
	mutation *SignalMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetType sets the "type" field.
func (_c *SignalCreate) SetType(v string) *SignalCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SignalCreate) SetStatus(v string) *SignalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *SignalCreate) SetSourceType(v string) *SignalCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceName sets the "source_name" field.
func (_c *SignalCreate) SetSourceName(v string) *SignalCreate {
	_c.mutation.SetSourceName(v)
	return _c
}

// SetSourceExternalID sets the "source_external_id" field.
func (_c *SignalCreate) SetSourceExternalID(v string) *SignalCreate {
	_c.mutation.SetSourceExternalID(v)
	return _c
}

// SetNillableSourceExternalID sets the "source_external_id" field if the given value is not nil.
func (_c *SignalCreate) SetNillableSourceExternalID(v *string) *SignalCreate {
	if v != nil {
		_c.SetSourceExternalID(*v)
	}
	return _c
}

// SetSourceURL sets the "source_url" field.
func (_c *SignalCreate) SetSourceURL(v string) *SignalCreate {
	_c.mutation.SetSourceURL(v)
	return _c
}

// SetNillableSourceURL sets the "source_url" field if the given value is not nil.
func (_c *SignalCreate) SetNillableSourceURL(v *string) *SignalCreate {
	if v != nil {
		_c.SetSourceURL(*v)
	}
	return _c
}

// SetDomainName sets the "domain_name" field.
func (_c *SignalCreate) SetDomainName(v string) *SignalCreate {
	_c.mutation.SetDomainName(v)
	return _c
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (_c *SignalCreate) SetDomainSubdomain(v string) *SignalCreate {
	_c.mutation.SetDomainSubdomain(v)
	return _c
}

// SetNillableDomainSubdomain sets the "domain_subdomain" field if the given value is not nil.
func (_c *SignalCreate) SetNillableDomainSubdomain(v *string) *SignalCreate {
	if v != nil {
		_c.SetDomainSubdomain(*v)
	}
	return _c
}

// SetDomainTeam sets the "domain_team" field.
func (_c *SignalCreate) SetDomainTeam(v string) *SignalCreate {
	_c.mutation.SetDomainTeam(v)
	return _c
}

// SetNillableDomainTeam sets the "domain_team" field if the given value is not nil.
func (_c *SignalCreate) SetNillableDomainTeam(v *string) *SignalCreate {
	if v != nil {
		_c.SetDomainTeam(*v)
	}
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *SignalCreate) SetSeverity(v string) *SignalCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *SignalCreate) SetSummary(v string) *SignalCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SignalCreate) SetDescription(v string) *SignalCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SignalCreate) SetNillableDescription(v *string) *SignalCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEntities sets the "entities" field.
func (_c *SignalCreate) SetEntities(v []common.Entity) *SignalCreate {
	_c.mutation.SetEntities(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *SignalCreate) SetObservedAt(v time.Time) *SignalCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *SignalCreate) SetReceivedAt(v time.Time) *SignalCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetFingerprint sets the "fingerprint" field.
func (_c *SignalCreate) SetFingerprint(v string) *SignalCreate {
	_c.mutation.SetFingerprint(v)
	return _c
}

// SetNillableFingerprint sets the "fingerprint" field if the given value is not nil.
func (_c *SignalCreate) SetNillableFingerprint(v *string) *SignalCreate {
	if v != nil {
		_c.SetFingerprint(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *SignalCreate) SetMetadata(v map[string]interface{}) *SignalCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetDerived sets the "derived" field.
func (_c *SignalCreate) SetDerived(v *signal.DerivedMetrics) *SignalCreate {
	_c.mutation.SetDerived(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *SignalCreate) SetTags(v []common.Tag) *SignalCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SignalCreate) SetID(v string) *SignalCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SignalMutation object of the builder.
func (_c *SignalCreate) Mutation() *SignalMutation {
	return _c.mutation
}

// Save creates the Signal in the database.
func (_c *SignalCreate) Save(ctx context.Context) (*Signal, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SignalCreate) SaveX(ctx context.Context) *Signal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SignalCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Signal.type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Signal.status"`)}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "Signal.source_type"`)}
	}
	if _, ok := _c.mutation.SourceName(); !ok {
		return &ValidationError{Name: "source_name", err: errors.New(`ent: missing required field "Signal.source_name"`)}
	}
	if _, ok := _c.mutation.DomainName(); !ok {
		return &ValidationError{Name: "domain_name", err: errors.New(`ent: missing required field "Signal.domain_name"`)}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "Signal.severity"`)}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Signal.summary"`)}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "Signal.observed_at"`)}
	}
	if _, ok := _c.mutation.ReceivedAt(); !ok {
		return &ValidationError{Name: "received_at", err: errors.New(`ent: missing required field "Signal.received_at"`)}
	}
	return nil
}

func (_c *SignalCreate) sqlSave(ctx context.Context) (*Signal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Signal.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SignalCreate) createSpec() (*Signal, *sqlgraph.CreateSpec) {
	var (
		_node = &Signal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(entsignal.Table, sqlgraph.NewFieldSpec(entsignal.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(entsignal.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(entsignal.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(entsignal.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceName(); ok {
		_spec.SetField(entsignal.FieldSourceName, field.TypeString, value)
		_node.SourceName = value
	}
	if value, ok := _c.mutation.SourceExternalID(); ok {
		_spec.SetField(entsignal.FieldSourceExternalID, field.TypeString, value)
		_node.SourceExternalID = value
	}
	if value, ok := _c.mutation.SourceURL(); ok {
		_spec.SetField(entsignal.FieldSourceURL, field.TypeString, value)
		_node.SourceURL = value
	}
	if value, ok := _c.mutation.DomainName(); ok {
		_spec.SetField(entsignal.FieldDomainName, field.TypeString, value)
		_node.DomainName = value
	}
	if value, ok := _c.mutation.DomainSubdomain(); ok {
		_spec.SetField(entsignal.FieldDomainSubdomain, field.TypeString, value)
		_node.DomainSubdomain = value
	}
	if value, ok := _c.mutation.DomainTeam(); ok {
		_spec.SetField(entsignal.FieldDomainTeam, field.TypeString, value)
		_node.DomainTeam = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(entsignal.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(entsignal.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(entsignal.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Entities(); ok {
		_spec.SetField(entsignal.FieldEntities, field.TypeJSON, value)
		_node.Entities = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(entsignal.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(entsignal.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = value
	}
	if value, ok := _c.mutation.Fingerprint(); ok {
		_spec.SetField(entsignal.FieldFingerprint, field.TypeString, value)
		_node.Fingerprint = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(entsignal.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Derived(); ok {
		_spec.SetField(entsignal.FieldDerived, field.TypeJSON, value)
		_node.Derived = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(entsignal.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Signal.Create().
//		SetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignalUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *SignalCreate) OnConflict(opts ...sql.ConflictOption) *SignalUpsertOne {
	_c.conflict = opts
	return &SignalUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Signal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignalCreate) OnConflictColumns(columns ...string) *SignalUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignalUpsertOne{
		create: _c,
	}
}

type (
	// SignalUpsertOne is the builder for "upsert"-ing
	//  one Signal node.
	SignalUpsertOne struct {
		create *SignalCreate
	}

	// SignalUpsert is the "OnConflict" setter.
	SignalUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *SignalUpsert) SetType(v string) *SignalUpsert {
	u.Set(entsignal.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SignalUpsert) UpdateType() *SignalUpsert {
	u.SetExcluded(entsignal.FieldType)
	return u
}

// SetStatus sets the "status" field.
func (u *SignalUpsert) SetStatus(v string) *SignalUpsert {
	u.Set(entsignal.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SignalUpsert) UpdateStatus() *SignalUpsert {
	u.SetExcluded(entsignal.FieldStatus)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *SignalUpsert) SetSourceType(v string) *SignalUpsert {
	u.Set(entsignal.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *SignalUpsert) UpdateSourceType() *SignalUpsert {
	u.SetExcluded(entsignal.FieldSourceType)
	return u
}

// SetSourceName sets the "source_name" field.
func (u *SignalUpsert) SetSourceName(v string) *SignalUpsert {
	u.Set(entsignal.FieldSourceName, v)
	return u
}

// UpdateSourceName sets the "source_name" field to the value that was provided on create.
func (u *SignalUpsert) UpdateSourceName() *SignalUpsert {
	u.SetExcluded(entsignal.FieldSourceName)
	return u
}

// SetSourceExternalID sets the "source_external_id" field.
func (u *SignalUpsert) SetSourceExternalID(v string) *SignalUpsert {
	u.Set(entsignal.FieldSourceExternalID, v)
	return u
}

// UpdateSourceExternalID sets the "source_external_id" field to the value that was provided on create.
func (u *SignalUpsert) UpdateSourceExternalID() *SignalUpsert {
	u.SetExcluded(entsignal.FieldSourceExternalID)
	return u
}

// ClearSourceExternalID clears the value of the "source_external_id" field.
func (u *SignalUpsert) ClearSourceExternalID() *SignalUpsert {
	u.SetNull(entsignal.FieldSourceExternalID)
	return u
}

// SetSourceURL sets the "source_url" field.
func (u *SignalUpsert) SetSourceURL(v string) *SignalUpsert {
	u.Set(entsignal.FieldSourceURL, v)
	return u
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SignalUpsert) UpdateSourceURL() *SignalUpsert {
	u.SetExcluded(entsignal.FieldSourceURL)
	return u
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *SignalUpsert) ClearSourceURL() *SignalUpsert {
	u.SetNull(entsignal.FieldSourceURL)
	return u
}

// SetDomainName sets the "domain_name" field.
func (u *SignalUpsert) SetDomainName(v string) *SignalUpsert {
	u.Set(entsignal.FieldDomainName, v)
	return u
}

// UpdateDomainName sets the "domain_name" field to the value that was provided on create.
func (u *SignalUpsert) UpdateDomainName() *SignalUpsert {
	u.SetExcluded(entsignal.FieldDomainName)
	return u
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (u *SignalUpsert) SetDomainSubdomain(v string) *SignalUpsert {
	u.Set(entsignal.FieldDomainSubdomain, v)
	return u
}

// UpdateDomainSubdomain sets the "domain_subdomain" field to the value that was provided on create.
func (u *SignalUpsert) UpdateDomainSubdomain() *SignalUpsert {
	u.SetExcluded(entsignal.FieldDomainSubdomain)
	return u
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (u *SignalUpsert) ClearDomainSubdomain() *SignalUpsert {
	u.SetNull(entsignal.FieldDomainSubdomain)
	return u
}

// SetDomainTeam sets the "domain_team" field.
func (u *SignalUpsert) SetDomainTeam(v string) *SignalUpsert {
	u.Set(entsignal.FieldDomainTeam, v)
	return u
}

// UpdateDomainTeam sets the "domain_team" field to the value that was provided on create.
func (u *SignalUpsert) UpdateDomainTeam() *SignalUpsert {
	u.SetExcluded(entsignal.FieldDomainTeam)
	return u
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (u *SignalUpsert) ClearDomainTeam() *SignalUpsert {
	u.SetNull(entsignal.FieldDomainTeam)
	return u
}

// SetSeverity sets the "severity" field.
func (u *SignalUpsert) SetSeverity(v string) *SignalUpsert {
	u.Set(entsignal.FieldSeverity, v)
	return u
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *SignalUpsert) UpdateSeverity() *SignalUpsert {
	u.SetExcluded(entsignal.FieldSeverity)
	return u
}

// SetSummary sets the "summary" field.
func (u *SignalUpsert) SetSummary(v string) *SignalUpsert {
	u.Set(entsignal.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *SignalUpsert) UpdateSummary() *SignalUpsert {
	u.SetExcluded(entsignal.FieldSummary)
	return u
}

// SetDescription sets the "description" field.
func (u *SignalUpsert) SetDescription(v string) *SignalUpsert {
	u.Set(entsignal.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SignalUpsert) UpdateDescription() *SignalUpsert {
	u.SetExcluded(entsignal.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SignalUpsert) ClearDescription() *SignalUpsert {
	u.SetNull(entsignal.FieldDescription)
	return u
}

// SetEntities sets the "entities" field.
func (u *SignalUpsert) SetEntities(v []common.Entity) *SignalUpsert {
	u.Set(entsignal.FieldEntities, v)
	return u
}

// UpdateEntities sets the "entities" field to the value that was provided on create.
func (u *SignalUpsert) UpdateEntities() *SignalUpsert {
	u.SetExcluded(entsignal.FieldEntities)
	return u
}

// ClearEntities clears the value of the "entities" field.
func (u *SignalUpsert) ClearEntities() *SignalUpsert {
	u.SetNull(entsignal.FieldEntities)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *SignalUpsert) SetObservedAt(v time.Time) *SignalUpsert {
	u.Set(entsignal.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *SignalUpsert) UpdateObservedAt() *SignalUpsert {
	u.SetExcluded(entsignal.FieldObservedAt)
	return u
}

// SetReceivedAt sets the "received_at" field.
func (u *SignalUpsert) SetReceivedAt(v time.Time) *SignalUpsert {
	u.Set(entsignal.FieldReceivedAt, v)
	return u
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *SignalUpsert) UpdateReceivedAt() *SignalUpsert {
	u.SetExcluded(entsignal.FieldReceivedAt)
	return u
}

// SetFingerprint sets the "fingerprint" field.
func (u *SignalUpsert) SetFingerprint(v string) *SignalUpsert {
	u.Set(entsignal.FieldFingerprint, v)
	return u
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *SignalUpsert) UpdateFingerprint() *SignalUpsert {
	u.SetExcluded(entsignal.FieldFingerprint)
	return u
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (u *SignalUpsert) ClearFingerprint() *SignalUpsert {
	u.SetNull(entsignal.FieldFingerprint)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *SignalUpsert) SetMetadata(v map[string]interface{}) *SignalUpsert {
	u.Set(entsignal.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SignalUpsert) UpdateMetadata() *SignalUpsert {
	u.SetExcluded(entsignal.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SignalUpsert) ClearMetadata() *SignalUpsert {
	u.SetNull(entsignal.FieldMetadata)
	return u
}

// SetDerived sets the "derived" field.
func (u *SignalUpsert) SetDerived(v *signal.DerivedMetrics) *SignalUpsert {
	u.Set(entsignal.FieldDerived, v)
	return u
}

// UpdateDerived sets the "derived" field to the value that was provided on create.
func (u *SignalUpsert) UpdateDerived() *SignalUpsert {
	u.SetExcluded(entsignal.FieldDerived)
	return u
}

// ClearDerived clears the value of the "derived" field.
func (u *SignalUpsert) ClearDerived() *SignalUpsert {
	u.SetNull(entsignal.FieldDerived)
	return u
}

// SetTags sets the "tags" field.
func (u *SignalUpsert) SetTags(v []common.Tag) *SignalUpsert {
	u.Set(entsignal.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *SignalUpsert) UpdateTags() *SignalUpsert {
	u.SetExcluded(entsignal.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *SignalUpsert) ClearTags() *SignalUpsert {
	u.SetNull(entsignal.FieldTags)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Signal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(entsignal.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SignalUpsertOne) UpdateNewValues() *SignalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(entsignal.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Signal.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SignalUpsertOne) Ignore() *SignalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignalUpsertOne) DoNothing() *SignalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignalCreate.OnConflict
// documentation for more info.
func (u *SignalUpsertOne) Update(set func(*SignalUpsert)) *SignalUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignalUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *SignalUpsertOne) SetType(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateType() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *SignalUpsertOne) SetStatus(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateStatus() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceType sets the "source_type" field.
func (u *SignalUpsertOne) SetSourceType(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateSourceType() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceName sets the "source_name" field.
func (u *SignalUpsertOne) SetSourceName(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceName(v)
	})
}

// UpdateSourceName sets the "source_name" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateSourceName() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceName()
	})
}

// SetSourceExternalID sets the "source_external_id" field.
func (u *SignalUpsertOne) SetSourceExternalID(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceExternalID(v)
	})
}

// UpdateSourceExternalID sets the "source_external_id" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateSourceExternalID() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceExternalID()
	})
}

// ClearSourceExternalID clears the value of the "source_external_id" field.
func (u *SignalUpsertOne) ClearSourceExternalID() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearSourceExternalID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *SignalUpsertOne) SetSourceURL(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateSourceURL() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *SignalUpsertOne) ClearSourceURL() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearSourceURL()
	})
}

// SetDomainName sets the "domain_name" field.
func (u *SignalUpsertOne) SetDomainName(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetDomainName(v)
	})
}

// UpdateDomainName sets the "domain_name" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateDomainName() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDomainName()
	})
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (u *SignalUpsertOne) SetDomainSubdomain(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetDomainSubdomain(v)
	})
}

// UpdateDomainSubdomain sets the "domain_subdomain" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateDomainSubdomain() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDomainSubdomain()
	})
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (u *SignalUpsertOne) ClearDomainSubdomain() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDomainSubdomain()
	})
}

// SetDomainTeam sets the "domain_team" field.
func (u *SignalUpsertOne) SetDomainTeam(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetDomainTeam(v)
	})
}

// UpdateDomainTeam sets the "domain_team" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateDomainTeam() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDomainTeam()
	})
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (u *SignalUpsertOne) ClearDomainTeam() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDomainTeam()
	})
}

// SetSeverity sets the "severity" field.
func (u *SignalUpsertOne) SetSeverity(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateSeverity() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSeverity()
	})
}

// SetSummary sets the "summary" field.
func (u *SignalUpsertOne) SetSummary(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateSummary() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSummary()
	})
}

// SetDescription sets the "description" field.
func (u *SignalUpsertOne) SetDescription(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateDescription() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SignalUpsertOne) ClearDescription() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDescription()
	})
}

// SetEntities sets the "entities" field.
func (u *SignalUpsertOne) SetEntities(v []common.Entity) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetEntities(v)
	})
}

// UpdateEntities sets the "entities" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateEntities() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateEntities()
	})
}

// ClearEntities clears the value of the "entities" field.
func (u *SignalUpsertOne) ClearEntities() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearEntities()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *SignalUpsertOne) SetObservedAt(v time.Time) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateObservedAt() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateObservedAt()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *SignalUpsertOne) SetReceivedAt(v time.Time) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateReceivedAt() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *SignalUpsertOne) SetFingerprint(v string) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateFingerprint() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateFingerprint()
	})
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (u *SignalUpsertOne) ClearFingerprint() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearFingerprint()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SignalUpsertOne) SetMetadata(v map[string]interface{}) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateMetadata() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SignalUpsertOne) ClearMetadata() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearMetadata()
	})
}

// SetDerived sets the "derived" field.
func (u *SignalUpsertOne) SetDerived(v *signal.DerivedMetrics) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetDerived(v)
	})
}

// UpdateDerived sets the "derived" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateDerived() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDerived()
	})
}

// ClearDerived clears the value of the "derived" field.
func (u *SignalUpsertOne) ClearDerived() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDerived()
	})
}

// SetTags sets the "tags" field.
func (u *SignalUpsertOne) SetTags(v []common.Tag) *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *SignalUpsertOne) UpdateTags() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *SignalUpsertOne) ClearTags() *SignalUpsertOne {
	return u.Update(func(s *SignalUpsert) {
		s.ClearTags()
	})
}

// Exec executes the query.
func (u *SignalUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SignalCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignalUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SignalUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SignalUpsertOne.ID is not supported by MySQL driver. Use SignalUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SignalUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SignalCreateBulk is the builder for creating many Signal entities in bulk.
type SignalCreateBulk struct {
	config
	err      error
	builders []*SignalCreate
	conflict []sql.ConflictOption
}

// Save creates the Signal entities in the database.
func (_c *SignalCreateBulk) Save(ctx context.Context) ([]*Signal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Signal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SignalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SignalCreateBulk) SaveX(ctx context.Context) []*Signal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SignalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SignalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Signal.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SignalUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *SignalCreateBulk) OnConflict(opts ...sql.ConflictOption) *SignalUpsertBulk {
	_c.conflict = opts
	return &SignalUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Signal.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SignalCreateBulk) OnConflictColumns(columns ...string) *SignalUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SignalUpsertBulk{
		create: _c,
	}
}

// SignalUpsertBulk is the builder for "upsert"-ing
// a bulk of Signal nodes.
type SignalUpsertBulk struct {
	create *SignalCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Signal.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(entsignal.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SignalUpsertBulk) UpdateNewValues() *SignalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(entsignal.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Signal.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SignalUpsertBulk) Ignore() *SignalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SignalUpsertBulk) DoNothing() *SignalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SignalCreateBulk.OnConflict
// documentation for more info.
func (u *SignalUpsertBulk) Update(set func(*SignalUpsert)) *SignalUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SignalUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *SignalUpsertBulk) SetType(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateType() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateType()
	})
}

// SetStatus sets the "status" field.
func (u *SignalUpsertBulk) SetStatus(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateStatus() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateStatus()
	})
}

// SetSourceType sets the "source_type" field.
func (u *SignalUpsertBulk) SetSourceType(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateSourceType() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceName sets the "source_name" field.
func (u *SignalUpsertBulk) SetSourceName(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceName(v)
	})
}

// UpdateSourceName sets the "source_name" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateSourceName() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceName()
	})
}

// SetSourceExternalID sets the "source_external_id" field.
func (u *SignalUpsertBulk) SetSourceExternalID(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceExternalID(v)
	})
}

// UpdateSourceExternalID sets the "source_external_id" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateSourceExternalID() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceExternalID()
	})
}

// ClearSourceExternalID clears the value of the "source_external_id" field.
func (u *SignalUpsertBulk) ClearSourceExternalID() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearSourceExternalID()
	})
}

// SetSourceURL sets the "source_url" field.
func (u *SignalUpsertBulk) SetSourceURL(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetSourceURL(v)
	})
}

// UpdateSourceURL sets the "source_url" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateSourceURL() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSourceURL()
	})
}

// ClearSourceURL clears the value of the "source_url" field.
func (u *SignalUpsertBulk) ClearSourceURL() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearSourceURL()
	})
}

// SetDomainName sets the "domain_name" field.
func (u *SignalUpsertBulk) SetDomainName(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetDomainName(v)
	})
}

// UpdateDomainName sets the "domain_name" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateDomainName() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDomainName()
	})
}

// SetDomainSubdomain sets the "domain_subdomain" field.
func (u *SignalUpsertBulk) SetDomainSubdomain(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetDomainSubdomain(v)
	})
}

// UpdateDomainSubdomain sets the "domain_subdomain" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateDomainSubdomain() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDomainSubdomain()
	})
}

// ClearDomainSubdomain clears the value of the "domain_subdomain" field.
func (u *SignalUpsertBulk) ClearDomainSubdomain() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDomainSubdomain()
	})
}

// SetDomainTeam sets the "domain_team" field.
func (u *SignalUpsertBulk) SetDomainTeam(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetDomainTeam(v)
	})
}

// UpdateDomainTeam sets the "domain_team" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateDomainTeam() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDomainTeam()
	})
}

// ClearDomainTeam clears the value of the "domain_team" field.
func (u *SignalUpsertBulk) ClearDomainTeam() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDomainTeam()
	})
}

// SetSeverity sets the "severity" field.
func (u *SignalUpsertBulk) SetSeverity(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetSeverity(v)
	})
}

// UpdateSeverity sets the "severity" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateSeverity() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSeverity()
	})
}

// SetSummary sets the "summary" field.
func (u *SignalUpsertBulk) SetSummary(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateSummary() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateSummary()
	})
}

// SetDescription sets the "description" field.
func (u *SignalUpsertBulk) SetDescription(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateDescription() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SignalUpsertBulk) ClearDescription() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDescription()
	})
}

// SetEntities sets the "entities" field.
func (u *SignalUpsertBulk) SetEntities(v []common.Entity) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetEntities(v)
	})
}

// UpdateEntities sets the "entities" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateEntities() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateEntities()
	})
}

// ClearEntities clears the value of the "entities" field.
func (u *SignalUpsertBulk) ClearEntities() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearEntities()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *SignalUpsertBulk) SetObservedAt(v time.Time) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateObservedAt() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateObservedAt()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *SignalUpsertBulk) SetReceivedAt(v time.Time) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateReceivedAt() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateReceivedAt()
	})
}

// SetFingerprint sets the "fingerprint" field.
func (u *SignalUpsertBulk) SetFingerprint(v string) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetFingerprint(v)
	})
}

// UpdateFingerprint sets the "fingerprint" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateFingerprint() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateFingerprint()
	})
}

// ClearFingerprint clears the value of the "fingerprint" field.
func (u *SignalUpsertBulk) ClearFingerprint() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearFingerprint()
	})
}

// SetMetadata sets the "metadata" field.
func (u *SignalUpsertBulk) SetMetadata(v map[string]interface{}) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateMetadata() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *SignalUpsertBulk) ClearMetadata() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearMetadata()
	})
}

// SetDerived sets the "derived" field.
func (u *SignalUpsertBulk) SetDerived(v *signal.DerivedMetrics) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetDerived(v)
	})
}

// UpdateDerived sets the "derived" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateDerived() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateDerived()
	})
}

// ClearDerived clears the value of the "derived" field.
func (u *SignalUpsertBulk) ClearDerived() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearDerived()
	})
}

// SetTags sets the "tags" field.
func (u *SignalUpsertBulk) SetTags(v []common.Tag) *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *SignalUpsertBulk) UpdateTags() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *SignalUpsertBulk) ClearTags() *SignalUpsertBulk {
	return u.Update(func(s *SignalUpsert) {
		s.ClearTags()
	})
}

// Exec executes the query.
func (u *SignalUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SignalCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SignalCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SignalUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
