// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	entsignal "github.com/plexusone/omnisignal/store/sqlite/ent/signal"
	"github.com/plexusone/signal-spec/pkg/common"
	"github.com/plexusone/signal-spec/pkg/signal"
)

// Signal is the model entity for the Signal schema.
type Signal struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType string `json:"source_type,omitempty"`
	// SourceName holds the value of the "source_name" field.
	SourceName string `json:"source_name,omitempty"`
	// SourceExternalID holds the value of the "source_external_id" field.
	SourceExternalID string `json:"source_external_id,omitempty"`
	// SourceURL holds the value of the "source_url" field.
	SourceURL string `json:"source_url,omitempty"`
	// DomainName holds the value of the "domain_name" field.
	DomainName string `json:"domain_name,omitempty"`
	// DomainSubdomain holds the value of the "domain_subdomain" field.
	DomainSubdomain string `json:"domain_subdomain,omitempty"`
	// DomainTeam holds the value of the "domain_team" field.
	DomainTeam string `json:"domain_team,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity string `json:"severity,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Entities holds the value of the "entities" field.
	Entities []common.Entity `json:"entities,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// Fingerprint holds the value of the "fingerprint" field.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Derived holds the value of the "derived" field.
	Derived *signal.DerivedMetrics `json:"derived,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags         []common.Tag `json:"tags,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Signal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entsignal.FieldEntities, entsignal.FieldMetadata, entsignal.FieldDerived, entsignal.FieldTags:
			values[i] = new([]byte)
		case entsignal.FieldID, entsignal.FieldType, entsignal.FieldStatus, entsignal.FieldSourceType, entsignal.FieldSourceName, entsignal.FieldSourceExternalID, entsignal.FieldSourceURL, entsignal.FieldDomainName, entsignal.FieldDomainSubdomain, entsignal.FieldDomainTeam, entsignal.FieldSeverity, entsignal.FieldSummary, entsignal.FieldDescription, entsignal.FieldFingerprint:
			values[i] = new(sql.NullString)
		case entsignal.FieldObservedAt, entsignal.FieldReceivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Signal fields.
func (_m *Signal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entsignal.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case entsignal.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case entsignal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case entsignal.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = value.String
			}
		case entsignal.FieldSourceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_name", values[i])
			} else if value.Valid {
				_m.SourceName = value.String
			}
		case entsignal.FieldSourceExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_external_id", values[i])
			} else if value.Valid {
				_m.SourceExternalID = value.String
			}
		case entsignal.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = value.String
			}
		case entsignal.FieldDomainName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_name", values[i])
			} else if value.Valid {
				_m.DomainName = value.String
			}
		case entsignal.FieldDomainSubdomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_subdomain", values[i])
			} else if value.Valid {
				_m.DomainSubdomain = value.String
			}
		case entsignal.FieldDomainTeam:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain_team", values[i])
			} else if value.Valid {
				_m.DomainTeam = value.String
			}
		case entsignal.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case entsignal.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case entsignal.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case entsignal.FieldEntities:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field entities", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Entities); err != nil {
					return fmt.Errorf("unmarshal field entities: %w", err)
				}
			}
		case entsignal.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				_m.ObservedAt = value.Time
			}
		case entsignal.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case entsignal.FieldFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fingerprint", values[i])
			} else if value.Valid {
				_m.Fingerprint = new(string)
				*_m.Fingerprint = value.String
			}
		case entsignal.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case entsignal.FieldDerived:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field derived", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Derived); err != nil {
					return fmt.Errorf("unmarshal field derived: %w", err)
				}
			}
		case entsignal.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Signal.
// This includes values selected through modifiers, order, etc.
func (_m *Signal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Signal.
// Note that you need to call Signal.Unwrap() before calling this method if this Signal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Signal) Update() *SignalUpdateOne {
	return NewSignalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Signal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Signal) Unwrap() *Signal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Signal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Signal) String() string {
	var builder strings.Builder
	builder.WriteString("Signal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source_type=")
	builder.WriteString(_m.SourceType)
	builder.WriteString(", ")
	builder.WriteString("source_name=")
	builder.WriteString(_m.SourceName)
	builder.WriteString(", ")
	builder.WriteString("source_external_id=")
	builder.WriteString(_m.SourceExternalID)
	builder.WriteString(", ")
	builder.WriteString("source_url=")
	builder.WriteString(_m.SourceURL)
	builder.WriteString(", ")
	builder.WriteString("domain_name=")
	builder.WriteString(_m.DomainName)
	builder.WriteString(", ")
	builder.WriteString("domain_subdomain=")
	builder.WriteString(_m.DomainSubdomain)
	builder.WriteString(", ")
	builder.WriteString("domain_team=")
	builder.WriteString(_m.DomainTeam)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("entities=")
	builder.WriteString(fmt.Sprintf("%v", _m.Entities))
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(_m.ObservedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.Fingerprint; v != nil {
		builder.WriteString("fingerprint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("derived=")
	builder.WriteString(fmt.Sprintf("%v", _m.Derived))
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteByte(')')
	return builder.String()
}

// Signals is a parsable slice of Signal.
type Signals []*Signal
