// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RootCause is the predicate function for rootcause builders.
type RootCause func(*sql.Selector)

// Signal is the predicate function for entsignal builders.
type Signal func(*sql.Selector)

// SignalRootCauseLink is the predicate function for signalrootcauselink builders.
type SignalRootCauseLink func(*sql.Selector)
