// Code generated by ent, DO NOT EDIT.

package rootcause

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the rootcause type in the database.
	Label = "root_cause"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDomainName holds the string denoting the domain_name field in the database.
	FieldDomainName = "domain_name"
	// FieldDomainSubdomain holds the string denoting the domain_subdomain field in the database.
	FieldDomainSubdomain = "domain_subdomain"
	// FieldDomainTeam holds the string denoting the domain_team field in the database.
	FieldDomainTeam = "domain_team"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldSymptomPatterns holds the string denoting the symptom_patterns field in the database.
	FieldSymptomPatterns = "symptom_patterns"
	// FieldImpactSignalCount holds the string denoting the impact_signal_count field in the database.
	FieldImpactSignalCount = "impact_signal_count"
	// FieldImpactAffectedCustomers holds the string denoting the impact_affected_customers field in the database.
	FieldImpactAffectedCustomers = "impact_affected_customers"
	// FieldImpactAffectedEntities holds the string denoting the impact_affected_entities field in the database.
	FieldImpactAffectedEntities = "impact_affected_entities"
	// FieldImpactEscalationRate holds the string denoting the impact_escalation_rate field in the database.
	FieldImpactEscalationRate = "impact_escalation_rate"
	// FieldImpactEstimatedRevenueLoss holds the string denoting the impact_estimated_revenue_loss field in the database.
	FieldImpactEstimatedRevenueLoss = "impact_estimated_revenue_loss"
	// FieldTrendDirection holds the string denoting the trend_direction field in the database.
	FieldTrendDirection = "trend_direction"
	// FieldTrendVelocity holds the string denoting the trend_velocity field in the database.
	FieldTrendVelocity = "trend_velocity"
	// FieldTrendPeriodStart holds the string denoting the trend_period_start field in the database.
	FieldTrendPeriodStart = "trend_period_start"
	// FieldTrendPeriodEnd holds the string denoting the trend_period_end field in the database.
	FieldTrendPeriodEnd = "trend_period_end"
	// FieldPriorityScore holds the string denoting the priority_score field in the database.
	FieldPriorityScore = "priority_score"
	// FieldFirstSeen holds the string denoting the first_seen field in the database.
	FieldFirstSeen = "first_seen"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldOwnerTeam holds the string denoting the owner_team field in the database.
	FieldOwnerTeam = "owner_team"
	// FieldRemediationID holds the string denoting the remediation_id field in the database.
	FieldRemediationID = "remediation_id"
	// FieldRecurrenceCount holds the string denoting the recurrence_count field in the database.
	FieldRecurrenceCount = "recurrence_count"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// Table holds the table name of the rootcause in the database.
	Table = "root_causes"
)

// Columns holds all SQL columns for rootcause fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldDescription,
	FieldStatus,
	FieldDomainName,
	FieldDomainSubdomain,
	FieldDomainTeam,
	FieldSeverity,
	FieldSymptomPatterns,
	FieldImpactSignalCount,
	FieldImpactAffectedCustomers,
	FieldImpactAffectedEntities,
	FieldImpactEscalationRate,
	FieldImpactEstimatedRevenueLoss,
	FieldTrendDirection,
	FieldTrendVelocity,
	FieldTrendPeriodStart,
	FieldTrendPeriodEnd,
	FieldPriorityScore,
	FieldFirstSeen,
	FieldLastSeen,
	FieldOwnerTeam,
	FieldRemediationID,
	FieldRecurrenceCount,
	FieldMetadata,
	FieldTags,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultImpactSignalCount holds the default value on creation for the "impact_signal_count" field.
	DefaultImpactSignalCount int
	// DefaultImpactAffectedCustomers holds the default value on creation for the "impact_affected_customers" field.
	DefaultImpactAffectedCustomers int
	// DefaultImpactEscalationRate holds the default value on creation for the "impact_escalation_rate" field.
	DefaultImpactEscalationRate float64
	// DefaultImpactEstimatedRevenueLoss holds the default value on creation for the "impact_estimated_revenue_loss" field.
	DefaultImpactEstimatedRevenueLoss float64
	// DefaultTrendVelocity holds the default value on creation for the "trend_velocity" field.
	DefaultTrendVelocity float64
	// DefaultPriorityScore holds the default value on creation for the "priority_score" field.
	DefaultPriorityScore int
	// DefaultRecurrenceCount holds the default value on creation for the "recurrence_count" field.
	DefaultRecurrenceCount int
)

// OrderOption defines the ordering options for the RootCause queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDomainName orders the results by the domain_name field.
func ByDomainName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainName, opts...).ToFunc()
}

// ByDomainSubdomain orders the results by the domain_subdomain field.
func ByDomainSubdomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainSubdomain, opts...).ToFunc()
}

// ByDomainTeam orders the results by the domain_team field.
func ByDomainTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainTeam, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByImpactSignalCount orders the results by the impact_signal_count field.
func ByImpactSignalCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImpactSignalCount, opts...).ToFunc()
}

// ByImpactAffectedCustomers orders the results by the impact_affected_customers field.
func ByImpactAffectedCustomers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImpactAffectedCustomers, opts...).ToFunc()
}

// ByImpactEscalationRate orders the results by the impact_escalation_rate field.
func ByImpactEscalationRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImpactEscalationRate, opts...).ToFunc()
}

// ByImpactEstimatedRevenueLoss orders the results by the impact_estimated_revenue_loss field.
func ByImpactEstimatedRevenueLoss(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImpactEstimatedRevenueLoss, opts...).ToFunc()
}

// ByTrendDirection orders the results by the trend_direction field.
func ByTrendDirection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrendDirection, opts...).ToFunc()
}

// ByTrendVelocity orders the results by the trend_velocity field.
func ByTrendVelocity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrendVelocity, opts...).ToFunc()
}

// ByTrendPeriodStart orders the results by the trend_period_start field.
func ByTrendPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrendPeriodStart, opts...).ToFunc()
}

// ByTrendPeriodEnd orders the results by the trend_period_end field.
func ByTrendPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrendPeriodEnd, opts...).ToFunc()
}

// ByPriorityScore orders the results by the priority_score field.
func ByPriorityScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriorityScore, opts...).ToFunc()
}

// ByFirstSeen orders the results by the first_seen field.
func ByFirstSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeen, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByOwnerTeam orders the results by the owner_team field.
func ByOwnerTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerTeam, opts...).ToFunc()
}

// ByRemediationID orders the results by the remediation_id field.
func ByRemediationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemediationID, opts...).ToFunc()
}

// ByRecurrenceCount orders the results by the recurrence_count field.
func ByRecurrenceCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecurrenceCount, opts...).ToFunc()
}
