// Code generated by ent, DO NOT EDIT.

package rootcause

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnisignal/store/sqlite/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldStatus, v))
}

// DomainName applies equality check predicate on the "domain_name" field. It's identical to DomainNameEQ.
func DomainName(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDomainName, v))
}

// DomainSubdomain applies equality check predicate on the "domain_subdomain" field. It's identical to DomainSubdomainEQ.
func DomainSubdomain(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDomainSubdomain, v))
}

// DomainTeam applies equality check predicate on the "domain_team" field. It's identical to DomainTeamEQ.
func DomainTeam(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDomainTeam, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldSeverity, v))
}

// ImpactSignalCount applies equality check predicate on the "impact_signal_count" field. It's identical to ImpactSignalCountEQ.
func ImpactSignalCount(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactSignalCount, v))
}

// ImpactAffectedCustomers applies equality check predicate on the "impact_affected_customers" field. It's identical to ImpactAffectedCustomersEQ.
func ImpactAffectedCustomers(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactAffectedCustomers, v))
}

// ImpactEscalationRate applies equality check predicate on the "impact_escalation_rate" field. It's identical to ImpactEscalationRateEQ.
func ImpactEscalationRate(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactEscalationRate, v))
}

// ImpactEstimatedRevenueLoss applies equality check predicate on the "impact_estimated_revenue_loss" field. It's identical to ImpactEstimatedRevenueLossEQ.
func ImpactEstimatedRevenueLoss(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactEstimatedRevenueLoss, v))
}

// TrendDirection applies equality check predicate on the "trend_direction" field. It's identical to TrendDirectionEQ.
func TrendDirection(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendDirection, v))
}

// TrendVelocity applies equality check predicate on the "trend_velocity" field. It's identical to TrendVelocityEQ.
func TrendVelocity(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendVelocity, v))
}

// TrendPeriodStart applies equality check predicate on the "trend_period_start" field. It's identical to TrendPeriodStartEQ.
func TrendPeriodStart(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendPeriodStart, v))
}

// TrendPeriodEnd applies equality check predicate on the "trend_period_end" field. It's identical to TrendPeriodEndEQ.
func TrendPeriodEnd(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendPeriodEnd, v))
}

// PriorityScore applies equality check predicate on the "priority_score" field. It's identical to PriorityScoreEQ.
func PriorityScore(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldPriorityScore, v))
}

// FirstSeen applies equality check predicate on the "first_seen" field. It's identical to FirstSeenEQ.
func FirstSeen(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldFirstSeen, v))
}

// LastSeen applies equality check predicate on the "last_seen" field. It's identical to LastSeenEQ.
func LastSeen(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldLastSeen, v))
}

// OwnerTeam applies equality check predicate on the "owner_team" field. It's identical to OwnerTeamEQ.
func OwnerTeam(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldOwnerTeam, v))
}

// RemediationID applies equality check predicate on the "remediation_id" field. It's identical to RemediationIDEQ.
func RemediationID(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldRemediationID, v))
}

// RecurrenceCount applies equality check predicate on the "recurrence_count" field. It's identical to RecurrenceCountEQ.
func RecurrenceCount(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldRecurrenceCount, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldStatus, v))
}

// DomainNameEQ applies the EQ predicate on the "domain_name" field.
func DomainNameEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDomainName, v))
}

// DomainNameNEQ applies the NEQ predicate on the "domain_name" field.
func DomainNameNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldDomainName, v))
}

// DomainNameIn applies the In predicate on the "domain_name" field.
func DomainNameIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldDomainName, vs...))
}

// DomainNameNotIn applies the NotIn predicate on the "domain_name" field.
func DomainNameNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldDomainName, vs...))
}

// DomainNameGT applies the GT predicate on the "domain_name" field.
func DomainNameGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldDomainName, v))
}

// DomainNameGTE applies the GTE predicate on the "domain_name" field.
func DomainNameGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldDomainName, v))
}

// DomainNameLT applies the LT predicate on the "domain_name" field.
func DomainNameLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldDomainName, v))
}

// DomainNameLTE applies the LTE predicate on the "domain_name" field.
func DomainNameLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldDomainName, v))
}

// DomainNameContains applies the Contains predicate on the "domain_name" field.
func DomainNameContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldDomainName, v))
}

// DomainNameHasPrefix applies the HasPrefix predicate on the "domain_name" field.
func DomainNameHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldDomainName, v))
}

// DomainNameHasSuffix applies the HasSuffix predicate on the "domain_name" field.
func DomainNameHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldDomainName, v))
}

// DomainNameEqualFold applies the EqualFold predicate on the "domain_name" field.
func DomainNameEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldDomainName, v))
}

// DomainNameContainsFold applies the ContainsFold predicate on the "domain_name" field.
func DomainNameContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldDomainName, v))
}

// DomainSubdomainEQ applies the EQ predicate on the "domain_subdomain" field.
func DomainSubdomainEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDomainSubdomain, v))
}

// DomainSubdomainNEQ applies the NEQ predicate on the "domain_subdomain" field.
func DomainSubdomainNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldDomainSubdomain, v))
}

// DomainSubdomainIn applies the In predicate on the "domain_subdomain" field.
func DomainSubdomainIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldDomainSubdomain, vs...))
}

// DomainSubdomainNotIn applies the NotIn predicate on the "domain_subdomain" field.
func DomainSubdomainNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldDomainSubdomain, vs...))
}

// DomainSubdomainGT applies the GT predicate on the "domain_subdomain" field.
func DomainSubdomainGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldDomainSubdomain, v))
}

// DomainSubdomainGTE applies the GTE predicate on the "domain_subdomain" field.
func DomainSubdomainGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldDomainSubdomain, v))
}

// DomainSubdomainLT applies the LT predicate on the "domain_subdomain" field.
func DomainSubdomainLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldDomainSubdomain, v))
}

// DomainSubdomainLTE applies the LTE predicate on the "domain_subdomain" field.
func DomainSubdomainLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldDomainSubdomain, v))
}

// DomainSubdomainContains applies the Contains predicate on the "domain_subdomain" field.
func DomainSubdomainContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldDomainSubdomain, v))
}

// DomainSubdomainHasPrefix applies the HasPrefix predicate on the "domain_subdomain" field.
func DomainSubdomainHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldDomainSubdomain, v))
}

// DomainSubdomainHasSuffix applies the HasSuffix predicate on the "domain_subdomain" field.
func DomainSubdomainHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldDomainSubdomain, v))
}

// DomainSubdomainIsNil applies the IsNil predicate on the "domain_subdomain" field.
func DomainSubdomainIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldDomainSubdomain))
}

// DomainSubdomainNotNil applies the NotNil predicate on the "domain_subdomain" field.
func DomainSubdomainNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldDomainSubdomain))
}

// DomainSubdomainEqualFold applies the EqualFold predicate on the "domain_subdomain" field.
func DomainSubdomainEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldDomainSubdomain, v))
}

// DomainSubdomainContainsFold applies the ContainsFold predicate on the "domain_subdomain" field.
func DomainSubdomainContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldDomainSubdomain, v))
}

// DomainTeamEQ applies the EQ predicate on the "domain_team" field.
func DomainTeamEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldDomainTeam, v))
}

// DomainTeamNEQ applies the NEQ predicate on the "domain_team" field.
func DomainTeamNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldDomainTeam, v))
}

// DomainTeamIn applies the In predicate on the "domain_team" field.
func DomainTeamIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldDomainTeam, vs...))
}

// DomainTeamNotIn applies the NotIn predicate on the "domain_team" field.
func DomainTeamNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldDomainTeam, vs...))
}

// DomainTeamGT applies the GT predicate on the "domain_team" field.
func DomainTeamGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldDomainTeam, v))
}

// DomainTeamGTE applies the GTE predicate on the "domain_team" field.
func DomainTeamGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldDomainTeam, v))
}

// DomainTeamLT applies the LT predicate on the "domain_team" field.
func DomainTeamLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldDomainTeam, v))
}

// DomainTeamLTE applies the LTE predicate on the "domain_team" field.
func DomainTeamLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldDomainTeam, v))
}

// DomainTeamContains applies the Contains predicate on the "domain_team" field.
func DomainTeamContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldDomainTeam, v))
}

// DomainTeamHasPrefix applies the HasPrefix predicate on the "domain_team" field.
func DomainTeamHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldDomainTeam, v))
}

// DomainTeamHasSuffix applies the HasSuffix predicate on the "domain_team" field.
func DomainTeamHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldDomainTeam, v))
}

// DomainTeamIsNil applies the IsNil predicate on the "domain_team" field.
func DomainTeamIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldDomainTeam))
}

// DomainTeamNotNil applies the NotNil predicate on the "domain_team" field.
func DomainTeamNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldDomainTeam))
}

// DomainTeamEqualFold applies the EqualFold predicate on the "domain_team" field.
func DomainTeamEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldDomainTeam, v))
}

// DomainTeamContainsFold applies the ContainsFold predicate on the "domain_team" field.
func DomainTeamContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldDomainTeam, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldSeverity, v))
}

// SymptomPatternsIsNil applies the IsNil predicate on the "symptom_patterns" field.
func SymptomPatternsIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldSymptomPatterns))
}

// SymptomPatternsNotNil applies the NotNil predicate on the "symptom_patterns" field.
func SymptomPatternsNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldSymptomPatterns))
}

// ImpactSignalCountEQ applies the EQ predicate on the "impact_signal_count" field.
func ImpactSignalCountEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactSignalCount, v))
}

// ImpactSignalCountNEQ applies the NEQ predicate on the "impact_signal_count" field.
func ImpactSignalCountNEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldImpactSignalCount, v))
}

// ImpactSignalCountIn applies the In predicate on the "impact_signal_count" field.
func ImpactSignalCountIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldImpactSignalCount, vs...))
}

// ImpactSignalCountNotIn applies the NotIn predicate on the "impact_signal_count" field.
func ImpactSignalCountNotIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldImpactSignalCount, vs...))
}

// ImpactSignalCountGT applies the GT predicate on the "impact_signal_count" field.
func ImpactSignalCountGT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldImpactSignalCount, v))
}

// ImpactSignalCountGTE applies the GTE predicate on the "impact_signal_count" field.
func ImpactSignalCountGTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldImpactSignalCount, v))
}

// ImpactSignalCountLT applies the LT predicate on the "impact_signal_count" field.
func ImpactSignalCountLT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldImpactSignalCount, v))
}

// ImpactSignalCountLTE applies the LTE predicate on the "impact_signal_count" field.
func ImpactSignalCountLTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldImpactSignalCount, v))
}

// ImpactAffectedCustomersEQ applies the EQ predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactAffectedCustomers, v))
}

// ImpactAffectedCustomersNEQ applies the NEQ predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersNEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldImpactAffectedCustomers, v))
}

// ImpactAffectedCustomersIn applies the In predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldImpactAffectedCustomers, vs...))
}

// ImpactAffectedCustomersNotIn applies the NotIn predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersNotIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldImpactAffectedCustomers, vs...))
}

// ImpactAffectedCustomersGT applies the GT predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersGT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldImpactAffectedCustomers, v))
}

// ImpactAffectedCustomersGTE applies the GTE predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersGTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldImpactAffectedCustomers, v))
}

// ImpactAffectedCustomersLT applies the LT predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersLT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldImpactAffectedCustomers, v))
}

// ImpactAffectedCustomersLTE applies the LTE predicate on the "impact_affected_customers" field.
func ImpactAffectedCustomersLTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldImpactAffectedCustomers, v))
}

// ImpactAffectedEntitiesIsNil applies the IsNil predicate on the "impact_affected_entities" field.
func ImpactAffectedEntitiesIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldImpactAffectedEntities))
}

// ImpactAffectedEntitiesNotNil applies the NotNil predicate on the "impact_affected_entities" field.
func ImpactAffectedEntitiesNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldImpactAffectedEntities))
}

// ImpactEscalationRateEQ applies the EQ predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateEQ(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactEscalationRate, v))
}

// ImpactEscalationRateNEQ applies the NEQ predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateNEQ(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldImpactEscalationRate, v))
}

// ImpactEscalationRateIn applies the In predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateIn(vs ...float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldImpactEscalationRate, vs...))
}

// ImpactEscalationRateNotIn applies the NotIn predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateNotIn(vs ...float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldImpactEscalationRate, vs...))
}

// ImpactEscalationRateGT applies the GT predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateGT(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldImpactEscalationRate, v))
}

// ImpactEscalationRateGTE applies the GTE predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateGTE(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldImpactEscalationRate, v))
}

// ImpactEscalationRateLT applies the LT predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateLT(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldImpactEscalationRate, v))
}

// ImpactEscalationRateLTE applies the LTE predicate on the "impact_escalation_rate" field.
func ImpactEscalationRateLTE(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldImpactEscalationRate, v))
}

// ImpactEstimatedRevenueLossEQ applies the EQ predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossEQ(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldImpactEstimatedRevenueLoss, v))
}

// ImpactEstimatedRevenueLossNEQ applies the NEQ predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossNEQ(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldImpactEstimatedRevenueLoss, v))
}

// ImpactEstimatedRevenueLossIn applies the In predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossIn(vs ...float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldImpactEstimatedRevenueLoss, vs...))
}

// ImpactEstimatedRevenueLossNotIn applies the NotIn predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossNotIn(vs ...float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldImpactEstimatedRevenueLoss, vs...))
}

// ImpactEstimatedRevenueLossGT applies the GT predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossGT(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldImpactEstimatedRevenueLoss, v))
}

// ImpactEstimatedRevenueLossGTE applies the GTE predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossGTE(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldImpactEstimatedRevenueLoss, v))
}

// ImpactEstimatedRevenueLossLT applies the LT predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossLT(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldImpactEstimatedRevenueLoss, v))
}

// ImpactEstimatedRevenueLossLTE applies the LTE predicate on the "impact_estimated_revenue_loss" field.
func ImpactEstimatedRevenueLossLTE(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldImpactEstimatedRevenueLoss, v))
}

// TrendDirectionEQ applies the EQ predicate on the "trend_direction" field.
func TrendDirectionEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendDirection, v))
}

// TrendDirectionNEQ applies the NEQ predicate on the "trend_direction" field.
func TrendDirectionNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldTrendDirection, v))
}

// TrendDirectionIn applies the In predicate on the "trend_direction" field.
func TrendDirectionIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldTrendDirection, vs...))
}

// TrendDirectionNotIn applies the NotIn predicate on the "trend_direction" field.
func TrendDirectionNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldTrendDirection, vs...))
}

// TrendDirectionGT applies the GT predicate on the "trend_direction" field.
func TrendDirectionGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldTrendDirection, v))
}

// TrendDirectionGTE applies the GTE predicate on the "trend_direction" field.
func TrendDirectionGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldTrendDirection, v))
}

// TrendDirectionLT applies the LT predicate on the "trend_direction" field.
func TrendDirectionLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldTrendDirection, v))
}

// TrendDirectionLTE applies the LTE predicate on the "trend_direction" field.
func TrendDirectionLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldTrendDirection, v))
}

// TrendDirectionContains applies the Contains predicate on the "trend_direction" field.
func TrendDirectionContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldTrendDirection, v))
}

// TrendDirectionHasPrefix applies the HasPrefix predicate on the "trend_direction" field.
func TrendDirectionHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldTrendDirection, v))
}

// TrendDirectionHasSuffix applies the HasSuffix predicate on the "trend_direction" field.
func TrendDirectionHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldTrendDirection, v))
}

// TrendDirectionIsNil applies the IsNil predicate on the "trend_direction" field.
func TrendDirectionIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldTrendDirection))
}

// TrendDirectionNotNil applies the NotNil predicate on the "trend_direction" field.
func TrendDirectionNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldTrendDirection))
}

// TrendDirectionEqualFold applies the EqualFold predicate on the "trend_direction" field.
func TrendDirectionEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldTrendDirection, v))
}

// TrendDirectionContainsFold applies the ContainsFold predicate on the "trend_direction" field.
func TrendDirectionContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldTrendDirection, v))
}

// TrendVelocityEQ applies the EQ predicate on the "trend_velocity" field.
func TrendVelocityEQ(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendVelocity, v))
}

// TrendVelocityNEQ applies the NEQ predicate on the "trend_velocity" field.
func TrendVelocityNEQ(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldTrendVelocity, v))
}

// TrendVelocityIn applies the In predicate on the "trend_velocity" field.
func TrendVelocityIn(vs ...float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldTrendVelocity, vs...))
}

// TrendVelocityNotIn applies the NotIn predicate on the "trend_velocity" field.
func TrendVelocityNotIn(vs ...float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldTrendVelocity, vs...))
}

// TrendVelocityGT applies the GT predicate on the "trend_velocity" field.
func TrendVelocityGT(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldTrendVelocity, v))
}

// TrendVelocityGTE applies the GTE predicate on the "trend_velocity" field.
func TrendVelocityGTE(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldTrendVelocity, v))
}

// TrendVelocityLT applies the LT predicate on the "trend_velocity" field.
func TrendVelocityLT(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldTrendVelocity, v))
}

// TrendVelocityLTE applies the LTE predicate on the "trend_velocity" field.
func TrendVelocityLTE(v float64) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldTrendVelocity, v))
}

// TrendPeriodStartEQ applies the EQ predicate on the "trend_period_start" field.
func TrendPeriodStartEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendPeriodStart, v))
}

// TrendPeriodStartNEQ applies the NEQ predicate on the "trend_period_start" field.
func TrendPeriodStartNEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldTrendPeriodStart, v))
}

// TrendPeriodStartIn applies the In predicate on the "trend_period_start" field.
func TrendPeriodStartIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldTrendPeriodStart, vs...))
}

// TrendPeriodStartNotIn applies the NotIn predicate on the "trend_period_start" field.
func TrendPeriodStartNotIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldTrendPeriodStart, vs...))
}

// TrendPeriodStartGT applies the GT predicate on the "trend_period_start" field.
func TrendPeriodStartGT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldTrendPeriodStart, v))
}

// TrendPeriodStartGTE applies the GTE predicate on the "trend_period_start" field.
func TrendPeriodStartGTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldTrendPeriodStart, v))
}

// TrendPeriodStartLT applies the LT predicate on the "trend_period_start" field.
func TrendPeriodStartLT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldTrendPeriodStart, v))
}

// TrendPeriodStartLTE applies the LTE predicate on the "trend_period_start" field.
func TrendPeriodStartLTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldTrendPeriodStart, v))
}

// TrendPeriodStartIsNil applies the IsNil predicate on the "trend_period_start" field.
func TrendPeriodStartIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldTrendPeriodStart))
}

// TrendPeriodStartNotNil applies the NotNil predicate on the "trend_period_start" field.
func TrendPeriodStartNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldTrendPeriodStart))
}

// TrendPeriodEndEQ applies the EQ predicate on the "trend_period_end" field.
func TrendPeriodEndEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldTrendPeriodEnd, v))
}

// TrendPeriodEndNEQ applies the NEQ predicate on the "trend_period_end" field.
func TrendPeriodEndNEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldTrendPeriodEnd, v))
}

// TrendPeriodEndIn applies the In predicate on the "trend_period_end" field.
func TrendPeriodEndIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldTrendPeriodEnd, vs...))
}

// TrendPeriodEndNotIn applies the NotIn predicate on the "trend_period_end" field.
func TrendPeriodEndNotIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldTrendPeriodEnd, vs...))
}

// TrendPeriodEndGT applies the GT predicate on the "trend_period_end" field.
func TrendPeriodEndGT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldTrendPeriodEnd, v))
}

// TrendPeriodEndGTE applies the GTE predicate on the "trend_period_end" field.
func TrendPeriodEndGTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldTrendPeriodEnd, v))
}

// TrendPeriodEndLT applies the LT predicate on the "trend_period_end" field.
func TrendPeriodEndLT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldTrendPeriodEnd, v))
}

// TrendPeriodEndLTE applies the LTE predicate on the "trend_period_end" field.
func TrendPeriodEndLTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldTrendPeriodEnd, v))
}

// TrendPeriodEndIsNil applies the IsNil predicate on the "trend_period_end" field.
func TrendPeriodEndIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldTrendPeriodEnd))
}

// TrendPeriodEndNotNil applies the NotNil predicate on the "trend_period_end" field.
func TrendPeriodEndNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldTrendPeriodEnd))
}

// PriorityScoreEQ applies the EQ predicate on the "priority_score" field.
func PriorityScoreEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldPriorityScore, v))
}

// PriorityScoreNEQ applies the NEQ predicate on the "priority_score" field.
func PriorityScoreNEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldPriorityScore, v))
}

// PriorityScoreIn applies the In predicate on the "priority_score" field.
func PriorityScoreIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldPriorityScore, vs...))
}

// PriorityScoreNotIn applies the NotIn predicate on the "priority_score" field.
func PriorityScoreNotIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldPriorityScore, vs...))
}

// PriorityScoreGT applies the GT predicate on the "priority_score" field.
func PriorityScoreGT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldPriorityScore, v))
}

// PriorityScoreGTE applies the GTE predicate on the "priority_score" field.
func PriorityScoreGTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldPriorityScore, v))
}

// PriorityScoreLT applies the LT predicate on the "priority_score" field.
func PriorityScoreLT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldPriorityScore, v))
}

// PriorityScoreLTE applies the LTE predicate on the "priority_score" field.
func PriorityScoreLTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldPriorityScore, v))
}

// FirstSeenEQ applies the EQ predicate on the "first_seen" field.
func FirstSeenEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldFirstSeen, v))
}

// FirstSeenNEQ applies the NEQ predicate on the "first_seen" field.
func FirstSeenNEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldFirstSeen, v))
}

// FirstSeenIn applies the In predicate on the "first_seen" field.
func FirstSeenIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldFirstSeen, vs...))
}

// FirstSeenNotIn applies the NotIn predicate on the "first_seen" field.
func FirstSeenNotIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldFirstSeen, vs...))
}

// FirstSeenGT applies the GT predicate on the "first_seen" field.
func FirstSeenGT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldFirstSeen, v))
}

// FirstSeenGTE applies the GTE predicate on the "first_seen" field.
func FirstSeenGTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldFirstSeen, v))
}

// FirstSeenLT applies the LT predicate on the "first_seen" field.
func FirstSeenLT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldFirstSeen, v))
}

// FirstSeenLTE applies the LTE predicate on the "first_seen" field.
func FirstSeenLTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldFirstSeen, v))
}

// LastSeenEQ applies the EQ predicate on the "last_seen" field.
func LastSeenEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldLastSeen, v))
}

// LastSeenNEQ applies the NEQ predicate on the "last_seen" field.
func LastSeenNEQ(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldLastSeen, v))
}

// LastSeenIn applies the In predicate on the "last_seen" field.
func LastSeenIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldLastSeen, vs...))
}

// LastSeenNotIn applies the NotIn predicate on the "last_seen" field.
func LastSeenNotIn(vs ...time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldLastSeen, vs...))
}

// LastSeenGT applies the GT predicate on the "last_seen" field.
func LastSeenGT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldLastSeen, v))
}

// LastSeenGTE applies the GTE predicate on the "last_seen" field.
func LastSeenGTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldLastSeen, v))
}

// LastSeenLT applies the LT predicate on the "last_seen" field.
func LastSeenLT(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldLastSeen, v))
}

// LastSeenLTE applies the LTE predicate on the "last_seen" field.
func LastSeenLTE(v time.Time) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldLastSeen, v))
}

// OwnerTeamEQ applies the EQ predicate on the "owner_team" field.
func OwnerTeamEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldOwnerTeam, v))
}

// OwnerTeamNEQ applies the NEQ predicate on the "owner_team" field.
func OwnerTeamNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldOwnerTeam, v))
}

// OwnerTeamIn applies the In predicate on the "owner_team" field.
func OwnerTeamIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldOwnerTeam, vs...))
}

// OwnerTeamNotIn applies the NotIn predicate on the "owner_team" field.
func OwnerTeamNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldOwnerTeam, vs...))
}

// OwnerTeamGT applies the GT predicate on the "owner_team" field.
func OwnerTeamGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldOwnerTeam, v))
}

// OwnerTeamGTE applies the GTE predicate on the "owner_team" field.
func OwnerTeamGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldOwnerTeam, v))
}

// OwnerTeamLT applies the LT predicate on the "owner_team" field.
func OwnerTeamLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldOwnerTeam, v))
}

// OwnerTeamLTE applies the LTE predicate on the "owner_team" field.
func OwnerTeamLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldOwnerTeam, v))
}

// OwnerTeamContains applies the Contains predicate on the "owner_team" field.
func OwnerTeamContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldOwnerTeam, v))
}

// OwnerTeamHasPrefix applies the HasPrefix predicate on the "owner_team" field.
func OwnerTeamHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldOwnerTeam, v))
}

// OwnerTeamHasSuffix applies the HasSuffix predicate on the "owner_team" field.
func OwnerTeamHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldOwnerTeam, v))
}

// OwnerTeamIsNil applies the IsNil predicate on the "owner_team" field.
func OwnerTeamIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldOwnerTeam))
}

// OwnerTeamNotNil applies the NotNil predicate on the "owner_team" field.
func OwnerTeamNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldOwnerTeam))
}

// OwnerTeamEqualFold applies the EqualFold predicate on the "owner_team" field.
func OwnerTeamEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldOwnerTeam, v))
}

// OwnerTeamContainsFold applies the ContainsFold predicate on the "owner_team" field.
func OwnerTeamContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldOwnerTeam, v))
}

// RemediationIDEQ applies the EQ predicate on the "remediation_id" field.
func RemediationIDEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldRemediationID, v))
}

// RemediationIDNEQ applies the NEQ predicate on the "remediation_id" field.
func RemediationIDNEQ(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldRemediationID, v))
}

// RemediationIDIn applies the In predicate on the "remediation_id" field.
func RemediationIDIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldRemediationID, vs...))
}

// RemediationIDNotIn applies the NotIn predicate on the "remediation_id" field.
func RemediationIDNotIn(vs ...string) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldRemediationID, vs...))
}

// RemediationIDGT applies the GT predicate on the "remediation_id" field.
func RemediationIDGT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldRemediationID, v))
}

// RemediationIDGTE applies the GTE predicate on the "remediation_id" field.
func RemediationIDGTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldRemediationID, v))
}

// RemediationIDLT applies the LT predicate on the "remediation_id" field.
func RemediationIDLT(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldRemediationID, v))
}

// RemediationIDLTE applies the LTE predicate on the "remediation_id" field.
func RemediationIDLTE(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldRemediationID, v))
}

// RemediationIDContains applies the Contains predicate on the "remediation_id" field.
func RemediationIDContains(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContains(FieldRemediationID, v))
}

// RemediationIDHasPrefix applies the HasPrefix predicate on the "remediation_id" field.
func RemediationIDHasPrefix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasPrefix(FieldRemediationID, v))
}

// RemediationIDHasSuffix applies the HasSuffix predicate on the "remediation_id" field.
func RemediationIDHasSuffix(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldHasSuffix(FieldRemediationID, v))
}

// RemediationIDIsNil applies the IsNil predicate on the "remediation_id" field.
func RemediationIDIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldRemediationID))
}

// RemediationIDNotNil applies the NotNil predicate on the "remediation_id" field.
func RemediationIDNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldRemediationID))
}

// RemediationIDEqualFold applies the EqualFold predicate on the "remediation_id" field.
func RemediationIDEqualFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldEqualFold(FieldRemediationID, v))
}

// RemediationIDContainsFold applies the ContainsFold predicate on the "remediation_id" field.
func RemediationIDContainsFold(v string) predicate.RootCause {
	return predicate.RootCause(sql.FieldContainsFold(FieldRemediationID, v))
}

// RecurrenceCountEQ applies the EQ predicate on the "recurrence_count" field.
func RecurrenceCountEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldEQ(FieldRecurrenceCount, v))
}

// RecurrenceCountNEQ applies the NEQ predicate on the "recurrence_count" field.
func RecurrenceCountNEQ(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNEQ(FieldRecurrenceCount, v))
}

// RecurrenceCountIn applies the In predicate on the "recurrence_count" field.
func RecurrenceCountIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldIn(FieldRecurrenceCount, vs...))
}

// RecurrenceCountNotIn applies the NotIn predicate on the "recurrence_count" field.
func RecurrenceCountNotIn(vs ...int) predicate.RootCause {
	return predicate.RootCause(sql.FieldNotIn(FieldRecurrenceCount, vs...))
}

// RecurrenceCountGT applies the GT predicate on the "recurrence_count" field.
func RecurrenceCountGT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGT(FieldRecurrenceCount, v))
}

// RecurrenceCountGTE applies the GTE predicate on the "recurrence_count" field.
func RecurrenceCountGTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldGTE(FieldRecurrenceCount, v))
}

// RecurrenceCountLT applies the LT predicate on the "recurrence_count" field.
func RecurrenceCountLT(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLT(FieldRecurrenceCount, v))
}

// RecurrenceCountLTE applies the LTE predicate on the "recurrence_count" field.
func RecurrenceCountLTE(v int) predicate.RootCause {
	return predicate.RootCause(sql.FieldLTE(FieldRecurrenceCount, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldMetadata))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.RootCause {
	return predicate.RootCause(sql.FieldNotNull(FieldTags))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RootCause) predicate.RootCause {
	return predicate.RootCause(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RootCause) predicate.RootCause {
	return predicate.RootCause(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RootCause) predicate.RootCause {
	return predicate.RootCause(sql.NotPredicates(p))
}
