// Code generated by ent, DO NOT EDIT.

package entsignal

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the signal type in the database.
	Label = "signal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceName holds the string denoting the source_name field in the database.
	FieldSourceName = "source_name"
	// FieldSourceExternalID holds the string denoting the source_external_id field in the database.
	FieldSourceExternalID = "source_external_id"
	// FieldSourceURL holds the string denoting the source_url field in the database.
	FieldSourceURL = "source_url"
	// FieldDomainName holds the string denoting the domain_name field in the database.
	FieldDomainName = "domain_name"
	// FieldDomainSubdomain holds the string denoting the domain_subdomain field in the database.
	FieldDomainSubdomain = "domain_subdomain"
	// FieldDomainTeam holds the string denoting the domain_team field in the database.
	FieldDomainTeam = "domain_team"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEntities holds the string denoting the entities field in the database.
	FieldEntities = "entities"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldDerived holds the string denoting the derived field in the database.
	FieldDerived = "derived"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// Table holds the table name of the signal in the database.
	Table = "signals"
)

// Columns holds all SQL columns for signal fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldStatus,
	FieldSourceType,
	FieldSourceName,
	FieldSourceExternalID,
	FieldSourceURL,
	FieldDomainName,
	FieldDomainSubdomain,
	FieldDomainTeam,
	FieldSeverity,
	FieldSummary,
	FieldDescription,
	FieldEntities,
	FieldObservedAt,
	FieldReceivedAt,
	FieldFingerprint,
	FieldMetadata,
	FieldDerived,
	FieldTags,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Signal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceName orders the results by the source_name field.
func BySourceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceName, opts...).ToFunc()
}

// BySourceExternalID orders the results by the source_external_id field.
func BySourceExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceExternalID, opts...).ToFunc()
}

// BySourceURL orders the results by the source_url field.
func BySourceURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceURL, opts...).ToFunc()
}

// ByDomainName orders the results by the domain_name field.
func ByDomainName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainName, opts...).ToFunc()
}

// ByDomainSubdomain orders the results by the domain_subdomain field.
func ByDomainSubdomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainSubdomain, opts...).ToFunc()
}

// ByDomainTeam orders the results by the domain_team field.
func ByDomainTeam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomainTeam, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}
