// Code generated by ent, DO NOT EDIT.

package entsignal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/plexusone/omnisignal/store/sqlite/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldStatus, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceType, v))
}

// SourceName applies equality check predicate on the "source_name" field. It's identical to SourceNameEQ.
func SourceName(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceName, v))
}

// SourceExternalID applies equality check predicate on the "source_external_id" field. It's identical to SourceExternalIDEQ.
func SourceExternalID(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceExternalID, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceURL, v))
}

// DomainName applies equality check predicate on the "domain_name" field. It's identical to DomainNameEQ.
func DomainName(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDomainName, v))
}

// DomainSubdomain applies equality check predicate on the "domain_subdomain" field. It's identical to DomainSubdomainEQ.
func DomainSubdomain(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDomainSubdomain, v))
}

// DomainTeam applies equality check predicate on the "domain_team" field. It's identical to DomainTeamEQ.
func DomainTeam(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDomainTeam, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSeverity, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSummary, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDescription, v))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldObservedAt, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldReceivedAt, v))
}

// Fingerprint applies equality check predicate on the "fingerprint" field. It's identical to FingerprintEQ.
func Fingerprint(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldFingerprint, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldStatus, v))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceNameEQ applies the EQ predicate on the "source_name" field.
func SourceNameEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceName, v))
}

// SourceNameNEQ applies the NEQ predicate on the "source_name" field.
func SourceNameNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldSourceName, v))
}

// SourceNameIn applies the In predicate on the "source_name" field.
func SourceNameIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldSourceName, vs...))
}

// SourceNameNotIn applies the NotIn predicate on the "source_name" field.
func SourceNameNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldSourceName, vs...))
}

// SourceNameGT applies the GT predicate on the "source_name" field.
func SourceNameGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldSourceName, v))
}

// SourceNameGTE applies the GTE predicate on the "source_name" field.
func SourceNameGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldSourceName, v))
}

// SourceNameLT applies the LT predicate on the "source_name" field.
func SourceNameLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldSourceName, v))
}

// SourceNameLTE applies the LTE predicate on the "source_name" field.
func SourceNameLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldSourceName, v))
}

// SourceNameContains applies the Contains predicate on the "source_name" field.
func SourceNameContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldSourceName, v))
}

// SourceNameHasPrefix applies the HasPrefix predicate on the "source_name" field.
func SourceNameHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldSourceName, v))
}

// SourceNameHasSuffix applies the HasSuffix predicate on the "source_name" field.
func SourceNameHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldSourceName, v))
}

// SourceNameEqualFold applies the EqualFold predicate on the "source_name" field.
func SourceNameEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldSourceName, v))
}

// SourceNameContainsFold applies the ContainsFold predicate on the "source_name" field.
func SourceNameContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldSourceName, v))
}

// SourceExternalIDEQ applies the EQ predicate on the "source_external_id" field.
func SourceExternalIDEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceExternalID, v))
}

// SourceExternalIDNEQ applies the NEQ predicate on the "source_external_id" field.
func SourceExternalIDNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldSourceExternalID, v))
}

// SourceExternalIDIn applies the In predicate on the "source_external_id" field.
func SourceExternalIDIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldSourceExternalID, vs...))
}

// SourceExternalIDNotIn applies the NotIn predicate on the "source_external_id" field.
func SourceExternalIDNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldSourceExternalID, vs...))
}

// SourceExternalIDGT applies the GT predicate on the "source_external_id" field.
func SourceExternalIDGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldSourceExternalID, v))
}

// SourceExternalIDGTE applies the GTE predicate on the "source_external_id" field.
func SourceExternalIDGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldSourceExternalID, v))
}

// SourceExternalIDLT applies the LT predicate on the "source_external_id" field.
func SourceExternalIDLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldSourceExternalID, v))
}

// SourceExternalIDLTE applies the LTE predicate on the "source_external_id" field.
func SourceExternalIDLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldSourceExternalID, v))
}

// SourceExternalIDContains applies the Contains predicate on the "source_external_id" field.
func SourceExternalIDContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldSourceExternalID, v))
}

// SourceExternalIDHasPrefix applies the HasPrefix predicate on the "source_external_id" field.
func SourceExternalIDHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldSourceExternalID, v))
}

// SourceExternalIDHasSuffix applies the HasSuffix predicate on the "source_external_id" field.
func SourceExternalIDHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldSourceExternalID, v))
}

// SourceExternalIDIsNil applies the IsNil predicate on the "source_external_id" field.
func SourceExternalIDIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldSourceExternalID))
}

// SourceExternalIDNotNil applies the NotNil predicate on the "source_external_id" field.
func SourceExternalIDNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldSourceExternalID))
}

// SourceExternalIDEqualFold applies the EqualFold predicate on the "source_external_id" field.
func SourceExternalIDEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldSourceExternalID, v))
}

// SourceExternalIDContainsFold applies the ContainsFold predicate on the "source_external_id" field.
func SourceExternalIDContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldSourceExternalID, v))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLIsNil applies the IsNil predicate on the "source_url" field.
func SourceURLIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldSourceURL))
}

// SourceURLNotNil applies the NotNil predicate on the "source_url" field.
func SourceURLNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldSourceURL))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldSourceURL, v))
}

// DomainNameEQ applies the EQ predicate on the "domain_name" field.
func DomainNameEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDomainName, v))
}

// DomainNameNEQ applies the NEQ predicate on the "domain_name" field.
func DomainNameNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldDomainName, v))
}

// DomainNameIn applies the In predicate on the "domain_name" field.
func DomainNameIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldDomainName, vs...))
}

// DomainNameNotIn applies the NotIn predicate on the "domain_name" field.
func DomainNameNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldDomainName, vs...))
}

// DomainNameGT applies the GT predicate on the "domain_name" field.
func DomainNameGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldDomainName, v))
}

// DomainNameGTE applies the GTE predicate on the "domain_name" field.
func DomainNameGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldDomainName, v))
}

// DomainNameLT applies the LT predicate on the "domain_name" field.
func DomainNameLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldDomainName, v))
}

// DomainNameLTE applies the LTE predicate on the "domain_name" field.
func DomainNameLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldDomainName, v))
}

// DomainNameContains applies the Contains predicate on the "domain_name" field.
func DomainNameContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldDomainName, v))
}

// DomainNameHasPrefix applies the HasPrefix predicate on the "domain_name" field.
func DomainNameHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldDomainName, v))
}

// DomainNameHasSuffix applies the HasSuffix predicate on the "domain_name" field.
func DomainNameHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldDomainName, v))
}

// DomainNameEqualFold applies the EqualFold predicate on the "domain_name" field.
func DomainNameEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldDomainName, v))
}

// DomainNameContainsFold applies the ContainsFold predicate on the "domain_name" field.
func DomainNameContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldDomainName, v))
}

// DomainSubdomainEQ applies the EQ predicate on the "domain_subdomain" field.
func DomainSubdomainEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDomainSubdomain, v))
}

// DomainSubdomainNEQ applies the NEQ predicate on the "domain_subdomain" field.
func DomainSubdomainNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldDomainSubdomain, v))
}

// DomainSubdomainIn applies the In predicate on the "domain_subdomain" field.
func DomainSubdomainIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldDomainSubdomain, vs...))
}

// DomainSubdomainNotIn applies the NotIn predicate on the "domain_subdomain" field.
func DomainSubdomainNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldDomainSubdomain, vs...))
}

// DomainSubdomainGT applies the GT predicate on the "domain_subdomain" field.
func DomainSubdomainGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldDomainSubdomain, v))
}

// DomainSubdomainGTE applies the GTE predicate on the "domain_subdomain" field.
func DomainSubdomainGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldDomainSubdomain, v))
}

// DomainSubdomainLT applies the LT predicate on the "domain_subdomain" field.
func DomainSubdomainLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldDomainSubdomain, v))
}

// DomainSubdomainLTE applies the LTE predicate on the "domain_subdomain" field.
func DomainSubdomainLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldDomainSubdomain, v))
}

// DomainSubdomainContains applies the Contains predicate on the "domain_subdomain" field.
func DomainSubdomainContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldDomainSubdomain, v))
}

// DomainSubdomainHasPrefix applies the HasPrefix predicate on the "domain_subdomain" field.
func DomainSubdomainHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldDomainSubdomain, v))
}

// DomainSubdomainHasSuffix applies the HasSuffix predicate on the "domain_subdomain" field.
func DomainSubdomainHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldDomainSubdomain, v))
}

// DomainSubdomainIsNil applies the IsNil predicate on the "domain_subdomain" field.
func DomainSubdomainIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldDomainSubdomain))
}

// DomainSubdomainNotNil applies the NotNil predicate on the "domain_subdomain" field.
func DomainSubdomainNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldDomainSubdomain))
}

// DomainSubdomainEqualFold applies the EqualFold predicate on the "domain_subdomain" field.
func DomainSubdomainEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldDomainSubdomain, v))
}

// DomainSubdomainContainsFold applies the ContainsFold predicate on the "domain_subdomain" field.
func DomainSubdomainContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldDomainSubdomain, v))
}

// DomainTeamEQ applies the EQ predicate on the "domain_team" field.
func DomainTeamEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDomainTeam, v))
}

// DomainTeamNEQ applies the NEQ predicate on the "domain_team" field.
func DomainTeamNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldDomainTeam, v))
}

// DomainTeamIn applies the In predicate on the "domain_team" field.
func DomainTeamIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldDomainTeam, vs...))
}

// DomainTeamNotIn applies the NotIn predicate on the "domain_team" field.
func DomainTeamNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldDomainTeam, vs...))
}

// DomainTeamGT applies the GT predicate on the "domain_team" field.
func DomainTeamGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldDomainTeam, v))
}

// DomainTeamGTE applies the GTE predicate on the "domain_team" field.
func DomainTeamGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldDomainTeam, v))
}

// DomainTeamLT applies the LT predicate on the "domain_team" field.
func DomainTeamLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldDomainTeam, v))
}

// DomainTeamLTE applies the LTE predicate on the "domain_team" field.
func DomainTeamLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldDomainTeam, v))
}

// DomainTeamContains applies the Contains predicate on the "domain_team" field.
func DomainTeamContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldDomainTeam, v))
}

// DomainTeamHasPrefix applies the HasPrefix predicate on the "domain_team" field.
func DomainTeamHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldDomainTeam, v))
}

// DomainTeamHasSuffix applies the HasSuffix predicate on the "domain_team" field.
func DomainTeamHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldDomainTeam, v))
}

// DomainTeamIsNil applies the IsNil predicate on the "domain_team" field.
func DomainTeamIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldDomainTeam))
}

// DomainTeamNotNil applies the NotNil predicate on the "domain_team" field.
func DomainTeamNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldDomainTeam))
}

// DomainTeamEqualFold applies the EqualFold predicate on the "domain_team" field.
func DomainTeamEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldDomainTeam, v))
}

// DomainTeamContainsFold applies the ContainsFold predicate on the "domain_team" field.
func DomainTeamContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldDomainTeam, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldSeverity, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldSummary, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldDescription, v))
}

// EntitiesIsNil applies the IsNil predicate on the "entities" field.
func EntitiesIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldEntities))
}

// EntitiesNotNil applies the NotNil predicate on the "entities" field.
func EntitiesNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldEntities))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldObservedAt, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldReceivedAt, v))
}

// FingerprintEQ applies the EQ predicate on the "fingerprint" field.
func FingerprintEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEQ(FieldFingerprint, v))
}

// FingerprintNEQ applies the NEQ predicate on the "fingerprint" field.
func FingerprintNEQ(v string) predicate.Signal {
	return predicate.Signal(sql.FieldNEQ(FieldFingerprint, v))
}

// FingerprintIn applies the In predicate on the "fingerprint" field.
func FingerprintIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldIn(FieldFingerprint, vs...))
}

// FingerprintNotIn applies the NotIn predicate on the "fingerprint" field.
func FingerprintNotIn(vs ...string) predicate.Signal {
	return predicate.Signal(sql.FieldNotIn(FieldFingerprint, vs...))
}

// FingerprintGT applies the GT predicate on the "fingerprint" field.
func FingerprintGT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGT(FieldFingerprint, v))
}

// FingerprintGTE applies the GTE predicate on the "fingerprint" field.
func FingerprintGTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldGTE(FieldFingerprint, v))
}

// FingerprintLT applies the LT predicate on the "fingerprint" field.
func FingerprintLT(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLT(FieldFingerprint, v))
}

// FingerprintLTE applies the LTE predicate on the "fingerprint" field.
func FingerprintLTE(v string) predicate.Signal {
	return predicate.Signal(sql.FieldLTE(FieldFingerprint, v))
}

// FingerprintContains applies the Contains predicate on the "fingerprint" field.
func FingerprintContains(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContains(FieldFingerprint, v))
}

// FingerprintHasPrefix applies the HasPrefix predicate on the "fingerprint" field.
func FingerprintHasPrefix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasPrefix(FieldFingerprint, v))
}

// FingerprintHasSuffix applies the HasSuffix predicate on the "fingerprint" field.
func FingerprintHasSuffix(v string) predicate.Signal {
	return predicate.Signal(sql.FieldHasSuffix(FieldFingerprint, v))
}

// FingerprintIsNil applies the IsNil predicate on the "fingerprint" field.
func FingerprintIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldFingerprint))
}

// FingerprintNotNil applies the NotNil predicate on the "fingerprint" field.
func FingerprintNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldFingerprint))
}

// FingerprintEqualFold applies the EqualFold predicate on the "fingerprint" field.
func FingerprintEqualFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldEqualFold(FieldFingerprint, v))
}

// FingerprintContainsFold applies the ContainsFold predicate on the "fingerprint" field.
func FingerprintContainsFold(v string) predicate.Signal {
	return predicate.Signal(sql.FieldContainsFold(FieldFingerprint, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldMetadata))
}

// DerivedIsNil applies the IsNil predicate on the "derived" field.
func DerivedIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldDerived))
}

// DerivedNotNil applies the NotNil predicate on the "derived" field.
func DerivedNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldDerived))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Signal {
	return predicate.Signal(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Signal {
	return predicate.Signal(sql.FieldNotNull(FieldTags))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Signal) predicate.Signal {
	return predicate.Signal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Signal) predicate.Signal {
	return predicate.Signal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Signal) predicate.Signal {
	return predicate.Signal(sql.NotPredicates(p))
}
